# SPDX-License-Identifier: Apache-2.0
import pathlib,json,hashlib,subprocess,datetime,platform
root=pathlib.Path.cwd();run=root/'research/shared/runs/20260919T200002Z-presentation';failed=root/'research/shared/runs/20260919T195841Z-presentation'
keys=[next((root/'research/items').glob(p)).name for p in ['R318.decode*','R360.*','R289.*','R323.fan*','R118.one*']]
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def write(p,x):p.write_text(json.dumps(x,indent=2)+'\n')
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return str(p.relative_to(root))
rev=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip();diff=subprocess.check_output(['git','diff','--binary','HEAD'])
(run/'tracked-diff.patch').write_bytes(diff)
rows=[
('pursue','passed','One closed 12-frame H.264 I/P GOP decoded once and retained for reverse hash/timestamp presentation; all frames exact against independent host decode. 55,296 visible plane bytes; 24-frame budget and dependent-entry controls rejected before decode; retained frames closed.','Add actual reverse UI presenter, cache replacement/cancellation and GOP capability parser; then compare persistent cached baseline with declared byte budget.','Immutable closed GOP cache batch only; no B/open GOP, renderer cadence, long-GOP fallback, or production seek lifecycle.'),
('stop_current_profile','pending','Continuing H.264 decode retargeted 3→8→10 and published only frame 10, matching host output. Current UI already coalesces scrub commits; this component submitted 12 packets versus 11 needed for the final-only target baseline, so it establishes no saved work for the present UI.','Reopen when a real workload issues multiple already-started forward seeks; execute source/config changes, backward restart and stale callbacks before performance testing.','Eligibility predicates reject backward/source changes, but their full restart paths were not executed. No user latency claim.'),
('pursue','pending','Six extracted independent same-configuration H.264 IDR jobs used one decoder. Full pixels equal six separately constructed decoders and host decode. Duplicate source timestamps remained distinct via dispatch identity; canceled job 2 was discarded.','Add malformed-job recovery, actual incompatible configuration groups and stale output after source-generation replacement; then compare a bounded pool and per-job baseline under an interactive arrival workload.','Same configuration synthetic IDR samples only. Configuration signature adverse check is not execution of reconfiguration recovery; no physical native/hardware identity claim.'),
('pursue','pending','Two actual workers received cloned VideoFrame references, materialized separate cropped regions and matched reference pixels/timestamps for four frames. One 20 ms slow worker, stale generation result and surviving newer-generation output exercised. Peak outstanding transferred references was two; all workers terminated and frames closed.','Implement enforceable consumer lease expiry/cancellation and measure retention under decoder backpressure before claiming complete multi-consumer correctness or benefit.','No explicit copyTo before fanout; browser internal copying and retained native surfaces were not measured. Source generation checked but prompt cancellation of an unresponsive worker remains untested.'),
('pursue','pending','One decoded H.264 source supplied synchronized left/right crop views in two workers. Four paired outputs matched independent same-browser crop rendering and original timestamps; underlying decoded planes matched host oracle. Slow and stale consumer probes preserved the newer output.','Add bounded live presentation owner with cancel/replace cleanup and a real two-view workload; quantify whether a second decoder is actually avoided in the target UI.','Two-view component only; parent source retains the bounded fixture frames. Lease count is not complete native decoder-surface accounting or zero-copy evidence.')]
summary='''<!-- SPDX-License-Identifier: CC-BY-4.0 -->
# Presentation component experiments

The corrected run uses 64x48, 12 fps synthetic H.264 baseline I/P and all-IDR fixtures. FFmpeg host decoding is an independent pixel oracle with passthrough cadence and an exact frame-count assertion. Browser decoding prefers software; this hint does not prove physical decoder identity. No production routing or player implementation changed.

All five components ran; no fallback was used. Pixel ownership tests compare canonical visible I420 planes, converting NV12 plane layout when needed, rather than comparing padded surfaces. Reverse playback is reverse presentation of forward-decoded pictures, never reversed packet submission. Independent-job baseline creates six decoders; the candidate creates one. Worker view baseline is a separate canvas rendering of the same decoded frame.

The earlier run preserved two useful setup failures. Chrome rejects explicit copyTo I420 conversion for some decoded formats. After native plane extraction, the independent host oracle initially disagreed because raw H.264 demux timing caused host FFmpeg to duplicate frames. The failed raw outputs contain twice the expected frame count. The corrected oracle uses -fps_mode passthrough and asserts exact counts; all 24 browser frames and six IDR jobs then match host pixels exactly. The earlier default decoder variant was not rerun after correcting the oracle; it is not a decoder correctness failure.

No performance stage was accepted. Decoder object counts and 55,296 visible retained GOP bytes are component accounting, not total process memory, physical surfaces, hardware utilization, latency or energy. R360 has no demonstrated opportunity against the existing final-only scrub UI. Missing full consumer cancellation, malformed-job recovery and configuration/source restart paths remain explicit correctness work for the relevant items. No production integration or release qualification is implied.
'''
(run/'analysis.md').write_text(summary)
(failed/'analysis.md').write_text('<!-- SPDX-License-Identifier: CC-BY-4.0 -->\n# Preserved preparation failures\n\nSee the corrected run ../20260919T200002Z-presentation/analysis.md. This run contains explicit-format copy failure and a host oracle cadence duplication, not a qualified candidate-negative result. Snapshots retain Apache-2.0 source headers and identify their variant in their filename.\n')
with (run/'commands.log').open('a') as f:f.write('node research/shared/tooling/presentation/probe.mjs '+rel(run)+'\nexit=0\n')
for directory,passed in [(failed,False),(run,True)]:
 record={'schema':1,'run_id':directory.name,'item_keys':keys,'stage':'correctness','status':'passed' if passed else 'failed','recorded_at_utc':now,'working_directory':str(root),'commands':['python3 research/shared/tooling/presentation/prepare.py '+rel(directory),'node research/shared/tooling/presentation/probe.mjs '+rel(directory)],'environment':{'git_revision':rev,'dirty_diff_sha256':hashlib.sha256(diff).hexdigest(),'browser':'152.0.7977.83','os_device':platform.platform(),'decoder_hint':'prefer-software in corrected run'},'candidate':{'executed':passed,'fallback_observed':False if passed else None},'acceptance':{'contract':'Scoped pixel/timestamp component assertions; per-item lifecycle exclusions below','oracle':'host FFmpeg raw YUV passthrough; separate browser decoder and crop baselines','passed':passed},'performance':{'applicable':False,'reason':'This run is correctness/opportunity only. Future performance remains pending for pursue items.'},'limits':[r[4] for r in rows],'decision':'See per-item records; whole-player qualification not established'}
 if not passed:record['status']='failed';record['failure_category']='preparation';record['commands']=['See commands.log for fixture generation; three preserved probe source variants explain failed preparations.'];record['candidate']['executed']=True
 write(directory/'run.json',record)
 artifacts=[]
 paths=list(directory.rglob('*'))
 if passed:paths+=list((root/'research/shared/tooling/presentation').glob('*'))
 for p in paths:
  if not p.is_file() or p.name=='manifest.json':continue
  role='source' if p.suffix in ['.mjs','.py'] else 'fixture' if p.suffix in ['.h264','.yuv'] or p.name=='input.json' else 'result'
  license='Apache-2.0' if role=='source' else 'NOASSERTION' if p.suffix=='.patch' else 'CC-BY-4.0'
  artifacts.append({'path':rel(p),'role':role,'sha256':digest(p),'bytes':p.stat().st_size,'license':license,'provenance':'Original independent experiment tooling' if role=='source' else 'FFmpeg lavfi testsrc2 generated synthetic fixture; generation commands captured' if role=='fixture' else 'Local observed experiment record; patch retains original file licenses' if p.suffix=='.patch' else 'Original local research result','notice_paths':['docs/LICENSING.md','docs/MEDIA-NOTICES.md']})
 write(directory/'manifest.json',{'schema':1,'run_id':directory.name,'path_base':'repository_root','artifacts':artifacts})
for key,(state,correct,reason,next_action,limits) in zip(keys,rows):
 folder=root/'research/items'/key;p=folder/'item.json';item=json.loads(p.read_text());ev=[rel(run/'results.json'),rel(run/'manifest.json'),rel(run/'analysis.md')]
 item['investigation_contract']={'scope':'Bounded synthetic H.264 WebCodecs component, full key-specific result below','baseline':'Independent host pixels and separate browser decode/render baseline','success_criteria':'All required scoped assertions pass; no fallback; retain unsatisfied lifecycle gates','effort_limit':'One shared tiny fixture preparation and browser component run; no production owner rewrite','falsifier':'Pixel/timestamp mismatch, incorrect job correlation or stale generation accepted','exclusions':limits}
 for stage in ['define','prepare','screen','results','decision']:item['stages'][stage]={'status':'passed','basis':reason if stage=='screen' else 'Scoped contract, exact commands/fixtures, immutable outputs and decision recorded for this run; not production qualification.','evidence':ev}
 item['stages']['correctness']={'status':correct,'basis':reason+' '+limits if correct=='passed' else 'Scoped output checks pass; full affected lifecycle acceptance remains pending: '+next_action,'evidence':ev}
 item['stages']['performance']={'status':'not_applicable' if state=='stop_current_profile' else 'pending','basis':'Current final-only scrub has no demonstrated redundant decode opportunity; no benchmark warranted.' if state=='stop_current_profile' else 'Not measured. Complete missing lifecycle gates and predeclare an actual workload, threshold and complete costs before benchmarking.','evidence':ev}
 record={'key':key,'state':state,'disposition':state,'stage':'decision','run_ids':[run.name,failed.name],'recorded_at_utc':now,'evidence_level':'component_test','candidate_executed':True,'fallback_observed':False,'reason':reason,'scope':limits,'evidence':ev,'next_test':next_action,'reopen_condition':next_action}
 event={'campaign':'research-presentation-components','record':record};item['current_decision']=event;item['next_action']=next_action;write(p,item)
 with (folder/'history.jsonl').open('a') as f:f.write(json.dumps(event)+'\n')
 (folder/'README.md').write_text(f'<!-- SPDX-License-Identifier: CC-BY-4.0 -->\n\n# {item["title"]}\n\n`{key}`\n\nCurrent disposition: **{state}**. Component evidence; no production integration or release qualification.\n\n{reason}\n\nScope limits: {limits}\n\n'+ '\n'.join(f'- {s}: **{v["status"]}** — {v["basis"]}' for s,v in item['stages'].items())+f'\n\nNext: {next_action}\n\n[Current record](item.json) · [History](history.jsonl) · [Evidence index](evidence/index.json)\n\n[Shared results](../../../shared/runs/{run.name}/results.json) · [Analysis](../../../shared/runs/{run.name}/analysis.md)\n')
 idx=json.loads((folder/'evidence/index.json').read_text())
 for directory in [failed,run]:
  for file in directory.rglob('*'):
   if file.is_file():idx['artifacts'].append({'path':rel(file),'sha256':digest(file),'bytes':file.stat().st_size,'uses':[{'campaign':'research-presentation-components','run_id':directory.name}]})
 write(folder/'evidence/index.json',idx)
print(json.dumps({'keys':keys,'run':run.name,'correctness_passed':[keys[0]],'correctness_pending':keys[1:]},indent=2))
