// SPDX-License-Identifier: Apache-2.0
#include <jxl/encode.h>
#include <jxl/decode.h>
#include <fstream>
#include <vector>
#include <string>
#include <iostream>
#include <cstdlib>
int main(int argc,char**argv){if(argc!=5)return 2;std::ifstream f(argv[2],std::ios::binary);std::vector<uint8_t>data((std::istreambuf_iterator<char>(f)),{}),out;int rc=0;if(std::string(argv[1])=="encode"){auto*e=JxlEncoderCreate(nullptr);JxlEncoderUseContainer(e,JXL_TRUE);JxlEncoderStoreJPEGMetadata(e,atoi(argv[4])?JXL_TRUE:JXL_FALSE);auto*s=JxlEncoderFrameSettingsCreate(e,nullptr);JxlEncoderSetFrameDistance(s,0);JxlEncoderSetFrameLossless(s,JXL_TRUE);if(JxlEncoderAddJPEGFrame(s,data.data(),data.size())!=JXL_ENC_SUCCESS)rc=3;else{JxlEncoderCloseInput(e);out.resize(1024*1024);auto*next=out.data();size_t avail=out.size();auto status=JxlEncoderProcessOutput(e,&next,&avail);if(status!=JXL_ENC_SUCCESS)rc=4;else out.resize(out.size()-avail);}JxlEncoderDestroy(e);}else{auto*d=JxlDecoderCreate(nullptr);JxlDecoderSubscribeEvents(d,JXL_DEC_JPEG_RECONSTRUCTION|JXL_DEC_FULL_IMAGE);JxlDecoderSetInput(d,data.data(),data.size());JxlDecoderCloseInput(d);bool reconstruct=false;size_t cap=std::stoul(argv[4]);if(cap>1024*1024){JxlDecoderDestroy(d);return 5;}for(;;){auto status=JxlDecoderProcessInput(d);if(status==JXL_DEC_JPEG_RECONSTRUCTION){reconstruct=true;out.resize(cap);if(JxlDecoderSetJPEGBuffer(d,out.data(),out.size())!=JXL_DEC_SUCCESS){rc=6;break;}}else if(status==JXL_DEC_SUCCESS){if(!reconstruct)rc=7;else out.resize(out.size()-JxlDecoderReleaseJPEGBuffer(d));break;}else if(status==JXL_DEC_JPEG_NEED_MORE_OUTPUT){rc=8;break;}else if(status==JXL_DEC_ERROR||status==JXL_DEC_NEED_MORE_INPUT||status==JXL_DEC_NEED_IMAGE_OUT_BUFFER){rc=9;break;}}JxlDecoderDestroy(d);}if(!rc){std::ofstream o(argv[3],std::ios::binary);o.write((char*)out.data(),out.size());}std::cout<<"{\"input_bytes\":"<<data.size()<<",\"output_bytes\":"<<(rc?0:out.size())<<",\"exit\":"<<rc<<",\"owner_destroyed\":true}\n";return rc;}
