// SPDX-License-Identifier: Apache-2.0
import{chromium}from'playwright';import{spawn}from'node:child_process';import{readFile,writeFile}from'node:fs/promises';
const out=process.argv[2],mode=process.argv[3],result={mode,plan:out+'/plan.json'};const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser;
try{const origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('server')),10000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(timer);resolve(m[0])}})});browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.route('**/engine-ass/subtitles.*',async route=>{const ext=new URL(route.request().url()).pathname.split('.').at(-1);await route.fulfill({contentType:ext==='wasm'?'application/wasm':'text/javascript',headers:{'Cross-Origin-Embedder-Policy':'require-corp','Cross-Origin-Resource-Policy':'same-origin'},body:await readFile('build/top100-ass/runtime/subtitles.'+ext)});});await page.goto(origin+'/examples/custom-controls.html');result.data=await page.evaluate(async mode=>{
const assert=(v,m)=>{if(!v)throw Error(m)},hash=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
const header='[Script Info]\nScriptType: v4.00+\nPlayResX: 320\nPlayResY: 180\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,DejaVu Sans,24,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n';const script=text=>new TextEncoder().encode(header+'Dialogue: 0,0:00:00.00,0:00:04.00,Default,,0,0,0,,'+text+'\n');
const raster=t=>{const im=new ImageData(t.w,t.h);for(let i=0;i<t.bytes.length;i++){im.data[i*4]=t.color>>>24;im.data[i*4+1]=(t.color>>>16)&255;im.data[i*4+2]=(t.color>>>8)&255;im.data[i*4+3]=Math.round(t.bytes[i]*(255-(t.color&255))/255)}const c=new OffscreenCanvas(t.w,t.h);c.getContext('2d').putImageData(im,0,0);return c;};
const trial=async(candidate,reference)=>{const begin=performance.now(),worker=new Worker('/web/native-ass-worker.js',{type:'module'});let id=0;const pending=new Map();worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);clearTimeout(p.timer);data.error?p.reject(Error(data.error)):p.resolve(data)};const rpc=(type,data={})=>new Promise((resolve,reject)=>{const seq=++id;pending.set(seq,{resolve,reject,timer:setTimeout(()=>reject(Error(type+' timeout')),10000)});worker.postMessage({id:seq,type,...data})});let rows=[],cache=new Map(),retained=0,peak=0,hits=0,misses=0,epoch=0;let templateCount=0,requests=0;
try{await rpc('init',{fonts:[{name:'DejaVuSans.ttf',bytes:await(await fetch('/fixtures/DejaVuSans.ttf')).arrayBuffer()}]});
if(mode==='R021'){let ordinal=0;for(const text of ['Static caption','{\\k50}One {\\k50}two {\\k50}three']){epoch++;cache.clear();retained=0;await rpc('load',{bytes:script(text)});let lastWidth=0;for(let rep=0;rep<8;rep++)for(const [seconds,width,height]of[[.1,320,180],[.1,320,180],[.6,320,180],[1.2,320,180],[1.2,640,360],[.1,640,360]]){if(lastWidth&&lastWidth!==width){epoch++;cache.clear();retained=0;}lastWidth=width;const r=await rpc('render',{seconds,width,height,sourceWidth:320,sourceHeight:180,force:true});requests++;const c=new OffscreenCanvas(width,height),ctx=c.getContext('2d');for(const t of r.tiles){let tile;if(candidate){const key=epoch+':'+[t.x,t.y,t.w,t.h,t.color,...t.bytes].join(',');tile=cache.get(key);if(tile)hits++;else{misses++;tile=raster(t);const size=t.w*t.h*4;if(retained+size>1024*1024){cache.clear();retained=0;}cache.set(key,tile);retained+=size;peak=Math.max(peak,retained)}}else tile=raster(t);ctx.drawImage(tile,t.x,t.y)}const h=await hash(ctx.getImageData(0,0,width,height).data);if(reference)assert(h===reference[ordinal].hash,'exact subtitle cache pixels');rows.push({ordinal:ordinal++,hash:h,seconds,width});c.width=c.height=0;}}assert(!candidate||hits>0&&peak<=1024*1024,'cache bounds');}
else{const text='{\\fad(300,300)}Fade caption';const admit=t=>t==='{\\fad(300,300)}Fade caption';assert(admit(text)&&!admit('{\\move(0,0,10,10)}Fade caption'),'restricted program gate');await rpc('load',{bytes:script(text)});let templates;if(candidate){templates=[];for(const seconds of [1,.15]){templates.push((await rpc('render',{seconds,width:320,height:180,sourceWidth:320,sourceHeight:180,force:true})).tiles);requests++;}templateCount=templates.length;}let ordinal=0;for(let rep=0;rep<14;rep++)for(const seconds of [.05,.15,.3,1,3.8,3.95,.15]){let tiles;if(candidate){const opacity=Math.min(1,seconds/.3,(4-seconds)/.3),base=opacity===1?templates[0]:templates[1];tiles=base.map((t,i)=>({...t,color:((t.color&0xffffff00)|(255-Math.round((255-(templates[0][i].color&255))*opacity)))>>>0}));}else{tiles=(await rpc('render',{seconds,width:320,height:180,sourceWidth:320,sourceHeight:180,force:true})).tiles;requests++;}const row={seconds,tiles:await Promise.all(tiles.map(async t=>({geometry:[t.x,t.y,t.w,t.h],mask:await hash(t.bytes),rgb:t.color>>>8,alpha:t.color&255})))};if(reference){const ref=reference[ordinal];assert(row.tiles.length===ref.tiles.length,'tile count');for(let i=0;i<row.tiles.length;i++){const a=row.tiles[i],b=ref.tiles[i];assert(JSON.stringify(a.geometry)===JSON.stringify(b.geometry)&&a.mask===b.mask&&a.rgb===b.rgb&&Math.abs(a.alpha-b.alpha)<=1,'fad exactmask alpha<=1');}}rows.push(row);ordinal++;}}
}finally{worker.terminate();for(const v of cache.values())v.width=v.height=0;cache.clear();retained=0;}return {candidate,wallMs:performance.now()-begin,rows,requests,templateCount,hits,misses,peakRetainedBytes:peak,retainedAtEnd:retained,cleanup:true};};
const reference=await trial(false),check=await trial(true,reference.rows),pairs=[];for(let i=0;i<9;i++){const row={pair:i};for(const c of i%2?[true,false]:[false,true]){const t=await trial(c,reference.rows);row[c?'candidate':'baseline']={...t,rows:undefined,checkedOutputs:t.rows.length}}pairs.push(row)}return {correctness:{baseline:{...reference,rows:undefined,checkedOutputs:reference.rows.length},candidate:{...check,rows:undefined,checkedOutputs:check.rows.length}},pairs,reference:reference.rows};},mode);result.passed=true;await page.evaluate(()=>player.destroy());}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();await writeFile(out+'/'+mode+'-results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({mode,passed:result.passed,error:result.error,pairs:result.data?.pairs?.map(p=>[p.baseline.wallMs,p.candidate.wallMs])}));}
