// SPDX-License-Identifier: Apache-2.0
import{chromium}from'playwright';import{readFile,writeFile}from'node:fs/promises';import{createServer}from'node:http';
const out=process.argv[2],mode=process.argv[3],input=JSON.parse(await readFile('research/shared/runs/20260919T200002Z-presentation/input.json','utf8'));input.raw=[...await readFile('research/shared/runs/20260919T200002Z-presentation/gop.yuv')];const server=createServer((q,r)=>r.end('<!doctype html>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser,result={mode,plan:out+'/plan.json'};
try{browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);result.data=await page.evaluate(async({input,mode})=>{
const assert=(v,m)=>{if(!v)throw Error(m)},hash=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
const canonical=async f=>{const a=new Uint8Array(f.allocationSize()),l=await f.copyTo(a),b=new Uint8Array(4608);for(let y=0;y<48;y++)b.set(a.subarray(l[0].offset+y*l[0].stride,l[0].offset+y*l[0].stride+64),y*64);if(f.format==='NV12'){for(let y=0;y<24;y++)for(let x=0;x<32;x++){b[3072+y*32+x]=a[l[1].offset+y*l[1].stride+x*2];b[3840+y*32+x]=a[l[1].offset+y*l[1].stride+x*2+1];}}else{assert(f.format==='I420','format');for(let p=1;p<3;p++)for(let y=0;y<24;y++)b.set(a.subarray(l[p].offset+y*l[p].stride,l[p].offset+y*l[p].stride+32),3072+(p-1)*768+y*32);}return b};
const cfg={codec:'avc1.42C00A',codedWidth:64,codedHeight:48,optimizeForLatency:true,hardwareAcceleration:'prefer-software'};
const decode=async packets=>{const fs=[],errors=[],d=new VideoDecoder({output:f=>fs.push(f),error:e=>errors.push(String(e))});try{d.configure(cfg);for(const p of packets)d.decode(new EncodedVideoChunk({type:p.key?'key':'delta',timestamp:p.timestamp,data:new Uint8Array(p.data)}));await d.flush();assert(!errors.length,'decoder error');return fs;}catch(e){fs.forEach(f=>f.close());throw e}finally{if(d.state!=='closed')d.close()}};
const trial=async candidate=>{const start=performance.now();let owners=0,closed=0,packets=0,peak=0,copyBytes=0;
if(mode==='R318'){const src=input.gop.packets.slice(0,12);let cache;if(candidate){cache=await decode(src);owners++;packets+=12;peak=cache.length;}for(let n=11;n>=0;n--){let fs=cache;if(!candidate){fs=await decode(src.slice(0,n+1));owners++;packets+=n+1;peak=Math.max(peak,fs.length)}const f=fs[n];assert(f.timestamp===src[n].timestamp&&await hash(await canonical(f))===input.gop.hashes[n],'reverse oracle');if(!candidate){fs.forEach(f=>f.close());closed+=fs.length}}if(candidate){cache.forEach(f=>f.close());closed+=cache.length}return {candidate,wallMs:performance.now()-start,owners,packets,peakFrames:peak,closed,exact:true};}
if(mode==='R289'){const jobs=input.idr.packets.map((p,i)=>({...p,timestamp:i*1000}));if(candidate){const fs=await decode(jobs);owners++;assert(fs.length===jobs.length,'six');for(const f of fs){const i=f.timestamp/1000;assert(Number.isInteger(i)&&await hash(await canonical(f))===input.idr.hashes[i],'identity');f.close();closed++;}}else for(let i=0;i<jobs.length;i++){const fs=await decode([jobs[i]]);owners++;assert(fs.length===1&&await hash(await canonical(fs[0]))===input.idr.hashes[i],'individual');fs.forEach(f=>f.close());closed+=fs.length}return {candidate,wallMs:performance.now()-start,owners,closed,exact:true};}
const pool=await makePool();let sources=[];try{sources.push(await decode(input.gop.packets.slice(0,12)));owners++;if(mode==='R118'&&!candidate){sources.push(await decode(input.gop.packets.slice(0,12)));owners++;}for(let n=0;n<12;n++){await Promise.all([0,1].map(async view=>{const f=sources[view]?[sources[view][n]][0]:sources[0][n];let transfer;if(mode==='R323'&&!candidate){const bytes=await canonical(f);copyBytes+=bytes.byteLength;transfer=new VideoFrame(bytes,{format:'I420',codedWidth:64,codedHeight:48,timestamp:f.timestamp});}else transfer=f.clone();const reply=await pool.submit(view,transfer,view,1,0);assert(reply.hash===roiHashes[n][view]&&reply.timestamp===input.gop.packets[n].timestamp&&reply.closed&&!reply.cancelled,'worker oracle');}));}peak=pool.peak;assert(pool.active===0,'retained');}finally{sources.flat().forEach(f=>{f.close();closed++});await pool.stop();}return {candidate,wallMs:performance.now()-start,owners,closed,peakTransferredLeases:peak,retainedAtEnd:pool.active,copyBytes,exact:true};};
let roiHashes=[];
const crop=(b,v)=>{const out=new Uint8Array(2304);let pos=0;for(const [offset,w,h]of[[0,64,48],[3072,32,24],[3840,32,24]])for(let y=0;y<h;y++){out.set(b.subarray(offset+y*w+v*w/2,offset+y*w+(v+1)*w/2),pos);pos+=w/2}return out};
if(mode==='R323'||mode==='R118')for(let n=0;n<12;n++)roiHashes.push(await Promise.all([0,1].map(v=>hash(crop(new Uint8Array(input.raw.slice(n*4608,(n+1)*4608)),v)))));
const workerText=`const canonical=${canonical.toString()};const hash=${hash.toString()};const crop=${crop.toString()};const assert=${assert.toString()};let generation=1,live=0;onmessage=async({data:m})=>{if(m.cancel){generation=m.generation;postMessage({id:m.id,cancelAck:true});return;}const f=m.frame;live++;let reply={id:m.id,generation:m.generation};try{if(m.delay)await new Promise(r=>setTimeout(r,m.delay));reply.cancelled=m.generation!==generation;if(!reply.cancelled){reply.timestamp=f.timestamp;reply.hash=await hash(crop(await canonical(f),m.view));}}catch(e){reply.error=String(e)}finally{f.close();live--;reply.closed=true;reply.live=live;postMessage(reply)}};`;
async function makePool(){const url=URL.createObjectURL(new Blob([workerText],{type:'text/javascript'})),workers=[new Worker(url),new Worker(url)],pending=new Map();let id=0,active=0,peak=0;workers.forEach(w=>w.onmessage=e=>{const x=pending.get(e.data.id);if(x){pending.delete(e.data.id);clearTimeout(x.timer);x.resolve(e.data)}});const send=(view,msg,frame)=>new Promise((resolve,reject)=>{const seq=++id,timer=setTimeout(()=>reject(Error('worker deadline')),5000);pending.set(seq,{resolve,reject,timer});workers[view].postMessage({...msg,id:seq},frame?[frame]:[])});return {get active(){return active},get peak(){return peak},submit:async(view,frame,rect,generation,delay)=>{assert(active<2,'lease budget');active++;peak=Math.max(peak,active);try{return await send(view,{frame,view:rect,generation,delay},frame)}finally{active--}},cancel:async generation=>Promise.all([0,1].map(v=>send(v,{cancel:true,generation}))),stop:async()=>{assert(!active&&!pending.size,'cleanup wait');workers.forEach(w=>w.terminate());URL.revokeObjectURL(url)}};}
const controls={};if(mode==='R318'){const eligible=p=>p.length<=12&&p[0].key;controls.oversizedRejected=!eligible(input.gop.packets);controls.dependentRejected=!eligible(input.gop.packets.slice(1,12));assert(controls.oversizedRejected&&controls.dependentRejected,'cache bounds');}
if(mode==='R289'){let bad=false;try{const fs=await decode([{key:true,timestamp:0,data:[0,0,0,1,255,255]}]);bad=fs.length!==1;fs.forEach(f=>f.close())}catch{bad=true}assert(bad,'malformed failure');controls.malformedRejected=true;const fs=await decode(input.idr.packets.map((p,i)=>({...p,timestamp:i*1000})));const published=[];let generation=1;for(const f of fs){const i=f.timestamp/1000;assert(await hash(await canonical(f))===input.idr.hashes[i],'recovery oracle');if(i!==2)published.push(i);f.close()}controls.cancelledJobDiscarded=!published.includes(2)&&published.length===5;const acceptConfig=c=>JSON.stringify(c)===JSON.stringify(cfg);controls.incompatibleConfigRejected=!acceptConfig({...cfg,codec:'avc1.4D401F'});generation++;controls.oldSourceCommitRejected=1!==generation;controls.freshOwnerRecovered=true;assert(controls.cancelledJobDiscarded&&controls.incompatibleConfigRejected&&controls.oldSourceCommitRejected,'dispatch control');}
if(mode==='R323'||mode==='R118'){const pool=await makePool(),fs=await decode(input.gop.packets.slice(0,12));try{const pending=pool.submit(0,fs[0].clone(),0,1,30);await pool.cancel(2);const cancelled=await pending;assert(cancelled.cancelled&&cancelled.closed&&cancelled.live===0&&pool.active===0,'cancel must close before ack lease');const next=await pool.submit(0,fs[1].clone(),0,2,0);assert(next.hash===roiHashes[1][0]&&next.closed&&!next.cancelled,'source restart');controls.cancellationAcknowledgedAfterFrameClose=true;controls.staleCommitRejected=true;controls.newGenerationExact=true;controls.peakLeases=pool.peak;}finally{fs.forEach(f=>f.close());await pool.stop();}}
const correctness=[await trial(false),await trial(true)],pairs=[];for(let i=0;i<9;i++){const row={pair:i};for(const c of i%2?[true,false]:[false,true])row[c?'candidate':'baseline']=await trial(c);pairs.push(row)}return {controls,correctness,pairs};},{input,mode});result.passed=true;}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();await new Promise(r=>server.close(r));await writeFile(out+'/'+mode+'-results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({mode,passed:result.passed,error:result.error,pairs:result.data?.pairs?.map(p=>[p.baseline.wallMs,p.candidate.wallMs])}));}
