// SPDX-License-Identifier: Apache-2.0
import {requireWritableRun} from './run-guard.mjs';
import {chromium,firefox} from 'playwright';
import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import {createServer} from 'node:http';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {focusForQualification,observeForeground} from '../../../../scripts/qualification-foreground.mjs';
const base='research/items/unified-hybrid-software-engine',out=process.env.UNIFIED_RUN||(await readFile(base+'/active-run.txt','utf8')).trim(),old='research/items/granular-engine-loading/evidence/20260921T162900Z-screen-01',variant=process.env.VARIANT??'baseline',runtime=variant==='unified'?path.resolve(out,'runtime'):path.resolve(old,'snapshots/runtime'),family=process.env.BROWSER??'chrome',stage=process.env.STAGE??'correctness',network=process.env.NETWORK??'local';
await requireWritableRun(out);
const software=process.env.SOFTWARE??'software-baseline',policy=process.env.PREPARE??'none',fixture=process.env.FIXTURE??(stage==='correctness'?'h264':'user'),expected=process.env.EXPECT??(family==='firefox'&&fixture==='user'?'software':'hybrid');
let nextNetworkSlot=0,softwareChoice=software;
const runName=`${stage}-${family}-${variant}-${software}-${fixture}-${policy}-${network}-${Date.now()}`,dest=path.join(out,runName);await mkdir(dest,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const requests=[],errors=[];let active=0;
const server=createServer(async(req,res)=>{
 res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');res.setHeader('Cache-Control',process.env.CACHE==='warm'?'public,max-age=3600':'no-store');
 try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/profile/hevc'){softwareChoice='software-hevc';res.end('ok');return;}if(u.pathname==='/profile/full'){softwareChoice='software-baseline';res.end('ok');return;}if(u.pathname==='/profile/common'){softwareChoice='software-common-v2';res.end('ok');return;}if(process.env.FAULT==='software-unavailable'&&u.pathname==='/web/engine-software-full/player.wasm'){requests.push({url:u.pathname,file:'injected-unavailable',bytes:0,gzip:false,status:503,started:Date.now()});res.writeHead(503).end('Research software asset unavailable');return;}if(u.pathname==='/favicon.ico'){res.writeHead(204).end();return;}if(u.pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><style>body{margin:0;background:#111}#surface{width:320px}</style><div id="surface"></div><input id="file" type="file">');return;}
 let file=u.pathname.startsWith('/web/engine-unified/')?path.resolve(out,'variants/unified',path.basename(u.pathname)):u.pathname.startsWith('/web/engine-hybrid/')?path.resolve(out,'variants',variant,path.basename(u.pathname)):u.pathname.startsWith('/web/engine-software-full/')&&softwareChoice!=='original'?path.resolve(out,'variants',softwareChoice,path.basename(u.pathname)):path.resolve(runtime,'.'+u.pathname);
 if(!file.startsWith(runtime)&&!file.startsWith(path.resolve(out,'variants')))throw Error('Invalid path');
 const wasm=file.endsWith('.wasm'),gzip=network!=='local'&&wasm;
 let bytes=gzip&&u.pathname.startsWith('/web/engine-hybrid/')?await readFile(file+'.gz'):await readFile(file);
 if(gzip&&!u.pathname.startsWith('/web/engine-hybrid/')){const {gzipSync}=await import('node:zlib');bytes=gzipSync(bytes,{level:6,mtime:0});}
 const record={url:u.pathname,bytes:bytes.length,sentBytes:0,gzip,started:Date.now(),file};requests.push(record);
 res.setHeader('Content-Type',wasm?'application/wasm':file.endsWith('.mjs')||file.endsWith('.js')?'text/javascript':file.endsWith('.ttf')?'font/ttf':'application/octet-stream');res.setHeader('Content-Length',bytes.length);if(gzip)res.setHeader('Content-Encoding','gzip');
 if(gzip){active++;await sleep(80);for(let offset=0;offset<bytes.length&&!res.destroyed;offset+=32768){const chunk=bytes.subarray(offset,offset+32768);const due=Math.max(Date.now(),nextNetworkSlot);nextNetworkSlot=due+chunk.length*8/(network==='50mbps'?50000:network==='5mbps'?5000:10000);await sleep(Math.max(0,due-Date.now()));if(res.destroyed)break;res.write(chunk);record.sentBytes+=chunk.length;}active--;res.end();}else{res.end(bytes);record.sentBytes=bytes.length;}record.complete=record.sentBytes===bytes.length;record.finished=Date.now();
 }catch(error){errors.push(String(error));res.writeHead(404).end(String(error));}
});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const deadline=setTimeout(()=>{console.error('Study trial exceeded 90 seconds');void browser.close();},90000);
const prelaunchPids=new Set(execFileSync('ps',['-axo','pid='],{encoding:'utf8'}).trim().split(/\s+/).map(Number));
const browser=await(family==='firefox'?firefox:chromium).launch({headless:false,...(family==='chrome'?{channel:'chrome',args:['--autoplay-policy=no-user-gesture-required']}:{firefoxUserPrefs:{'media.autoplay.default':0}})});const result={startedAt:Date.now(),stage,family,variant,network,browser:browser.version(),requests,errors,software,policy,fixture,fault:process.env.FAULT??null,expected,passed:false};
try{
 const page=await browser.newPage({viewport:{width:640,height:480}});page.on('pageerror',e=>errors.push(String(e)));await page.addInitScript(()=>{window.compilePhases=[];const original=WebAssembly.compile;WebAssembly.compile=async function(bytes){const t=performance.now();try{return await original.call(WebAssembly,bytes);}finally{compilePhases.push({bytes:bytes.byteLength,ms:performance.now()-t});}};});await page.goto(origin);await page.bringToFront();if(family==='chrome')result.foregroundStart=await focusForQualification(page,browser);
 const cdp=family==='chrome'?await browser.newBrowserCDPSession():null;
 async function processSnapshot(){if(!cdp){const rows=execFileSync('ps',['-axo','pid=,rss=,comm='],{encoding:'utf8'}).trim().split('\n').map(line=>/^\s*(\d+)\s+(\d+)\s+(.*)$/.exec(line)).filter(Boolean).filter(m=>!prelaunchPids.has(Number(m[1]))&&/firefox|Nightly.app/.test(m[3]));return {cpuSeconds:null,rssKiB:rows.reduce((s,m)=>s+Number(m[2]),0),pids:rows.map(m=>Number(m[1]))};}const info=await cdp.send('SystemInfo.getProcessInfo');let rssKiB=null;try{rssKiB=execFileSync('ps',['-o','rss=','-p',info.processInfo.map(p=>p.id).join(',')],{encoding:'utf8'}).trim().split(/\s+/).map(Number).reduce((a,b)=>a+b,0);}catch{}return {cpuSeconds:info.processInfo.reduce((s,p)=>s+p.cpuTime,0),rssKiB,pids:info.processInfo.map(p=>p.id)};}
 async function focusFirefox(){
  const processes=await processSnapshot();
  for(const pid of processes.pids){
   const match=execFileSync('lsappinfo',['find',`pid=${pid}`],{encoding:'utf8'}).match(/ASN:0x[0-9a-f]+-0x[0-9a-f]+:/i);
   if(match){execFileSync('lsappinfo',['setfront',match[0]]);break;}
  }
  await page.bringToFront();await page.waitForTimeout(150);
 }
 if(family==='firefox')await focusFirefox();
 const file=fixture==='user'?'/Volumes/seed2/Projects/startup-repro/software_test_slow.mkv':fixture==='h264'?path.resolve(old,'fixtures-v2/h264-aac-ass.mkv'):path.resolve(out,'fixtures',fixture+(fixture.startsWith('rotation')?'.mp4':'.mkv'));
 result.fixturePath=file;await page.evaluate(async forced=>{const {Player}=await import('/web/generated/index.js');window.player=new Player(document.querySelector('#surface'),{width:320,height:180,assetBase:'/',...(forced?{mode:forced}:{})});window.events=[];for(const type of ['selectionchange','modechange','error'])player.addEventListener(type,e=>events.push({type,detail:e.detail,ms:performance.now()-(window.start??0)}));},process.env.FORCE??'');
 result.preparation=await page.evaluate(async ({policy,expected})=>{const start=performance.now();let report;if(policy==='immediate-all'||policy==='immediate-selective'){window.prepStarted=performance.now();window.prepTask=player.prepare(policy==='immediate-all'?'all':['inspector',expected]);}if(policy==='all')report=await player.prepare('all');else if(policy==='selective')report=await player.prepare(['inspector',expected]);return {ms:performance.now()-start,compilePhases:window.compilePhases,report};},{policy,expected}).catch(error=>{if(process.env.FAULT)return {error:String(error)};throw error;});if(process.env.FAULT)assert.ok(result.preparation.error||result.preparation.report?.assets.some(x=>x.status==='failed'||x.status==='aborted'),'Expected preparation asset failure was not observed');
 await page.locator('#file').setInputFiles(file);if(process.env.ADMISSION){result.admission=await page.evaluate(async hevc=>{const t=performance.now();const {probeSource}=await import('/web/source-probe.js');const probe=await probeSource({file:document.querySelector('#file').files[0]},new AbortController().signal);const videos=probe.tracks.filter(x=>x.type==='video');const common=videos.length>0&&videos.every(x=>(hevc?['hevc']:['h264','hevc','vp8','vp9','av1']).includes(x.codec));await fetch('/profile/'+(common?(hevc?'hevc':'common'):'full'));return {ms:performance.now()-t,common,hevc,tracks:probe.tracks};},process.env.ADMISSION==='hevc');}if(family==='firefox')await focusFirefox();result.before=await processSnapshot();if(family==='firefox'){const asn=execFileSync('lsappinfo',['front'],{encoding:'utf8'}).trim();const info=execFileSync('lsappinfo',['info','-only','pid',asn],{encoding:'utf8'});const pid=Number(/\"pid\"=(\d+)/.exec(info)?.[1]);result.foregroundStart={pid,matched:result.before.pids.includes(pid),...await page.evaluate(()=>({visible:document.visibilityState==='visible',focused:document.hasFocus()}))};assert.ok(result.foregroundStart.matched&&result.foregroundStart.visible&&result.foregroundStart.focused);}
 result.startup=await page.evaluate(async()=>{window.start=performance.now();await player.open(document.querySelector('#file').files[0]);const openMs=performance.now()-start;await player.play();return {openMs,playMs:performance.now()-start};});
 await page.waitForFunction(()=>Number(player.properties.get('time-pos'))>.2,null,{timeout:30000});
 result.startup.movementMs=await page.evaluate(()=>performance.now()-start);result.after=await processSnapshot();
 if(policy.startsWith('immediate'))result.preparationAfterPlayback=await page.evaluate(async()=>({ms:performance.now()-prepStarted,report:await prepTask,finishedMs:performance.now()-prepStarted}));
 result.state=await page.evaluate(()=>({mode:player.mode,diagnostics:player.diagnostics,audio:player.audioDiagnostics(),events}));
 assert.equal(result.state.mode,expected);if(expected==='software')assert.equal(result.state.diagnostics.backend.decoder,'software');if(result.state.mode==='hybrid')assert.equal(result.state.diagnostics.backend.decoder,'webcodecs');if(result.state.mode!=='native')assert.ok(result.state.audio.mediaFrames>0);
 if(stage==='correctness'||stage==='recovery'){
  const synthetic=fixture!=='user';
  await page.evaluate(()=>player.selectTrack('sub','1'));result.tone=await page.evaluate(()=>{const b=player.current.backend,a=new Float32Array(b.analyser.fftSize);b.analyser.getFloatTimeDomainData(a);let crossings=0;for(let i=1;i<a.length;i++)if(a[i-1]<=0&&a[i]>0)crossings++;return {frequency:crossings*b.audioContext.sampleRate/a.length,rms:Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length)};});
  if(synthetic){assert.ok(Math.abs(result.tone.frequency-1000)<80,JSON.stringify(result.tone));assert.ok(result.tone.rms>.01);}
  await page.evaluate(()=>player.pause());result.positions=[];
  for(const target of [1,3,1]){await page.evaluate(t=>player.seek(t),target);await page.waitForTimeout(150);const position=await page.evaluate(()=>player.diagnostics.backend.presentation?.position??player.properties.get('time-pos'));assert.ok(Math.abs(position-target)<.15);result.positions.push(position);await page.locator('canvas').screenshot({scale:'css',path:path.join(dest,`frame-${target}.png`)});}
  await page.evaluate(()=>player.seek(3));await page.evaluate(()=>player.subtitleVisible(false));await page.waitForTimeout(150);await page.locator('canvas').screenshot({scale:'css',path:path.join(dest,'frame-3-no-sub.png')});
  await page.evaluate(async()=>{await player.subtitleVisible(true);await player.play();});await page.waitForFunction(()=>Number(player.properties.get('time-pos'))>3.2);
  await page.evaluate(async()=>{await player.open(document.querySelector('#file').files[0]);await player.play();});await page.waitForFunction(()=>Number(player.properties.get('time-pos'))>.1);result.replacement=true;
  if(expected==='hybrid'&&!process.env.FORCE){
   const recoveryStarted=Date.now();await page.evaluate(()=>player.current.backend.dispatchEvent(new CustomEvent('error',{detail:'Injected runtime decoder failure'})));
   await page.waitForFunction(()=>player.mode==='software'&&Number(player.properties.get('time-pos'))>.2,null,{timeout:30000});result.fallback=await page.evaluate(()=>({mode:player.mode,attempts:player.diagnostics.selection.attempts,audio:player.audioDiagnostics()}));result.fallback.ms=Date.now()-recoveryStarted;assert.ok(result.fallback.audio.mediaFrames>0);
  }
 }
 if(stage==='policy'){result.repeat=await page.evaluate(async()=>{const t=performance.now();await player.open(document.querySelector('#file').files[0]);await player.play();return {openPlayMs:performance.now()-t};});await page.waitForFunction(()=>Number(player.properties.get('time-pos'))>.2);}
 if(stage==='software-recovery'){result.partialRecovery=await page.evaluate(async()=>{const target=Number(player.properties.get('time-pos'));const start=performance.now();player.current.backend.dispatchEvent(new CustomEvent('error',{detail:'Injected partial Software decoder failure'}));await fetch('/profile/full');await player.destroy();const {Player}=await import('/web/generated/index.js');window.player=new Player(document.querySelector('#surface'),{width:320,height:180,assetBase:'/',mode:'software'});await player.open(document.querySelector('#file').files[0]);await player.seek(target);await player.play();return {target,openSeekPlayMs:performance.now()-start};});await page.waitForFunction(target=>Number(player.properties.get('time-pos'))>target+.2,result.partialRecovery.target,{timeout:30000});result.partialRecovery.audio=await page.evaluate(()=>player.audioDiagnostics());assert.ok(result.partialRecovery.audio.mediaFrames>0);assert.ok(requests.some(x=>x.file.includes('/software-baseline/')),'Full Software was not fetched');}
 if(stage==='cache'){await page.evaluate(()=>player.destroy());const beforeRequests=requests.length;await page.reload();await page.evaluate(async()=>{const {Player}=await import('/web/generated/index.js');window.player=new Player(document.querySelector('#surface'),{width:320,height:180,assetBase:'/'});});await page.locator('#file').setInputFiles(file);result.warmReload=await page.evaluate(async()=>{window.warmStart=performance.now();await player.open(document.querySelector('#file').files[0]);await player.play();return {openPlayMs:performance.now()-warmStart};});await page.waitForFunction(()=>Number(player.properties.get('time-pos'))>.2);result.warmReload.progressMs=await page.evaluate(()=>performance.now()-warmStart);result.warmReload.additionalRequests=requests.slice(beforeRequests);assert.equal(await page.evaluate(()=>player.mode),expected);}
 if(family==='firefox'){const asn=execFileSync('lsappinfo',['front'],{encoding:'utf8'}).trim();const info=execFileSync('lsappinfo',['info','-only','pid',asn],{encoding:'utf8'});const pid=Number(/"pid"=(\d+)/.exec(info)?.[1]);result.foregroundEnd={pid,matched:result.after.pids.includes(pid),...await page.evaluate(()=>({visible:document.visibilityState==='visible',focused:document.hasFocus()}))};assert.ok(result.foregroundEnd.matched&&result.foregroundEnd.visible&&result.foregroundEnd.focused);}
 if(family==='chrome'){result.foregroundEnd=await observeForeground(page,browser);result.foregroundEnd.application=execFileSync('lsappinfo',['info','-only','name,pid',execFileSync('lsappinfo',['front'],{encoding:'utf8'}).trim()],{encoding:'utf8'});result.foregroundEnd.process=execFileSync('ps',['-o','pid=,ppid=,comm=','-p',String(result.foregroundEnd.foregroundPID)],{encoding:'utf8'});assert.ok(result.foregroundEnd.matched);}
 result.compilePhases=await page.evaluate(()=>window.compilePhases);if(variant==='unified'){const engineRequests=requests.filter(x=>/engine-unified.*player.wasm$/.test(x.url));assert.equal(engineRequests.length,1,'Unified engine must download exactly once');assert.equal(result.compilePhases.filter(x=>x.bytes>20000000).length,1,'Unified engine must compile exactly once');assert.ok(!requests.some(x=>/engine-(hybrid|software-full)\/player.wasm$/.test(x.url)));}await page.evaluate(()=>player.destroy());await page.waitForTimeout(250);result.remainingWorkers=page.workers().length;result.resourceTiming=await page.evaluate(()=>performance.getEntriesByType('resource').map(e=>({name:e.name,duration:e.duration,encodedBodySize:e.encodedBodySize,decodedBodySize:e.decodedBodySize})));assert.equal(result.remainingWorkers,0);assert.deepEqual(errors,[]);result.passed=true;
}catch(error){result.error=String(error.stack);process.exitCode=1;}finally{result.trialWallMs=Date.now()-result.startedAt;await browser.close();if(result.after?.pids){await sleep(200);result.survivingPids=result.after.pids.filter(pid=>{try{process.kill(pid,0);return true;}catch{return false;}});if(result.survivingPids.length){result.passed=false;result.error='Browser processes survived close: '+result.survivingPids;process.exitCode=1;}}await new Promise(r=>server.close(r));await writeFile(path.join(dest,'result.json'),JSON.stringify(result,null,2));clearTimeout(deadline);console.log(JSON.stringify({dest,passed:result.passed,error:result.error,startup:result.startup}));}
