// SPDX-License-Identifier: Apache-2.0
import {chromium,firefox} from 'playwright';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createServer} from 'node:http';
import path from 'node:path';
import assert from 'node:assert/strict';
const base='research/items/granular-engine-loading',out=(await readFile(base+'/full-run.txt','utf8')).trim(),root=path.resolve(out,'dynamic'),family=process.env.BROWSER??'chrome',kind=process.env.KIND??'dynamic';
const dest=path.join(root,`trial-${family}-${kind}-${process.env.FAULT??'valid'}-${Date.now()}`);await mkdir(dest);const requests=[];
const server=createServer(async(req,res)=>{res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy','require-corp');res.setHeader('Cache-Control','no-store');try{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Codec module research</title>');return;}const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep))throw Error('Invalid path');const bytes=await readFile(file);requests.push({file,bytes:bytes.length});res.setHeader('Content-Type',file.endsWith('.wasm')?'application/wasm':'text/javascript');res.end(bytes);}catch(e){res.writeHead(404).end(String(e));}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const worker=`import create from './${kind==='static'?'static':kind==='dynamic'?'host':kind==='lazy2'?'host-lazy2':'host-lazy1'}.mjs';
self.onmessage=async()=>{let m;try{const t=performance.now();m=await create({dynamicLibraries:[]});const ready=performance.now();const before=performance.getEntriesByType('resource').map(x=>x.name);let load=0;if(${kind!=='static'}){const bytes=new Uint8Array(await(await fetch('./codec.wasm')).arrayBuffer());if(${process.env.FAULT==='corrupt'})bytes.fill(0);m.FS.writeFile('/codec.wasm',bytes);const start=performance.now();if(m._load_codec()!==0)throw Error('dlopen failed');load=performance.now()-start;}
const loaded=performance.now();const bytes=new Uint8Array(await(await fetch('./fixture.h264')).arrayBuffer());const ptr=m._malloc(bytes.length);m.HEAPU8.set(bytes,ptr);const start=performance.now();const count=${kind!=='static'?'m._run_codec':'m._decode_fixture'}(ptr,bytes.length);const checksum=${kind!=='static'?'m._codec_checksum':'m._get_checksum'}()>>>0;const decodeMs=performance.now()-start;m._free(ptr);
let repeat;if(${kind!=='static'}){const close=m._unload_codec();const reload=m._load_codec();const p=m._malloc(bytes.length);m.HEAPU8.set(bytes,p);repeat={close,reload,count:m._run_codec(p,bytes.length),checksum:m._codec_checksum()>>>0};m._free(p);}
m.PThread.terminateAllThreads();postMessage({passed:true,count,checksum,repeat,hostReadyMs:ready-t,moduleReadyMs:loaded-t,dlopenMs:load,decodeMs,loadedBeforeCodec:before,heapBytes:m.HEAPU8.byteLength});}catch(e){m?.PThread?.terminateAllThreads();postMessage({passed:false,error:String(e.stack)});}};`;
await writeFile(path.join(root,`worker-${kind}.mjs`),worker);
let browser;const result={family,kind,requests,passed:false};try{browser=await(family==='chrome'?chromium:firefox).launch({headless:false,...(family==='chrome'?{channel:'chrome'}:{})});result.browser=browser.version();const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}`);await page.bringToFront();const expected=JSON.parse(await readFile(path.join(root,'oracle.json'),'utf8'));result.negativeControl=process.env.FAULT??null;Object.assign(result,await page.evaluate(({kind})=>new Promise((resolve,reject)=>{const w=new Worker('/worker-'+kind+'.mjs',{type:'module'});const timer=setTimeout(()=>{w.terminate();reject(Error('Module trial timeout'));},30000);w.onerror=e=>{clearTimeout(timer);w.terminate();reject(Error(e.message));};w.onmessage=e=>{clearTimeout(timer);w.terminate();resolve(e.data);};w.postMessage({});}),{kind}));if(process.env.FAULT==='corrupt'){assert.equal(result.passed,false,'Corrupt module unexpectedly accepted');assert.ok(/CompileError|magic|wasm|link|dlopen/i.test(result.error));result.expectedRejection=true;result.passed=true;}else{assert.ok(result.passed,result.error);assert.equal(result.count,expected.count);assert.equal(result.checksum,expected.checksum);if(kind!=='static'){assert.ok(!result.loadedBeforeCodec.some(x=>x.endsWith('/codec.wasm')),'Module was loaded eagerly');assert.equal(result.repeat.count,expected.count);assert.equal(result.repeat.checksum,expected.checksum);assert.equal(result.repeat.close,0);assert.equal(result.repeat.reload,0);}}await page.waitForTimeout(200);result.remainingWorkers=page.workers().length;assert.equal(result.remainingWorkers,0);}catch(e){result.passed=false;result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();await new Promise(r=>server.close(r));await writeFile(path.join(dest,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));}
