// SPDX-License-Identifier: Apache-2.0
import{chromium}from'playwright';import{readFile,writeFile,mkdir}from'node:fs/promises';import{createServer}from'node:http';import{execFileSync}from'node:child_process';
const out=process.argv[2],fixture=process.argv[3],diagnostic=false,extra=false;await mkdir(out,{recursive:true});let browser,result={diagnostic,scope:'Actual foreground Chrome native CALayer diagnostic; color identifies Chrome CALayer class, not macOS hardware-overlay promotion. ScreenCaptureKit only owned window; no photon claim.'};
const html=`<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:white;font:16px Arial}.stage{position:relative;width:640px;height:360px;background:white}.stage video,.stage canvas{position:absolute;left:0;top:0;width:640px;height:360px}.caption{position:absolute;left:160px;bottom:12px;width:320px;height:28px;background:#000;color:#fff;text-align:center;line-height:28px;z-index:2}.control{position:absolute;right:12px;top:52px;width:80px;height:28px;background:#222;color:#fff;text-align:center;line-height:28px;z-index:2}.stage.blend{mix-blend-mode:multiply}.stage.transformed{transform:scaleX(-1)}.stage.transformed>*{transform:scaleX(-1)}.stage.transformed .control{right:auto;left:12px}.stage:fullscreen{width:640px;height:360px;margin:auto;background:white}button{margin:8px}</style></head><body><div class="stage" id="stage"><video id="v" src="/source.mp4" muted playsinline preload="auto"></video><canvas id="c" width="640" height="360" style="display:none"></canvas><div class="caption" id="caption">Caption 0123 • same content</div><div class="control" id="control">Controls</div></div><button id="fullscreen">Fullscreen</button><script>fullscreen.onclick=()=>stage.requestFullscreen();</script></body></html>`;
const server=createServer(async(q,r)=>{if(q.url==='/source.mp4'){const b=await readFile(fixture+'/source.mp4');r.setHeader('Content-Type','video/mp4');r.setHeader('Accept-Ranges','bytes');if(q.headers.range){const m=q.headers.range.match(/bytes=(\d+)-(\d*)/),start=Number(m[1]),end=m[2]?Math.min(Number(m[2]),b.length-1):b.length-1;r.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${b.length}`,'Content-Length':end-start+1});r.end(b.subarray(start,end+1));}else{r.setHeader('Content-Length',b.length);r.end(b)}}else{r.setHeader('Content-Type','text/html');r.end(html)}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
try{browser=await chromium.launch({channel:'chrome',headless:false,args:['--autoplay-policy=no-user-gesture-required',...(diagnostic?['--show-mac-overlay-borders']:[])]});const page=await browser.newPage({viewport:{width:700,height:440}});await page.goto('http://127.0.0.1:'+server.address().port);const cdp=await browser.newBrowserCDPSession();result.version=await cdp.send('Browser.getVersion');const initial=(await cdp.send('SystemInfo.getProcessInfo')).processInfo,pid=initial.find(p=>p.type==='browser').id;result.foreground=JSON.parse(execFileSync('/tmp/demuxe-display-foreground',[String(pid)],{encoding:'utf8'}));result.foreground.windows=result.foreground.windows.filter(w=>w.pid===pid);await page.bringToFront();await page.evaluate(async()=>{if(v.readyState<2)await new Promise(r=>v.addEventListener('loadeddata',r,{once:true}));window.ctx=c.getContext('2d');window.mode='direct';window.tick=(now,m)=>{if(mode==='canvas')ctx.drawImage(v,0,0);v.requestVideoFrameCallback(tick)};v.requestVideoFrameCallback(tick);});
result.metrics=await page.evaluate(()=>({inner:[innerWidth,innerHeight],outer:[outerWidth,outerHeight],dpr:devicePixelRatio,screen:[screen.width,screen.height]}));
const setMode=async mode=>{await page.evaluate(mode=>{window.mode=mode;stage.className='stage'+(mode==='blend'?' blend':mode==='transformed'?' transformed':'');v.style.visibility=mode==='canvas'?'hidden':'visible';c.style.display=mode==='canvas'?'block':'none';caption.style.display=mode==='plain'?'none':'block';control.style.display=mode==='plain'?'none':'block';},mode);};
const samples=[];
for(const state of['caption-change','controls-hidden','scroll','resize']){
 if(state==='resize')await page.setViewportSize({width:660,height:400});
 for(const mode of['direct','blend']){
 await setMode(mode);await page.evaluate(async state=>{document.body.style.height='1000px';window.scrollTo(0,state==='scroll'?100:0);caption.textContent='Caption changed 48 • same';control.style.display=state==='controls-hidden'?'none':'block';v.currentTime=2;await new Promise(r=>v.addEventListener('seeked',r,{once:true}));},state);await page.waitForTimeout(150);
 const held=await page.evaluate(()=>({time:v.currentTime,rect:v.getBoundingClientRect().toJSON(),caption:caption.textContent,controls:control.style.display,scrollY,visible:document.visibilityState}));const capture=JSON.parse(execFileSync('/tmp/demuxe-overlay-capture',[String(pid),out+'/'+state+'-'+mode+'.png'],{encoding:'utf8'}));samples.push({state,mode,held,capture});}}
result.samples=samples;result.passed=true;}catch(e){result.error=String(e.stack);process.exitCode=1}finally{await browser?.close();await new Promise(r=>server.close(r));await writeFile(out+'/results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,error:result.error,samples:result.samples?.length}));}
