// SPDX-License-Identifier: Apache-2.0
import {readFile,writeFile} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';const out=process.argv[2],source=out+'/source.mp4',bytes=await readFile(source),sha=()=>createHash('sha256').update(bytes).digest('hex'),identity=sha();
const records=JSON.parse(execFileSync('ffprobe',['-v','error','-select_streams','v:0','-show_entries','packet=pts_time,pos,flags','-of','json',source],{maxBuffer:100000000})).packets;assert.equal(records.length,100000);assert.ok(records.every(p=>p.flags.includes('K')));const times=records.map(p=>Math.round(+p.pts_time*90000)),offsets=records.map(p=>+p.pos);await writeFile(out+'/oracle.json',JSON.stringify({sourceSHA256:identity,times,offsets}));await writeFile(out+'/plan.json',JSON.stringify({scope:'Real100000 all-intra MP4 packet seek entries, representation-only immutable source-bound map. Maintained native seeks remain delegated to FFmpeg; this does not establish a current production duplicate-map owner.',metric:'Logical retained index array bytes <=50% of two Float64Arrays. No speed claim;11 alternating cold construction plus100000predecessor-query batches descriptive. Source parse/read and independent oracle excluded equally; measure constructor peak buffer accounting separately.',controls:'Every query predecessor compared with independent plain-array binary search; all reconstructed entries exact, source identity and malformed varints reject, arithmetic beyond4GiB and90k ticks controlled.'},null,2));
const put=(a,n)=>{if(!Number.isSafeInteger(n)||n<0)throw Error('delta');do{const x=n%128;n=Math.floor(n/128);a.push(x+(n?128:0));}while(n);};function get(a,p){let n=0,m=1;for(let j=0;j<8;j++){if(p.i>=a.length)throw Error('truncated varint');const b=a[p.i++];n+=(b%128)*m;if(!Number.isSafeInteger(n))throw Error('overflow');if(b<128)return n;m*=128;}throw Error('long varint');}
function compact(ts,os){const ct=[],co=[],cp=[],stream=[];for(let i=0;i<ts.length;i++){if(i%32===0){ct.push(ts[i]);co.push(os[i]);cp.push(stream.length);}else{put(stream,ts[i]-ts[i-1]);put(stream,os[i]-os[i-1]);}}return {t:Float64Array.from(ct),o:Float64Array.from(co),p:Uint32Array.from(cp),d:Uint8Array.from(stream),count:ts.length,identity};}
const floor=(a,t)=>{let lo=0,hi=a.length;while(lo<hi){const m=Math.floor((lo+hi)/2);if(a[m]<=t)lo=m+1;else hi=m;}return lo-1;};function query(c,t,id=identity){if(id!==c.identity)throw Error('source identity');const k=floor(c.t,t);if(k<0)return null;let time=c.t[k],offset=c.o[k],n=k*32;const p={i:c.p[k]};while(n+1<Math.min((k+1)*32,c.count)){const dt=get(c.d,p),off=get(c.d,p);if(time+dt>t)break;time+=dt;offset+=off;n++;}return {n,time,offset};}
const c=compact(times,offsets);for(let i=0;i<times.length;i++)assert.deepEqual(query(c,times[i]),{n:i,time:times[i],offset:offsets[i]});assert.throws(()=>query(c,10,'changed'),/identity/);const damaged={...c,d:c.d.slice(0,-1)};assert.throws(()=>query(damaged,times.at(-1)),/truncated/);const wide=compact([0,90000,180000],[2**32+7,2**32+100,156000000000]);assert.equal(query(wide,180000).offset,156000000000);
let seed=75;const rnd=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);const targets=Array.from({length:100000},()=>Math.floor(rnd()*(times.at(-1)+3000))-1);for(const t of targets){const i=floor(times,t);assert.deepEqual(query(c,t),i<0?null:{n:i,time:times[i],offset:offsets[i]});}
const rows=[];for(let pair=0;pair<11;pair++){const row={pair};for(const mode of pair%2?['compact','baseline']:['baseline','compact']){const start=performance.now(),index=mode==='compact'?compact(times,offsets):{t:Float64Array.from(times),o:Float64Array.from(offsets)},built=performance.now();let sum=0;for(const t of targets){if(mode==='compact')sum+=query(index,t)?.offset??0;else{const i=floor(index.t,t);sum+=i<0?0:index.o[i];}}row[mode]={buildMs:built-start,queryMs:performance.now()-built,totalMs:performance.now()-start,checksum:sum};}assert.equal(row.baseline.checksum,row.compact.checksum);rows.push(row);}const logicalBytes=c.t.byteLength+c.o.byteLength+c.p.byteLength+c.d.byteLength,baseBytes=times.length*16;await writeFile(out+'/deltas.bin',c.d);const med=a=>a.toSorted((a,b)=>a-b)[5];await writeFile(out+'/result.json',JSON.stringify({sourceSHA256:identity,samples:times.length,allEntriesExact:true,all100000QueriesExact:true,controls:{staleRejected:true,truncatedRejected:true,wideArithmeticExact:true},baselineBytes:baseBytes,candidateBytes:logicalBytes,savingPct:100*(1-logicalBytes/baseBytes),storagePassed:logicalBytes<=baseBytes*.5,rows,medianColdCompleteSavingPct:med(rows.map(r=>100*(1-r.compact.totalMs/r.baseline.totalMs))),limitations:'Array payload retention only. Transient JS numeric arrays during authoring and source/oracle arrays are not retained index bytes. No physical RSS, energy or current production map replacement claim.'},null,2));console.log({logicalBytes,baseBytes});
