// SPDX-License-Identifier: Apache-2.0
// Bounded Ogg framing -> independent packet bytes -> actual pinned Wasm decoder.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import os from 'node:os';
const sha=b=>createHash('sha256').update(b).digest('hex'),home=await mkdtemp(path.join(os.tmpdir(),'demuxe-ogg-'));
const sources=['packages/provider-container/src/ogg.ts','packages/provider-container/src/matroska.ts','packages/provider-audio/src/packet-decoder.ts'],sourceHashes=Object.fromEntries(await Promise.all([...sources,'tests/provider-ogg.mjs'].map(async p=>[p,sha(await readFile(p))])));
execFileSync('node_modules/.bin/tsc',['--target','ES2022','--module','NodeNext','--moduleResolution','NodeNext','--lib','ES2022,DOM','--strict','--skipLibCheck','--outDir',home+'/compiled',...sources],{stdio:'inherit'});await writeFile(home+'/compiled/package.json','{"type":"module"}');
const {OggAudioReader,oggCRC}=await import(pathToFileURL(home+'/compiled/provider-container/src/ogg.js')),{PacketAudioDecoder}=await import(pathToFileURL(home+'/compiled/provider-audio/src/packet-decoder.js'));
const modules=new Map(),builds=[],results=[],blocked=[];let maxRead=0;
class MeteredBlob extends Blob{async arrayBuffer(){throw Error('Whole Ogg Blob read forbidden');}slice(start=0,end=this.size,type){maxRead=Math.max(maxRead,end-start);return super.slice(start,end,type);}}
const ffmpeg=args=>execFileSync('ffmpeg',['-v','error','-cpuflags','0','-y',...args],{maxBuffer:32*1024*1024});
const unhex=s=>Buffer.from((s??'').split('\n').filter(l=>l.includes(':')).map(l=>l.split(':')[1].split('  ')[0].replaceAll(' ','')).join(''),'hex');
function xiphHeaders(bytes){let p=1,lengths=[];assert.equal(bytes[0],2);for(let i=0;i<2;i++){let n=0,v;do{v=bytes[p++];n+=v;}while(v===255);lengths.push(n);}return [bytes.subarray(p,p+lengths[0]),bytes.subarray(p+lengths[0],p+lengths[0]+lengths[1]),bytes.subarray(p+lengths[0]+lengths[1])];}
async function decoderModule(profile){if(modules.has(profile))return modules.get(profile);const pointer=JSON.parse(await readFile((process.env.DECODER_BUILD_ROOT??'build/codec-expansion/decoder-families')+'/'+profile+'.json')),raw=await readFile(pointer.directory+'/build-record.json');assert.equal(sha(raw),pointer.recordSHA256);const record=JSON.parse(raw),wasm=await readFile(pointer.directory+'/module.wasm'),js=await readFile(pointer.directory+'/module.mjs');assert.equal(sha(wasm),record.artifacts['module.wasm'].sha256);assert.equal(sha(js),record.artifacts['module.mjs'].sha256);const factory=(await import(pathToFileURL(pointer.directory+'/module.mjs'))).default,module=await factory({wasmBinary:wasm});modules.set(profile,module);builds.push({profile,recordSHA256:pointer.recordSHA256,wasmSHA256:sha(wasm),moduleSHA256:sha(js)});return module;}
for(const codec of ['opus','vorbis','flac'])for(const rate of (codec==='opus'?[48000]:codec==='vorbis'?[44100,48000]:[44100,48000,96000]))for(const channels of [1,2])for(const bits of (codec==='flac'?[16,24,32]:[0]))test(`${codec} ${rate} ${channels} ${bits} packet/granule/native reference`,async t=>{
 const id=[codec,rate,channels,bits].join('-'),file=home+'/'+id+'.ogg',options=codec==='flac'?['-sample_fmt',bits===16?'s16':'s32','-bits_per_raw_sample',String(bits),'-strict','experimental']:['-strict','experimental'];
 try{ffmpeg(['-f','lavfi','-i',`aevalsrc=0.35*sin(2*PI*443*t)${channels===2?'|0.2*sin(2*PI*787*t)':''}:s=${rate}:d=2.137`,'-c:a',codec,...options,file]);}
 catch(error){if(codec==='vorbis'&&channels===1){blocked.push({id,status:'fixture-encoder-blocked',reason:String(error.stderr)});t.skip('Host experimental Vorbis encoder does not encode mono; decoder support is not inferred');return;}throw error;}
 const bytes=await readFile(file),reader=await OggAudioReader.open(new MeteredBlob([bytes]),new AbortController().signal),track=reader.tracks[0],probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_packets','-show_streams','-show_data','-of','json',file],{encoding:'utf8',maxBuffer:32*1024*1024}));
 assert.equal(track.codec,codec);assert.equal(track.rate,rate);assert.equal(track.channels,channels);assert.equal(track.bitDepth,bits);if(codec==='vorbis'){const actual=xiphHeaders(Buffer.from(track.privateData)),expected=xiphHeaders(unhex(probe.streams[0].extradata));assert.deepEqual(actual[0],expected[0],'Vorbis identification');assert.deepEqual(actual[2],expected[2],'Vorbis setup');/* Host demux strips user comments from codec extradata; retain original raw comments. */}else assert.deepEqual(Buffer.from(track.privateData),unhex(probe.streams[0].extradata),'Independent codec header bytes');
 const packets=[];for await(const p of reader.packets())packets.push(p);assert.equal(packets.length,probe.packets.length);assert.equal(reader.packetCount,packets.length);assert.equal(packets.at(-1).granuleEndSamples,reader.granuleEndSamples);assert.equal(packets.at(-1).endOfStream,true);
 for(let i=0;i<packets.length;i++)assert.deepEqual(Buffer.from(packets[i].data),unhex(probe.packets[i].data),'Independent packet bytes '+i);
 const decoder=new PacketAudioDecoder(await decoderModule(codec==='flac'?'lossless':'opus-vorbis'),codec,new AbortController().signal,{sampleRate:rate,channels,bitsPerSample:bits,extradata:track.privateData});let frames=[],cursor=0;
 try{for(const p of packets){const produced=decoder.decode(p.data,p.startSample??cursor);for(const f of produced){assert.equal(f.pts,cursor,'Decoded sample clock continuity');cursor+=f.samples;frames.push(f);}if(codec!=='vorbis'&&p.granuleEndSamples!==undefined&&!p.endOfStream)assert.equal(cursor,p.granuleEndSamples-reader.preSkip,'Nonterminal page granule clock');}frames.push(...decoder.flush());}finally{decoder.dispose();}
 assert.ok(cursor>=reader.sampleCount,'Final granule must not invent decoded samples');
 const raw=ffmpeg(['-i',file,'-map','0:a:0','-f','f32le','-']),reference=new Float32Array(raw.buffer,raw.byteOffset,raw.length/4).subarray(0,reader.sampleCount*channels),actual=Float32Array.from(frames.flatMap(f=>Array.from({length:f.samples*channels},(_,i)=>f.pcm?f.pcm[i]/2147483648:f.planes[i%channels][Math.floor(i/channels)]))).subarray(0,reader.sampleCount*channels);
 assert.equal(actual.length,reader.sampleCount*channels);assert.equal(reference.length,actual.length,'Independent reference granule extent');let error=0;for(let i=0;i<actual.length;i++)error=Math.max(error,Math.abs(actual[i]-reference[i]));assert.ok(error<2e-5,'Native reference PCM '+error);
 if(codec==='flac'){const integer=ffmpeg(['-i',file,'-map','0:a:0','-f','s32le','-']),decoded=Buffer.concat(frames.map(f=>Buffer.from(f.pcm.buffer,f.pcm.byteOffset,f.pcm.byteLength))).subarray(0,reader.sampleCount*channels*4);assert.deepEqual(decoded,integer.subarray(0,decoded.length));}
 const first=packets[0].data.slice();for await(const p of reader.packets())void p;assert.deepEqual(packets[0].data,first,'Owned packets after repeat');assert.ok(maxRead<=65536);
 results.push({id,codec,rate,channels,bits,packets:packets.length,inputSHA256:sha(bytes),extradataSHA256:sha(track.privateData),packetSHA256:sha(Buffer.concat(packets.map(p=>Buffer.from(p.data)))),referenceSHA256:sha(Buffer.from(reference.buffer,reference.byteOffset,reference.byteLength)),preSkip:reader.preSkip,endGranule:reader.granuleEndSamples,samples:reader.sampleCount,decodedSamples:cursor,discardedTail:cursor-reader.sampleCount,maxError:error,integerExact:codec==='flac',ownedPackets:true});
});
const page=(packets,sequence,flags,granule,serial=77)=>{const laces=[];for(const packet of packets){let length=packet.length;while(length>=255){laces.push(255);length-=255;}laces.push(length);}assert.ok(laces.length<=255);const h=Buffer.alloc(27);h.write('OggS');h[5]=flags;h.writeBigUInt64LE(BigInt(granule),6);h.writeUInt32LE(serial,14);h.writeUInt32LE(sequence,18);h[26]=laces.length;const bytes=Buffer.concat([h,Buffer.from(laces),...packets]);bytes.writeUInt32LE(oggCRC(bytes),22);return bytes;};
const pages=bytes=>{const rows=[];for(let offset=0;offset<bytes.length;){const count=bytes[offset+26],size=27+count+bytes.subarray(offset+27,offset+27+count).reduce((n,b)=>n+b,0);rows.push(Buffer.from(bytes.subarray(offset,offset+size)));offset+=size;}return rows;};
const checksum=p=>{p.writeUInt32LE(oggCRC(p),22);return p;};
test('reject bad headers, CRC, sequence, lacing, serial, missing EOS and chained streams',async()=>{
 const bytes=await readFile(home+'/opus-48000-2-0.ogg'),original=pages(bytes),mutations=[];
 const change=(index,edit)=>{const rows=original.map(p=>Buffer.from(p));edit(rows[index]);checksum(rows[index]);mutations.push(Buffer.concat(rows));};
 const crc=Buffer.from(bytes);crc[crc.length-1]^=1;mutations.push(crc);
 change(0,p=>p[4]=1);change(0,p=>p[27+p[26]+18]=1);change(0,p=>p.writeInt16LE(1,27+p[26]+16));change(0,p=>p[27+p[26]+8]=2);change(1,p=>p.writeUInt32LE(2,18));change(1,p=>p.writeUInt32LE(99,14));change(1,p=>p[5]|=1);change(1,p=>p[27+p[26]]^=1);change(original.length-1,p=>p[5]&=~4);change(original.length-1,p=>p.writeBigUInt64LE(99999999n,6));change(1,p=>p[27]=255);mutations.push(Buffer.concat([bytes,bytes]));mutations.push(bytes.subarray(0,bytes.length-1));
 for(const b of mutations)await assert.rejects(()=>OggAudioReader.open(new Blob([b]),new AbortController().signal),e=>e.code==='PROVIDER_PROFILE_MISMATCH');
 const vorbis=pages(await readFile(home+'/vorbis-48000-2-0.ogg'));const tags=Buffer.from(vorbis[1]),start=27+tags[26],id=tags.indexOf(Buffer.from('vorbis'),start);tags[id-1]=5;checksum(tags);await assert.rejects(()=>OggAudioReader.open(new Blob([vorbis[0],tags,...vorbis.slice(2)]),new AbortController().signal),/Vorbis header/);
 const vr=await OggAudioReader.open(new Blob([Buffer.concat(vorbis)]),new AbortController().signal),vh=xiphHeaders(Buffer.from(vr.tracks[0].privateData)),va=await vr.packets().next(),serial=vorbis[0].readUInt32LE(14);const missingSetup=Buffer.concat([vorbis[0],page([vh[1]],1,0,0,serial),page([va.value.data],2,4,1024,serial)]);await assert.rejects(()=>OggAudioReader.open(new Blob([missingSetup]),new AbortController().signal),/Vorbis header/);const impossible=vorbis.map(p=>Buffer.from(p));impossible.at(-1).writeBigUInt64LE(99999999n,6);checksum(impossible.at(-1));await assert.rejects(()=>OggAudioReader.open(new Blob([Buffer.concat(impossible)]),new AbortController().signal),/granule exceeds/);
 const canceled=new AbortController();canceled.abort();await assert.rejects(()=>OggAudioReader.open(new Blob([bytes]),canceled.signal),e=>e.name==='AbortError');const later=new AbortController(),reader=await OggAudioReader.open(new Blob([bytes]),later.signal);later.abort();await assert.rejects(async()=>{for await(const p of reader.packets())void p;},e=>e.name==='AbortError');const mid=new AbortController(),active=await OggAudioReader.open(new Blob([bytes]),mid.signal),iterator=active.packets();assert.equal((await iterator.next()).done,false);mid.abort();await assert.rejects(()=>iterator.next(),e=>e.name==='AbortError');results.push({id:'negative-controls',rejections:mutations.length+3,abort:true});
});
test('reassemble continued Opus comments across pages and reject broken continuation',async()=>{
 const original=pages(await readFile(home+'/opus-48000-2-0.ogg')),head=original[0],firstPayload=head.subarray(27+head[26]),vendor=Buffer.alloc(70000,65),tag=Buffer.alloc(16+vendor.length);tag.write('OpusTags');tag.writeUInt32LE(vendor.length,8);vendor.copy(tag,12);tag.writeUInt32LE(0,12+vendor.length);
 const split=65025,first=Buffer.alloc(27+255+split);first.write('OggS');first.writeBigUInt64LE(0xffffffffffffffffn,6);first.writeUInt32LE(head.readUInt32LE(14),14);first.writeUInt32LE(1,18);first[26]=255;first.fill(255,27,282);tag.copy(first,282,0,split);checksum(first);
 const second=page([tag.subarray(split)],2,1,0,head.readUInt32LE(14)),audio=original.slice(2).map((p,i)=>{p.writeUInt32LE(i+3,18);return checksum(p);}),bytes=Buffer.concat([head,first,second,...audio]);const reader=await OggAudioReader.open(new MeteredBlob([bytes]),new AbortController().signal);assert.equal(reader.tracks[0].privateData.length,firstPayload.length);assert.ok(reader.packetCount>0);second[5]=0;checksum(second);await assert.rejects(()=>OggAudioReader.open(new Blob([head,first,second,...audio]),new AbortController().signal),/continuation/);results.push({id:'continued-header',bytes:tag.length,owned:true});
});
test.after(async()=>{for(const [name,hash]of Object.entries(sourceHashes))assert.equal(sha(await readFile(name)),hash,'Source changed during Ogg matrix');const report={schema:1,passed:results.length===24,scope:'Single-stream Ogg packet/granule reader plus actual Wasm decoding; no seek, public route or playback qualification',sources:sourceHashes,ffmpegVersion:execFileSync('ffmpeg',['-version'],{encoding:'utf8'}).split('\n')[0],builds,maximumBlobRead:maxRead,results,blocked,home};await writeFile(home+'/report.json',JSON.stringify(report,null,2)+'\n');console.log('Ogg evidence: '+home+'/report.json');});
