// SPDX-License-Identifier: Apache-2.0
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import os from 'node:os';
import path from 'node:path';
const sha=b=>createHash('sha256').update(b).digest('hex'),home=await mkdtemp(path.join(os.tmpdir(),'demuxe-webm-copy-'));
const sourceNames=['packages/provider-container/src/webm.ts','packages/provider-container/src/webm-remux.ts','packages/provider-container/src/matroska.ts','tests/provider-webm.mjs'],sources=Object.fromEntries(await Promise.all(sourceNames.map(async p=>[p,sha(await readFile(p))])));
execFileSync('node_modules/.bin/tsc',['--target','ES2022','--module','NodeNext','--moduleResolution','NodeNext','--lib','ES2022,DOM','--strict','--skipLibCheck','--outDir',home+'/compiled',...sourceNames.filter(p=>p.endsWith('.ts'))]);await writeFile(home+'/compiled/package.json','{"type":"module"}');
const {remuxWebm}=await import(pathToFileURL(home+'/compiled/webm-remux.js')),{MatroskaReader}=await import(pathToFileURL(home+'/compiled/matroska.js')),{WebmPacketWriter}=await import(pathToFileURL(home+'/compiled/webm.js'));const results=[];
const ff=args=>execFileSync('ffmpeg',['-v','error','-cpuflags','0','-y',...args],{maxBuffer:32*1024*1024}),probe=p=>JSON.parse(execFileSync('ffprobe',['-v','error','-show_format','-show_streams','-show_packets','-show_data_hash','sha256','-of','json',p],{maxBuffer:8*1024*1024}));

// Independent structural inspection checks segment-relative index targets.
function elements(bytes,start,end){const rows=[];for(let offset=start;offset<end;){const at=offset;let iw=1;while(!(bytes[offset]&(1<<(8-iw))))iw++;let id=0;for(let i=0;i<iw;i++)id=id*256+bytes[offset++];let sw=1;while(!(bytes[offset]&(1<<(8-sw))))sw++;let n=bytes[offset++]&((1<<(8-sw))-1);for(let i=1;i<sw;i++)n=n*256+bytes[offset++];assert.ok(offset+n<=end);rows.push({id,start:offset,end:offset+n,at});offset+=n;}return rows;}
const num=(bytes,e)=>{let n=0;for(let i=e.start;i<e.end;i++)n=n*256+bytes[i];return n;};
function validateIndex(bytes,reader){const segment=elements(bytes,0,bytes.length).find(e=>e.id===0x18538067),top=elements(bytes,segment.start,segment.end),seek=top.find(e=>e.id===0x114d9b74),cues=top.find(e=>e.id===0x1c53bb6b);assert.ok(seek&&cues);for(const entry of elements(bytes,seek.start,seek.end)){const children=elements(bytes,entry.start,entry.end),id=num(bytes,children.find(e=>e.id===0x53ab)),position=num(bytes,children.find(e=>e.id===0x53ac));assert.equal(top.find(e=>e.id===id).at,segment.start+position);}
 const points=elements(bytes,cues.start,cues.end);assert.ok(points.length>=6);let last=-1;for(const point of points){const children=elements(bytes,point.start,point.end),time=num(bytes,children.find(e=>e.id===0xb3)),pos=children.find(e=>e.id===0xb7),fields=elements(bytes,pos.start,pos.end),track=num(bytes,fields.find(e=>e.id===0xf7)),clusterPosition=num(bytes,fields.find(e=>e.id===0xf1)),cluster=top.find(e=>e.at===segment.start+clusterPosition);assert.equal(cluster.id,0x1f43b675);assert.equal(track,reader.tracks.find(t=>t.kind==='video').number);const entries=elements(bytes,cluster.start,cluster.end);assert.equal(num(bytes,entries.find(e=>e.id===0xe7)),time);assert.ok(bytes[entries.find(e=>e.id===0xa3).start+3]&128);assert.ok(time>=last);last=time;}}

for(const video of ['vp8','vp9','av1'])for(const audio of ['opus','vorbis'])for(const channels of audio==='opus'?[1,2]:[2])test(video+'/'+audio+'/'+channels+' exact native packets, timing, video and audio',async()=>{
 const id=video+'-'+audio+'-'+channels,input=home+'/'+id+'.webm',output=home+'/'+id+'-copy.webm';
 const options={vp8:['-c:v','libvpx','-deadline','realtime','-cpu-used','8','-auto-alt-ref','0','-lag-in-frames','0'],vp9:['-c:v','libvpx-vp9','-deadline','realtime','-cpu-used','8','-auto-alt-ref','0','-lag-in-frames','0'],av1:['-c:v','libsvtav1','-preset','12','-svtav1-params','lp=1:enable-overlays=0:enable-tf=0:pred-struct=1']}[video];
 execFileSync('ffmpeg',['-v','error','-y','-f','lavfi','-i','testsrc2=size=128x96:rate=25','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','6.137','-ac',String(channels),...options,'-g','25','-c:a',audio==='opus'?'libopus':'vorbis',...(audio==='vorbis'?['-strict','experimental']:[]),input],{stdio:['ignore','ignore','pipe']});
 const source=await readFile(input),signal=new AbortController().signal,reader=await MatroskaReader.open(new Blob([source]),signal),prepared=await remuxWebm(new Blob([source]),signal);assert.equal(prepared.type,'video/webm');const bytes=Buffer.from(await prepared.arrayBuffer());await writeFile(output,bytes);const independent=probe(input),actual=probe(output);assert.equal(actual.format.duration,independent.format.duration,'Declared duration retained');assert.equal(reader.durationNs,Number(independent.format.duration)*1e9);
 validateIndex(bytes,reader);
 for(const typ of ['video','audio']){const a=independent.packets.filter(p=>p.codec_type===typ),b=actual.packets.filter(p=>p.codec_type===typ),identity=p=>({hash:p.data_hash,pts:p.pts,duration:p.duration,flags:p.flags,side:p.side_data_list});assert.deepEqual(b.map(identity),a.map(identity),typ+' packet/timeline/trim identity');}
 assert.deepEqual(actual.streams.map(s=>[s.codec_name,s.extradata_hash,s.sample_rate,s.channels,s.width,s.height,s.start_pts]),independent.streams.map(s=>[s.codec_name,s.extradata_hash,s.sample_rate,s.channels,s.width,s.height,s.start_pts]),'Exact codec configuration');
 const videoDecode=p=>ff(['-i',p,'-map','0:v:0','-pix_fmt','yuv420p','-f','rawvideo','-']),audioDecode=p=>ff(['-i',p,'-map','0:a:0','-f','f32le','-']);const rawVideo=videoDecode(input),rawAudio=audioDecode(input);assert.deepEqual(videoDecode(output),rawVideo);assert.deepEqual(audioDecode(output),rawAudio);
 for(const typ of ['video','audio']){const args=typ==='video'?['-map','0:v:0','-pix_fmt','yuv420p','-f','rawvideo']:['-map','0:a:0','-f','f32le'];const seek=p=>ff(['-ss','1.25','-i',p,'-t','0.2',...args,'-']);assert.deepEqual(seek(output),seek(input),'Native indexed seek '+typ);}
 const reread=await MatroskaReader.open(prepared,signal);assert.deepEqual(reread.tracks,reader.tracks);const originalPackets=[];for await(const p of reader.packets())originalPackets.push({...p,data:sha(p.data)});const copied=[];for await(const p of reread.packets())copied.push({...p,data:sha(p.data)});assert.deepEqual(copied,originalPackets);
 results.push({id,video,audio,channels,sampleRate:48000,inputSHA256:sha(source),outputSHA256:sha(bytes),outputBytes:bytes.length,packets:originalPackets.length,videoSHA256:sha(rawVideo),audioSHA256:sha(rawAudio),audioSamples:rawAudio.length/(4*channels),codecConfigExact:true,packetTimelineExact:true,decodedExact:true,durationSeconds:Number(actual.format.duration),nativeIndexedSeekExact:true,cueOffsetsChecked:true,tracks:reader.tracks.map(t=>({...t,privateData:sha(t.privateData)}))});
});
test('abort, malformed framing and writer bounds reject',async()=>{
 const input=await readFile(home+'/vp8-opus-2.webm'),signal=new AbortController();signal.abort();await assert.rejects(()=>remuxWebm(new Blob([input]),signal.signal),e=>e.name==='AbortError');const active=new AbortController(),file=new Blob([input]),original=file.slice.bind(file);let count=0;file.slice=(...args)=>{if(++count===3)active.abort();return original(...args);};await assert.rejects(()=>remuxWebm(file,active.signal),e=>e.name==='AbortError');
 class HugeBlob extends Blob{get size(){return 65*1024*1024;}}await assert.rejects(()=>remuxWebm(new HugeBlob(),new AbortController().signal),/byte budget/);await assert.rejects(()=>remuxWebm(new Blob([input.subarray(0,input.length-1)]),new AbortController().signal));
 for(const invalid of [0,NaN,Infinity,-1]){const corrupt=Buffer.from(input),at=corrupt.indexOf(Buffer.from([0x44,0x89,0x88]));assert.ok(at>0);corrupt.writeDoubleBE(invalid,at+3);await assert.rejects(()=>remuxWebm(new Blob([corrupt]),new AbortController().signal),e=>e.code==='PROVIDER_PROFILE_MISMATCH');}
 for(const offset of [16,18]){const corrupt=Buffer.from(input),head=corrupt.indexOf(Buffer.from('OpusHead'));assert.ok(head>0);corrupt[head+offset]=1;await assert.rejects(()=>remuxWebm(new Blob([corrupt]),new AbortController().signal),e=>e.code==='PROVIDER_PROFILE_MISMATCH');}
 const reader=await MatroskaReader.open(new Blob([input]),new AbortController().signal),writer=new WebmPacketWriter(reader.tracks,reader.timecodeScale),packet=(await reader.packets().next()).value;
 for(const change of [{timestampNs:-1},{timestampNs:1},{track:99},{data:new Uint8Array()},{data:new Uint8Array(1048577)},{durationNs:1},{discardPaddingNs:-1}])assert.throws(()=>writer.packet({...packet,...change}),e=>e.code==='PROVIDER_PROFILE_MISMATCH');assert.throws(()=>new WebmPacketWriter(reader.tracks,0));assert.throws(()=>writer.finish(Array(97).fill(new Uint8Array(1048576))),/output budget/);const counted=new WebmPacketWriter(reader.tracks,reader.timecodeScale);for(let i=0;i<18000;i++)counted.packet({...packet,data:Uint8Array.of(0)});assert.throws(()=>counted.packet({...packet,data:Uint8Array.of(0)}),/packet bounds/);
 results.push({id:'negative-controls',abortBeforeRead:true,abortDuringRead:true,inputBudget:true,truncated:true,writerControls:10,malformedCodecControls:2,invalidDurationControls:4});
});
test.after(async()=>{for(const [p,h]of Object.entries(sources))assert.equal(sha(await readFile(p)),h,'Source changed');const report={schema:1,passed:results.length===10,scope:'Bounded WebM packet copy native reference only; no browser or registry qualification',sources,nodeVersion:process.version,execArgv:process.execArgv,ffmpegVersion:execFileSync('ffmpeg',['-version'],{encoding:'utf8'}).split('\n')[0],home,results};await writeFile(home+'/report.json',JSON.stringify(report,null,2)+'\n');console.log('WebM evidence: '+home+'/report.json');});
