// Qualify public entrypoints and current component behavior against one immutable archive.
import {execFileSync,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,readdirSync,statSync} from 'node:fs';
import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const sha=b=>createHash('sha256').update(b).digest('hex');
const archive=path.resolve(process.env.BETA_ARCHIVE),root=mkdtempSync(path.resolve('build/release-extra-'));
const out=path.resolve('results/release-extra/'+new Date().toISOString().replaceAll(':','-'));mkdirSync(out,{recursive:true});console.log(out);
writeFileSync(path.join(root,'package.json'),'{"private":true,"type":"module"}\n');
const env={...process.env,npm_config_cache:path.join(root,'npm-cache')};delete env.ONLY;delete env.CASES;
execFileSync('npm',['install','--offline','--ignore-scripts','--no-audit','--no-fund',archive],{cwd:root,env});
const pkgRoot=path.join(root,'node_modules/deplexr'),metadata=JSON.parse(readFileSync(path.join(pkgRoot,'package.json'))),manifest=JSON.parse(readFileSync(path.join(pkgRoot,'release-manifest.json')));
assert.equal(metadata.name,'deplexr');assert.equal(metadata.version,'0.3.0-beta.3');assert.ok(!metadata.private);assert.deepEqual(metadata.bin,{deplexr:'./bin/deplexr.mjs'});assert.deepEqual(manifest.publicModes,['native','hybrid','software']);
for(const key of ['description','license','type','main','types','exports','repository','bugs','homepage','keywords'])assert.ok(metadata[key],key);
for(const [name,entry]of Object.entries(manifest.files)){const bytes=readFileSync(path.join(pkgRoot,name));assert.equal(sha(bytes),entry.sha256,name);assert.equal(bytes.length,entry.bytes,name);assert.ok(!/(^|\/)(results|node_modules|tests|build|src|\.git)(\/|$)/.test(name),name);assert.ok(!/webmpv/i.test(name),name);}
execFileSync('npm',['exec','--offline','--','deplexr','copy-assets','public/assets/deplexr'],{cwd:root,env,stdio:'pipe'});
const runtime=JSON.parse(readFileSync(path.join(root,'public/assets/deplexr/deplexr-runtime.json')));assert.ok(runtime.files['web/engine-hybrid/player.wasm']);
execFileSync(process.execPath,['--input-type=module','-e',`import {Player,PLAYBACK_MODES} from 'deplexr';import {definePlayerElement} from 'deplexr/player';import {createRequire} from 'node:module';const pkg=createRequire(import.meta.url)('deplexr/package.json');if(pkg.name!=='deplexr'||typeof Player!=='function'||typeof definePlayerElement!=='function'||typeof HTMLElement!=='undefined'||PLAYBACK_MODES.join(',')!=='native,hybrid,software')throw Error('exports/SSR');`],{cwd:root,env});
const pack=JSON.parse(execFileSync('npm',['pack','--dry-run','--json','--ignore-scripts'],{cwd:pkgRoot,env,encoding:'utf8'}))[0];writeFileSync(path.join(out,'npm-pack.json'),JSON.stringify(pack,null,2)+'\n');
const harnesses=['tests/release-extra.mjs','tests/beta-consumer.mjs','tests/beta-streaming.mjs','tests/public-api-consumer.mjs','tests/public-api.mjs','tests/player-component.mjs','tests/player-menu-review.mjs','tests/copy-assets.mjs','scripts/serve.mjs'];
const record={archiveSHA256:sha(readFileSync(archive)),sourceCommit:manifest.sourceCommit,harnesses:Object.fromEntries(harnesses.map(n=>[n,sha(readFileSync(n))])),metadata,pack:{bytes:statSync(archive).size,unpackedSize:pack.unpackedSize,fileCount:pack.entryCount},checks:[],passed:false};
const jobs=[['cli','node',['--test','tests/copy-assets.mjs'],{}],...['chrome','firefox'].flatMap(f=>[['consumer-'+f,'node',['tests/public-api-consumer.mjs'],{BROWSER:f}],['public-api-'+f,'node',['tests/public-api.mjs'],{BROWSER:f}],['component-'+f,'node',['tests/player-component.mjs'],{BROWSER:f}]]),['menu-review','node',['tests/player-menu-review.mjs'],{}]];
try{for(const [name,command,args,extra]of jobs){console.log('RUN',name);const run=spawnSync(command,args,{env:{...env,...extra,BETA_ARCHIVE:archive,DEPLEXR_RUNTIME_ROOT:pkgRoot},encoding:'utf8',maxBuffer:30*1024*1024});writeFileSync(path.join(out,name+'.log'),(run.stdout||'')+(run.stderr||''));record.checks.push({name,passed:run.status===0,log:name+'.log',sha256:sha(readFileSync(path.join(out,name+'.log')))});writeFileSync(path.join(out,'result.json'),JSON.stringify(record,null,2));if(run.status!==0)throw Error(name+' failed: '+run.stdout+'\n'+run.stderr);console.log('PASS',name);}record.passed=true;}finally{writeFileSync(path.join(out,'result.json'),JSON.stringify(record,null,2)+'\n');}
