// SPDX-License-Identifier: Apache-2.0
import {DemuxeRuntime,Player} from '/web/generated/index.js';
import {ProviderRuntime} from '/web/generated/internal/provider-runtime.js';
export async function runRuntimeAdversarial(){
 await fetch('/runtime-test/reset',{method:'POST'});
 const configuration=await(await fetch('/runtime-test/config')).json(),cases=[],errors=[];
 const assert=(ok,message)=>{if(!ok)throw Error(message);};
 const delay=ms=>new Promise(r=>setTimeout(r,ms));
 const reject=async(p,code)=>{try{await p;}catch(e){if(code)assert(e.code===code||e.name===code,`Expected ${code}, got ${e.code??e.name}: ${e.message}`);return;}throw Error('Expected rejection');};
 const resources=[];
 const runtime=(options={})=>{const r=new DemuxeRuntime({assetBase:location.origin+'/',qualifiedProviders:configuration.qualified,...options});resources.push(r);return r;};
 const session=r=>{const p=new ProviderRuntime(new URL(r.assetBase),r.qualifiedProviders,undefined,r);resources.push(p);return p;};
 const run=async(name,fn)=>{const start=performance.now();try{await fn();cases.push({name,passed:true,milliseconds:performance.now()-start});}catch(e){cases.push({name,passed:false,error:String(e.stack??e)});}finally{for(const r of resources.splice(0).reverse())await r.destroy();}};
 const counts=async()=>await(await fetch('/runtime-test/requests')).json();
 const onError=e=>errors.push(String(e.reason??e.message));window.addEventListener('unhandledrejection',onError);
 try{
  await run('20 concurrent manifest consumers make one HTTP request',async()=>{const r=runtime(),before=await counts();await Promise.all(Array.from({length:20},()=>r.providers.load('/runtime-test/native.json')));assert((await counts())['/runtime-test/native.json']-(before['/runtime-test/native.json']??0)===1,'Duplicate fetch');assert(r.snapshot.revision===1,'Duplicate publication');});
  await run('Parallel catalogs merge atomically',async()=>{const r=runtime();await Promise.all(['native','extra','second'].map(n=>r.providers.load('/runtime-test/'+n+'.json')));assert(r.snapshot.providers.length===3&&r.snapshot.revision===3,'Lost catalog addition');});
  for(const [name,code] of [['unqualified','DEPLOYMENT_UNAVAILABLE'],['bad-contract','ASSET_LOAD_FAILED'],['malformed','ASSET_LOAD_FAILED'],['oversized','ASSET_LOAD_FAILED']])await run('Reject '+name+' manifest without publication',async()=>{const r=runtime();await reject(r.providers.load('/runtime-test/'+name+'.json'),code);assert(r.snapshot.revision===0,'Invalid publication');});
  await run('Conflicting asset size preserves accepted catalog',async()=>{const r=runtime();await r.providers.load('/runtime-test/extra.json');await reject(r.providers.load('/runtime-test/conflict.json'),'ASSET_LOAD_FAILED');assert(r.snapshot.revision===1,'Conflict partially published');await r.providers.preload();});
  await run('HTTP failure can be retried',async()=>{const r=runtime();await reject(r.providers.load('/runtime-test/retry.json'),'ASSET_LOAD_FAILED');await r.providers.load('/runtime-test/retry.json');assert(r.snapshot.revision===1,'Retry did not publish');});
  await run('Caller abort leaves another delayed HTTP consumer alive',async()=>{const r=runtime(),a=new AbortController();const first=reject(r.providers.load('/runtime-test/slow.json',{signal:a.signal}),'AbortError'),second=r.providers.load('/runtime-test/slow.json');await delay(30);a.abort();await first;await second;assert(r.snapshot.revision===1,'Other consumer lost');});
  await run('Runtime destruction cancels delayed manifest and prohibits resurrection',async()=>{const r=runtime();const pending=reject(r.providers.load('/runtime-test/slow.json'),'ABORTED');await delay(30);await r.destroy();await pending;assert(r.snapshot.revision===0,'Late catalog published');await reject(r.providers.load('/runtime-test/native.json'),'ABORTED');});
  await run('Cached manifest completion cannot outlive runtime',async()=>{const r=runtime();await r.providers.load('/runtime-test/native.json');const pending=reject(r.providers.load('/runtime-test/native.json'),'ABORTED');await r.destroy();await pending;});
  await run('Shared compiled module identity and transferable byte copies',async()=>{const r=runtime();await r.providers.load('/runtime-test/extra.json');const a=session(r),b=session(r),path='runtime-test/cache.wasm';const [one,two]=await Promise.all([a.module(path),b.module(path)]);assert(one===two,'Compiled separately');const bytes=await a.bytes(path);structuredClone(bytes,{transfer:[bytes]});assert(bytes.byteLength===0&&(await b.bytes(path)).byteLength===8,'Cache bytes detached');await a.destroy();assert(await b.module(path)===two,'Player disposal invalidated shared cache');});
  await run('Failed digest is discarded and HTTP retry succeeds',async()=>{const r=runtime();await r.providers.load('/runtime-test/flaky.json');await reject(r.providers.preload(),'ASSET_LOAD_FAILED');assert(r.cacheStats.entries===0,'Failed bytes retained');await r.providers.preload();assert(r.cacheStats.reservedBytes===8,'Retry failed');});
  await run('Bounded LRU eviction and clear retain provider registration',async()=>{const r=runtime({maxCacheBytes:8});await Promise.all(['extra','second'].map(n=>r.providers.load('/runtime-test/'+n+'.json')));for(let i=0;i<10;i++){await r.providers.preload([i%2?'cache-second':'cache-test']);assert(r.cacheStats.reservedBytes===8&&r.cacheStats.entries===1,'Cache budget violated');}r.clearCache();assert(r.cacheStats.entries===0&&r.snapshot.providers.length===2,'Clear lost registrations');await r.providers.preload(['cache-test']);});
  await run('Pending assets survive clear and deny over-budget concurrency',async()=>{const r=runtime({maxCacheBytes:8});await Promise.all(['extra','slow'].map(n=>r.providers.load('/runtime-test/'+n+'.json')));const pending=r.providers.preload(['cache-slow']);await delay(40);r.clearCache();assert(r.cacheStats.reservedBytes===8,'Clear evicted pending acquisition');await reject(r.providers.preload(['cache-test']),'ASSET_LOAD_FAILED');await pending;await r.providers.preload(['cache-test']);});
  await run('Aborting a preload consumer preserves shared acquisition',async()=>{const r=runtime();await r.providers.load('/runtime-test/slow.json');const c=new AbortController(),cancelled=reject(r.providers.preload(undefined,{signal:c.signal}),'AbortError'),second=r.providers.preload();await delay(40);c.abort();await cancelled;await second;assert(r.cacheStats.reservedBytes===8,'Shared asset cancelled');});
  await run('Runtime retirement clears pending cache without late restoration',async()=>{const r=runtime();await r.providers.load('/runtime-test/slow.json');const pending=reject(r.providers.preload(),'ABORTED');await delay(40);await r.destroy();await pending;await delay(350);assert(r.cacheStats.entries===0,'Late cache restoration');});
  await run('Origin and fragment restrictions reject before HTTP',async()=>{const r=runtime();await reject(r.providers.load('https://example.invalid/providers.json'),'INVALID_ARGUMENT');await reject(r.providers.load('/runtime-test/native.json#fragment'),'INVALID_ARGUMENT');});
  await run('Listener failures cannot roll back publication',async()=>{const r=runtime();let seen=0;r.subscribe(()=>{throw Error('Injected listener failure');});const stop=r.subscribe(()=>seen++);await r.providers.load('/runtime-test/native.json');stop();await r.providers.load('/runtime-test/extra.json');assert(seen===1&&r.snapshot.revision===2,'Listener ownership corrupted');});
  const r=runtime(),hosts=[],players=[];
  try{
   await r.providers.load('/runtime-test/native.json');
   for(let i=0;i<3;i++){const host=document.createElement('div');host.style.cssText='display:inline-block;width:240px;height:135px';document.body.append(host);hosts.push(host);const p=new Player(host,{runtime:r,preview:false,watchdogs:false,remuxRuntime:'off',startupEscalation:false});players.push(p);await p.setMuted(true);await p.openRemote({url:location.origin+'/fixtures/example.mp4'},{mode:'native'});}
   const check=async(name,fn)=>{try{await fn();cases.push({name,passed:true});}catch(e){cases.push({name,passed:false,error:String(e.stack??e)});}};
   await check('Three real players advance during provider publication',async()=>{await Promise.all(players.map(p=>p.play()));const before=players.map(p=>p.state.currentTime);await r.providers.load('/runtime-test/extra.json',{preload:true});await delay(800);assert(players.every((p,i)=>p.state.currentTime>before[i]&&p.diagnostics.plan.id==='native-direct'),'Playback stopped or changed route');});
   await check('Provider publication during seek and pause preserves user intent',async()=>{await Promise.all([players[0].pause(),players[1].seek(2),r.providers.load('/runtime-test/second.json')]);await delay(350);assert(players[0].state.playbackIntent==='pause'&&players[0].state.status==='paused'&&players[1].state.currentTime>=1.8,'Pause or seek overwritten');});
   await check('Repeated transport and settings changes leave peer playback intact',async()=>{for(let i=0;i<5;i++){await players[0].seek(i%3);await players[0].play();await delay(60);await players[0].pause();await players[0].setPlaybackRate(i%2?1.5:1);await players[0].setVolume(i/10);}const t=players[2].state.currentTime;await delay(350);assert(players[2].state.currentTime>t,'Peer stalled');});
   await check('Source replacement rejects old metadata and preserves runtime',async()=>{const p=players[0],old=p.state.sourceId;await p.openRemote({url:location.origin+'/fixtures/example.mp4'});let error;try{p.presentation.setMediaSessionMetadata({title:'retired'},old);}catch(e){error=e.code;}assert(error==='ABORTED'&&r.snapshot.revision===3,'Stale metadata or runtime reset');});
   await check('Destroying a player while peers play preserves cached modules',async()=>{const p=players[2],t=p.state.currentTime;await players[0].destroy();await r.providers.preload(['cache-test']);await delay(350);assert(p.state.currentTime>t,'Peer stopped after destroy');});
   await check('Runtime disposal does not stop already admitted native playback',async()=>{const p=players[2],t=p.state.currentTime;await r.destroy();await delay(350);assert(p.state.currentTime>t,'Existing native playback stopped');});
  }finally{await Promise.all(players.map(p=>p.destroy()));hosts.forEach(h=>h.remove());for(const owner of resources.splice(0).reverse())await owner.destroy();}
 }finally{window.removeEventListener('unhandledrejection',onError);for(const r of resources.splice(0).reverse())await r.destroy();}
 return {passed:cases.every(c=>c.passed)&&errors.length===0,cases,errors,ua:navigator.userAgent};
}
