// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';import {readFile,writeFile,mkdir} from 'node:fs/promises';import{pathToFileURL}from'node:url';import path from'node:path';import{createHash}from'node:crypto';
const adapterPath=process.env.SHORTEN_ADAPTER_MODULE??'build/component-candidates/provider-audio/src/packet-decoder.js';const {PacketAudioDecoder}=await import(pathToFileURL(path.resolve(adapterPath)));
const root=process.env.SHORTEN_AUDIO_FIXTURE_ROOT??'/tmp/demuxe-shorten-fixtures',sha=b=>createHash('sha256').update(b).digest('hex');const unhex=text=>Uint8Array.from(Buffer.from(text.split('\n').filter(l=>l.includes(':')).map(l=>l.split(':')[1].split('  ')[0].replaceAll(' ','')).join(''),'hex'));
const pointer=JSON.parse(await readFile(process.env.SHORTEN_BUILD_POINTER??'/tmp/demuxe-shorten-builds/archive-historical.json')),raw=await readFile(pointer.directory+'/build-record.json');assert.equal(sha(raw),pointer.recordSHA256);const record=JSON.parse(raw),wasm=await readFile(pointer.directory+'/module.wasm'),js=await readFile(pointer.directory+'/module.mjs');assert.equal(sha(wasm),record.artifacts['module.wasm'].sha256);assert.equal(sha(js),record.artifacts['module.mjs'].sha256);const module=await(await import(pathToFileURL(pointer.directory+'/module.mjs'))).default({wasmBinary:wasm});
const f=JSON.parse(await readFile(root+'/fixtures.json'))[0],source=await readFile(f.input);assert.equal(sha(source),f.inputSHA256);const packetRaw=await readFile(root+'/'+f.id+'.json'),frameRaw=await readFile(root+'/'+f.id+'.frames.json');assert.equal(sha(packetRaw),f.packetSHA256);assert.equal(sha(frameRaw),f.framesSHA256);const packets=JSON.parse(packetRaw).packets,host=JSON.parse(frameRaw).frames;assert.ok(packets.every(p=>p.pts_time===undefined)&&host.every(f=>f.pts_time===undefined),'native source timestamps are missing');const bytes=packets.map(p=>unhex(p.data)),config={sampleRate:44100,channels:2,bitsPerSample:16,extradata:new Uint8Array()},signal=new AbortController(),decoder=new PacketAudioDecoder(module,'shorten',signal.signal,config);let maxFramesPerCall=0,maxScalarSamplesPerCall=0;
const fullDecode=()=>{const frames=[];for(const packet of bytes){const part=decoder.decode(packet,0);maxFramesPerCall=Math.max(maxFramesPerCall,part.length);maxScalarSamplesPerCall=Math.max(maxScalarSamplesPerCall,part.reduce((n,f)=>n+f.samples*f.channels,0));frames.push(...part);}const tail=decoder.flush();maxFramesPerCall=Math.max(maxFramesPerCall,tail.length);maxScalarSamplesPerCall=Math.max(maxScalarSamplesPerCall,tail.reduce((n,f)=>n+f.samples*f.channels,0));frames.push(...tail);assert.deepEqual(decoder.flush(),[]);return frames;};
let frames,seeks=[];try{frames=fullDecode();assert.equal(frames.length,host.length);let clock=0;for(let i=0;i<frames.length;i++){const frame=frames[i];assert.equal(frame.pts,clock);assert.equal(frame.duration,frame.samples);assert.equal(frame.samples,host[i].nb_samples);assert.equal(frame.timestampOrigin,'stream-clock');assert.equal(frame.rate,44100);assert.equal(frame.channels,2);assert.equal(frame.layout,3);clock+=frame.samples;}const reference=await readFile(root+'/'+f.id+'.s32');assert.equal(sha(reference),f.referenceSHA256);assert.deepEqual(Buffer.concat(frames.map(f=>Buffer.from(f.pcm.buffer))),reference);assert.equal(clock,f.referenceSamples);
 decoder.reset();assert.deepEqual(fullDecode().map(({generation,...f})=>f),frames.map(({generation,...f})=>f),'full predictor reset + owned PCM');
 for(const seconds of [48.25,16.75,58.5,4.75]){decoder.reset();const restarted=fullDecode(),target=Math.round(seconds*44100);let compared=0;for(const frame of restarted){const from=Math.max(target,frame.pts),to=Math.min(target+17640,frame.pts+frame.samples);if(to<=from)continue;assert.deepEqual(Buffer.from(frame.pcm.subarray((from-frame.pts)*2,(to-frame.pts)*2).buffer,frame.pcm.byteOffset+(from-frame.pts)*8,(to-from)*8),reference.subarray(from*8,to*8));compared+=to-from;}assert.equal(compared,17640);seeks.push({seconds,firstInputPacket:0,discardToSample:target,comparedSamples:compared,integerExact:true,contract:'restart-from-start-and-discard'});}
}finally{decoder.dispose();decoder.dispose();}
for(const changed of [{sampleRate:48000},{channels:1},{bitsPerSample:24},{extradata:new Uint8Array([1])}])assert.throws(()=>new PacketAudioDecoder(module,'shorten',new AbortController().signal,{...config,...changed}),e=>e.code==='PROVIDER_PROFILE_MISMATCH');
for(const mode of ['missingHeader','version','packetPTS','packetBudget']){const d=new PacketAudioDecoder(module,'shorten',new AbortController().signal,config),packet=bytes[0].slice();try{if(mode==='missingHeader')packet[0]=0;if(mode==='version')packet[4]=1;assert.throws(()=>d.decode(mode==='packetBudget'?new Uint8Array(1025):packet,mode==='packetPTS'?256:0));}finally{d.dispose();}}
// Independent Rice parser locates actual compressed RIFF fields for causal negatives.
let cursor=40;const get=count=>{let value=0;for(let i=0;i<count;i++){value=value*2+((bytes[0][cursor>>>3]>>>(7-(cursor&7)))&1);cursor++;}return value;};const rice=k=>{let q=0;while(!get(1)){assert.ok(++q<4096);}return q*2**k+get(k);},uint=()=>rice(rice(2));
const fields={};for(const name of ['type','channels','block','predictor','mean','skip']){const start=cursor,value=uint();fields[name]={start,end:cursor,value};}assert.equal(fields.predictor.value,0);assert.equal(rice(2),9);const headerLength=rice(5);assert.equal(headerLength,44);const wave=[];for(let i=0;i<headerLength;i++){const start=cursor,value=rice(8);wave.push({start,end:cursor,value});}
const bitString=b=>Array.from(b,x=>x.toString(2).padStart(8,'0')).join(''),encodeRice=(value,k)=>'0'.repeat(Math.floor(value/2**k))+'1'+(k?(value%2**k).toString(2).padStart(k,'0'):''),encodeUInt=value=>{const k=Math.ceil(Math.log2(value+1));return encodeRice(k,2)+encodeRice(value,k);};
function replaceBits(packet,start,end,bits){const original=bitString(packet),joined=original.slice(0,start)+bits+original.slice(end);return Uint8Array.from(joined.slice(0,8192).match(/.{8}/g).map(x=>parseInt(x,2)));}
let negativeControls=0;
for(const mode of ['riffChannels','riffRate','riffPrecision','riffExtent','predictor','corruptHeader','truncatedAudio']){let changed=bytes[0].slice();if(mode==='riffChannels')changed=replaceBits(changed,wave[22].start,wave[22].end,encodeRice(1,8));if(mode==='riffRate')changed=replaceBits(changed,wave[24].start,wave[24].end,encodeRice(128,8));if(mode==='riffPrecision')changed=replaceBits(changed,wave[34].start,wave[34].end,encodeRice(8,8));if(mode==='riffExtent'){changed=replaceBits(changed,wave[40].start,wave[40].end,encodeRice(0,8));changed=replaceBits(changed,wave[4].start,wave[4].end,encodeRice(36,8));}if(mode==='predictor')changed=replaceBits(changed,fields.predictor.start,fields.predictor.end,encodeUInt(65535));if(mode==='corruptHeader')changed.fill(255,5,40);const d=new PacketAudioDecoder(module,'shorten',new AbortController().signal,config);try{assert.throws(()=>{for(const packet of(mode==='truncatedAudio'?bytes.slice(0,200):[changed,...bytes.slice(1)]))d.decode(packet,0);d.flush();},/Audio codec failed/,'sourceRIFF/predictor/EOF control '+mode);}finally{d.dispose();}negativeControls++;}
const partialReset=module._mc_create_config(28,44100,2,16,0,0);assert.ok(partialReset);assert.ok(module._mc_reset(partialReset,0)<0,'partial predictor reset is unsupported');module._mc_destroy(partialReset);
const abort=new AbortController(),victim=new PacketAudioDecoder(module,'shorten',abort.signal,config);abort.abort();assert.throws(()=>victim.flush(),e=>e.name==='AbortError');
const inputs=Object.fromEntries(await Promise.all(['native/audio-codecs/decoder.c','packages/provider-audio/src/packet-decoder.ts','tests/shorten-audio-fixtures.py','tests/shorten-audio.mjs'].map(async p=>[p,sha(await readFile(p))])));const report={passed:true,scope:'Canonical60.48sec Shorten version2 RIFF44100stereo16 exact original integer PCM, absent native PTS explicitly replaced by decoded stream sample clock, complete predictor reset and restart-from-start/discard seek; no arbitrary packet restart or source recipe admission.',inputs,adapterSHA256:sha(await readFile(adapterPath)),fixture:f,frames:frames.length,packets:packets.length,samples:f.referenceSamples,maxFramesPerCall,maxScalarSamplesPerCall,timestampOrigin:'stream-clock',nativeFramePTSAbsent:true,negativeControls,seeks,build:{recordSHA256:pointer.recordSHA256,nativeBuildInputs:record.inputs,module:record.artifacts['module.mjs'],wasm:record.artifacts['module.wasm']}};await mkdir('results/media-components/codec-expansion',{recursive:true});await writeFile(process.env.SHORTEN_REPORT??'results/media-components/codec-expansion/shorten-audio.json',JSON.stringify(report,null,2)+'\n');console.log('Canonical Shorten PASS',frames.length,'frames',maxFramesPerCall,'max frames per call');
