#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Pinned canonical speech packets and independent FFmpeg9 scalar reference PCM."""
import pathlib,json,subprocess,hashlib,shutil,os
root=pathlib.Path(os.environ.get('SPEECH_FIXTURE_ROOT','/tmp/demuxe-speech-fixtures'));root.mkdir(parents=True,exist_ok=True)
reference=pathlib.Path(os.environ.get('SPEECH_REFERENCE_ROOT','/tmp/demuxe-speech-native-reference'));ffmpeg=str(reference/'ffmpeg');ffprobe=str(reference/'ffprobe');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
record=json.loads((reference/'build-record.json').read_text());assert sha(reference/'ffmpeg')==record['artifacts']['ffmpeg']['sha256'];assert sha(reference/'ffprobe')==record['artifacts']['ffprobe']['sha256']
inventory=json.load(open('results/media-components/codec-expansion/speech-adpcm-aac-inventory.json'));rows=[]
def unhex(s):return bytes.fromhex(''.join(line.split(':')[1].split('  ')[0].replace(' ','')for line in s.splitlines()if ':'in line))
for f in inventory['realFixtures']:
 if f['id']not in ['speex-flv','amrnb-475','amrwb-660']:continue
 original=pathlib.Path(f['path']);assert sha(original)==f['sha256'];ident=f['id'];codec={'speex-flv':'speex','amrnb-475':'amrnb','amrwb-660':'amrwb'}[ident];rate=8000 if codec=='amrnb'else 16000;source=root/(ident+('.flv'if codec=='speex'else'.amr'if codec=='amrnb'else'.awb'));derivation=None
 if codec=='amrwb':
  # FATE's .awb original is actually3GP. Retain its verified original codec packets.
  original_host=json.loads(subprocess.check_output(['ffprobe','-v','error','-select_streams','a:0','-show_streams','-show_packets','-show_data','-of','json',str(original)]));(root/(ident+'.origin.json')).write_text(json.dumps(original_host,indent=2)+'\n');assert original.read_bytes()[4:8]==b'ftyp';packets=original_host['packets'];assert all(unhex(p['data'])[0]==4 and len(unhex(p['data']))==18 and int(p['pts'])==i*320 for i,p in enumerate(packets));source.write_bytes(b'#!AMR-WB\n'+b''.join(unhex(p['data'])for p in packets));derivation='Bit-identical mode0 packet extraction from canonical3GP into raw AMR-WB signature; original320-sample clock verified.'
 else:shutil.copyfile(original,source)
 packet=root/(ident+'.json');packet.write_bytes(subprocess.check_output([ffprobe,'-v','error','-select_streams','a:0','-show_streams','-show_packets','-show_data','-of','json',str(source)]));data=json.loads(packet.read_bytes());stream=data['streams'][0];assert int(stream['sample_rate'])==rate and stream['channels']==1;assert not unhex(stream.get('extradata',''))
 frames=root/(ident+'.frames.json');frames.write_bytes(subprocess.check_output([ffprobe,'-v','error','-select_streams','a:0','-show_frames','-show_entries','frame=pts_time,nb_samples,sample_fmt,channel_layout','-of','json',str(source)]));shape=json.loads(frames.read_bytes())['frames'];assert len(shape)==len(data['packets']);assert all(x['nb_samples']in([320,640]if codec=='speex'else[160]if codec=='amrnb'else[320])for x in shape)
 if codec!='speex':assert all(unhex(p['data'])[0]==4 and len(unhex(p['data']))==(13 if codec=='amrnb'else 18)for p in data['packets'])
 for ext,fmt in [('f32','f32le'),('s32','s32le')]:subprocess.run([ffmpeg,'-v','error','-xerror','-cpuflags','0','-c:a',codec,'-y','-i',str(source),'-map','0:a:0','-f',fmt,str(root/(ident+'.'+ext))],check=True)
 samples=(root/(ident+'.f32')).stat().st_size//4;assert samples==sum(frame['nb_samples']for frame in shape);pts=[round(float(p['pts_time'])*rate)for p in data['packets']];gaps=[dict(packet=i,previousEnd=pts[i-1]+shape[i-1]['nb_samples'],nextPTS=pts[i])for i in range(1,len(pts))if pts[i]!=pts[i-1]+shape[i-1]['nb_samples']]
 rows.append(dict(id=ident,profile='speech',codec=codec,sampleRate=rate,channels=1,bitsPerSample=0,input=str(source),inputSHA256=sha(source),originSHA256=f['sha256'],sourceURL=f['url'],derivation=derivation,originPacketSHA256=sha(root/(ident+'.origin.json'))if derivation else None,packetSHA256=sha(packet),framesSHA256=sha(frames),referenceF32SHA256=sha(root/(ident+'.f32')),referenceSHA256=sha(root/(ident+'.f32')),referenceIntegerSHA256=sha(root/(ident+'.s32')),referenceSamples=samples,fixtureRoot=str(root),generated=False,seekContract='restart-from-start-and-discard',timestampGaps=gaps,packetMetadata='original container PTS; no concatenated sample-clock replacement',mode='headerless-FLV-wideband'if codec=='speex'else'mode0-4.75kbps'if codec=='amrnb'else'mode0-6.60kbps'))
(root/'fixtures.json').write_text(json.dumps(rows,indent=2)+'\n');(root/'packet-browser.json').write_text(json.dumps([{**row,'generated':True,'fixtureOrigin':'official','speechFloatQualification':{'maxAbsoluteError':7e-5,'minimumSNR':80,'mandatorySilentControl':True,'mandatoryCorruptControl':True}}for row in rows],indent=2)+'\n');(root/'reference-build.json').write_text(json.dumps(record,indent=2)+'\n');print(len(rows),'speech fixtures ready')
