// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
const sha=b=>createHash('sha256').update(b).digest('hex'),root=process.env.SPEECH_FIXTURE_ROOT??'/tmp/demuxe-speech-fixtures',adapter=process.env.SPEECH_ADAPTER_MODULE??'/tmp/demuxe-speech-adapter/packet-decoder.js';
const {PacketAudioDecoder}=await import(pathToFileURL(adapter)),pointer=JSON.parse(await readFile('/tmp/demuxe-speech-builds/speech.json')),raw=await readFile(pointer.directory+'/build-record.json');assert.equal(sha(raw),pointer.recordSHA256);const record=JSON.parse(raw),wasm=await readFile(pointer.directory+'/module.wasm'),js=await readFile(pointer.directory+'/module.mjs');assert.equal(sha(wasm),record.artifacts['module.wasm'].sha256);assert.equal(sha(js),record.artifacts['module.mjs'].sha256);const module=await(await import(pathToFileURL(pointer.directory+'/module.mjs'))).default({wasmBinary:wasm});
const unhex=s=>Uint8Array.from(Buffer.from(s.split('\n').filter(s=>s.includes(':')).map(s=>s.split(':')[1].split('  ')[0].replaceAll(' ','')).join(''),'hex')),fixtures=JSON.parse(await readFile(root+'/fixtures.json')),results=[];let controls=0;
function compare(actual,expected,fullStream=true){assert.equal(actual.length*4,expected.length);let maxError=0,signal=0,error=0;for(let i=0;i<actual.length;i++){const ref=expected.readFloatLE(i*4),difference=actual[i]-ref;assert.ok(Number.isFinite(actual[i])&&Number.isFinite(ref));maxError=Math.max(maxError,Math.abs(difference));signal+=ref*ref;error+=difference*difference;}const snr=10*Math.log10(signal/Math.max(error,1e-30));assert.ok(maxError<7e-5&&(!fullStream||snr>80),'scalar speech PCM error '+maxError+' SNR '+snr);return{maxError,snr};}
for(const f of fixtures){const input=await readFile(f.input),packetRaw=await readFile(root+'/'+f.id+'.json'),frameRaw=await readFile(root+'/'+f.id+'.frames.json'),reference=await readFile(root+'/'+f.id+'.f32');assert.equal(sha(input),f.inputSHA256);assert.equal(sha(packetRaw),f.packetSHA256);assert.equal(sha(frameRaw),f.framesSHA256);assert.equal(sha(reference),f.referenceF32SHA256);const packets=JSON.parse(packetRaw).packets.map(p=>({bytes:unhex(p.data),pts:Math.round(Number(p.pts_time)*f.sampleRate)})),metadata=JSON.parse(frameRaw).frames,config={sampleRate:f.sampleRate,channels:1,bitsPerSample:0,extradata:new Uint8Array()},signal=new AbortController().signal,d=new PacketAudioDecoder(module,f.codec,signal,config);let comparison,seeks=[];
 const full=()=>{const frames=[];for(const p of packets){const out=d.decode(p.bytes,p.pts);assert.equal(out.length,1);assert.equal(out[0].pts,p.pts);frames.push(...out);}frames.push(...d.flush());assert.deepEqual(d.flush(),[]);assert.equal(frames.length,metadata.length);for(let i=0;i<frames.length;i++){const frame=frames[i];assert.equal(frame.samples,metadata[i].nb_samples);assert.equal(frame.pts,Math.round(Number(metadata[i].pts_time)*f.sampleRate));assert.equal(frame.rate,f.sampleRate);assert.equal(frame.channels,1);assert.equal(frame.layout,4);assert.equal(frame.planes.length,1);assert.equal(frame.pcm,undefined);}const actual=Float32Array.from(frames.flatMap(f=>Array.from(f.planes[0])));comparison=compare(actual,reference);assert.throws(()=>compare(new Float32Array(actual.length),reference),'silent PCM control');return frames;};
 let frames;try{frames=full();assert.equal(frames.reduce((n,f)=>n+f.samples,0),f.referenceSamples);d.reset();assert.deepEqual(full().map(({generation,...f})=>f),frames.map(({generation,...f})=>f));
 for(const fraction of [.8,.3,.95,.1]){d.reset();const target=Math.floor(packets.length*fraction),offset=frames.slice(0,target).reduce((n,f)=>n+f.samples,0);let targetFrame;for(let i=0;i<=target;i++){const out=d.decode(packets[i].bytes,packets[i].pts);if(i===target)targetFrame=out[0];}assert.ok(targetFrame);assert.deepEqual(targetFrame.planes,frames[target].planes,'full original predictor state after restart/discard');const checked=compare(targetFrame.planes[0],reference.subarray(offset*4,(offset+targetFrame.samples)*4),false);seeks.push({targetPacket:target,originalPTS:targetFrame.pts,referenceOffsetSample:offset,comparedSamples:targetFrame.samples,firstPacket:0,contract:'original-stream-restart-and-discard',...checked});}
 // An arbitrary block reset is distinct from qualified original predictor history.
 const start=Math.floor(packets.length*.7);d.reset();const restarted=d.decode(packets[start].bytes,packets[start].pts)[0],offset=frames.slice(0,start).reduce((n,f)=>n+f.samples,0);assert.throws(()=>compare(restarted.planes[0],reference.subarray(offset*4,(offset+restarted.samples)*4)),'arbitrary packet restart must not be advertised as original seek');controls++;
 }finally{d.dispose();d.dispose();}
 for(const change of [{sampleRate:f.codec==='amrnb'?16000:8000},{channels:2},{bitsPerSample:16},{extradata:new Uint8Array(80)},{blockAlign:33},{bitRate:64000}]){assert.throws(()=>new PacketAudioDecoder(module,f.codec,signal,{...config,...change}),e=>e.code==='PROVIDER_PROFILE_MISMATCH');controls++;}
 for(const mode of ['negativePTS','overflowPTS','size','header']){const bad=new PacketAudioDecoder(module,f.codec,signal,config);let packet=packets[0].bytes.slice();if(mode==='size')packet=f.codec==='speex'?new Uint8Array(2049):packet.subarray(0,-1);if(mode==='header')packet.fill(0);try{assert.throws(()=>{const frames=bad.decode(packet,mode==='negativePTS'?-1:mode==='overflowPTS'?Number.MAX_SAFE_INTEGER:0);if(frames.length)compare(frames[0].planes[0],reference.subarray(0,frames[0].samples*4));});}finally{bad.dispose();}controls++;}
 const abort=new AbortController(),victim=new PacketAudioDecoder(module,f.codec,abort.signal,config);abort.abort();assert.throws(()=>victim.flush(),e=>e.name==='AbortError');victim.dispose();controls++;
 results.push({id:f.id,codec:f.codec,inputSHA256:f.inputSHA256,referenceF32SHA256:f.referenceF32SHA256,samples:f.referenceSamples,frames:frames.length,nativeFrameDurations:[...new Set(frames.map(f=>f.duration))],timestampGaps:f.timestampGaps,resetExact:true,seeks,...comparison});
}
const unsupported=[];
for(const [codec,kind,rate,header]of [['amrnb',36,8000,68],['amrwb',37,16000,76]]){const config={sampleRate:rate,channels:1,bitsPerSample:0,extradata:new Uint8Array()},packet=new Uint8Array(6);packet[0]=header;const guarded=new PacketAudioDecoder(module,codec,new AbortController().signal,config);try{assert.throws(()=>guarded.decode(packet,0),/Unsupported AMR SID\/DTX/);}finally{guarded.dispose();}const owner=module._mc_create_config(kind,rate,1,0,0,0),p=module._malloc(6);assert.ok(owner);try{module.HEAPU8.set(packet,p);let error=module._mc_decode(owner,p,6,0);if(error>=0)error=module._mc_frame(owner);assert.equal(error,-1163346256,'native unsupported SID/DTX PATCHWELCOME');unsupported.push({codec,nativeError:error,wrapperRejected:true});}finally{module._mc_destroy(owner);module._free(p);}controls++;}
// Independent native profile/payload guards do not rely on the adapter.
for(const[kind,rate,size]of [[35,16000,2049],[36,8000,12],[37,16000,17]]){const p=module._malloc(4096);try{for(const[changedRate,channels,bits,extraSize]of [[48000,1,0,0],[rate,2,0,0],[rate,1,16,0],[rate,1,0,1]]){assert.equal(module._mc_create_config(kind,changedRate,channels,bits,p,extraSize),0);controls++;}const owner=module._mc_create_config(kind,rate,1,0,0,0);assert.ok(owner);try{module.HEAPU8.fill(0,p,p+4096);for(const pts of [-1,NaN,Infinity,.5]){assert.ok(module._mc_decode(owner,p,1,pts)<0);controls++;}assert.ok(module._mc_decode(owner,p,size,0)<0);controls++;}finally{module._mc_destroy(owner);}}finally{module._free(p);}}
const referenceRaw=await readFile('/tmp/demuxe-speech-native-reference/build-record.json'),referenceBuild=JSON.parse(referenceRaw);for(const name of ['ffmpeg','ffprobe'])assert.equal(sha(await readFile('/tmp/demuxe-speech-native-reference/'+name)),referenceBuild.artifacts[name].sha256);for(const[name,hash]of Object.entries(record.inputs))assert.equal(sha(await readFile('/tmp/demuxe-speech-source-inputs/'+name)),hash,'retained native input');const report={passed:true,scope:'Finite canonical SpeexFLV wideband mono original packet PTS with gaps and mode0 AMRNB/WB speech; original fullstream float reference/reset/restart-discard seeks only. No container, FLAC or playback admission.',inputs:Object.fromEntries(await Promise.all(['packages/provider-audio/src/packet-decoder.ts','scripts/build-speech-reference.py','tests/speech-audio-fixtures.py','tests/speech-audio.mjs'].map(async p=>[p,sha(await readFile(p))]))),adapterSHA256:sha(await readFile(adapter)),fixturesSHA256:sha(await readFile(root+'/fixtures.json')),controls,unsupported,results,referenceBuild:{recordSHA256:sha(referenceRaw),...referenceBuild},build:{recordSHA256:pointer.recordSHA256,nativeInputs:record.inputs,module:record.artifacts['module.mjs'],wasm:record.artifacts['module.wasm']}};await mkdir('results/media-components/codec-expansion',{recursive:true});await writeFile('results/media-components/codec-expansion/speech-audio.json',JSON.stringify(report,null,2)+'\n');console.log('Speech PASS',results.length,'fullstreams',results.reduce((n,r)=>n+r.seeks.length,0),'original seeks',controls,'controls');
