// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
const sha=b=>createHash('sha256').update(b).digest('hex'),root=process.env.TELEPHONY_FIXTURE_ROOT??'/tmp/demuxe-telephony-fixtures',adapter=process.env.TELEPHONY_ADAPTER_MODULE??'/tmp/demuxe-telephony-adapter/packet-decoder.js';
const {PacketAudioDecoder}=await import(pathToFileURL(adapter)),pointer=JSON.parse(await readFile('/tmp/demuxe-telephony-builds/telephony.json')),raw=await readFile(pointer.directory+'/build-record.json');assert.equal(sha(raw),pointer.recordSHA256);const record=JSON.parse(raw),wasm=await readFile(pointer.directory+'/module.wasm'),js=await readFile(pointer.directory+'/module.mjs');assert.equal(sha(wasm),record.artifacts['module.wasm'].sha256);assert.equal(sha(js),record.artifacts['module.mjs'].sha256);const module=await(await import(pathToFileURL(pointer.directory+'/module.mjs'))).default({wasmBinary:wasm});
const fixtures=JSON.parse(await readFile(root+'/fixtures.json')),results=[];let negativeControls=0;
const unhex=s=>Uint8Array.from(Buffer.from(s.split('\n').filter(s=>s.includes(':')).map(s=>s.split(':')[1].split('  ')[0].replaceAll(' ','')).join(''),'hex'));
for(const f of fixtures){
 const source=await readFile(f.input),packetRaw=await readFile(root+'/'+f.id+'.json'),hostRaw=await readFile(root+'/'+f.id+'.host.json'),reference=await readFile(root+'/'+f.id+'.s32');assert.equal(sha(source),f.inputSHA256);assert.equal(sha(packetRaw),f.packetSHA256);assert.equal(sha(hostRaw),f.hostPacketSHA256);assert.equal(sha(reference),f.referenceSHA256);const packets=JSON.parse(packetRaw).packets.map(p=>({...p,bytes:unhex(p.data)})),config={sampleRate:f.sampleRate,channels:f.channels,bitsPerSample:f.bitsPerSample,extradata:Uint8Array.from(Buffer.from(f.extradata,'hex')),...f.framing},signal=new AbortController().signal,d=new PacketAudioDecoder(module,f.codec,signal,config);let count=0,maxFrames=0;
 const full=()=>{const frames=[];for(const p of packets){const part=d.decode(p.bytes,p.pts);assert.equal(part.length,1);assert.equal(part[0].pts,p.pts);assert.equal(part[0].samples,p.duration);assert.ok(part[0].duration===0||part[0].duration===p.duration);maxFrames=Math.max(maxFrames,part.length);frames.push(...part);}frames.push(...d.flush());assert.deepEqual(d.flush(),[]);let clock=0;for(const frame of frames){assert.equal(frame.pts,clock);assert.equal(frame.rate,f.sampleRate);assert.equal(frame.channels,f.channels);assert.equal(frame.layout,f.channels===1?4:3);assert.ok(frame.pcm instanceof Int32Array);assert.ok(frame.pcm.every(x=>(x&65535)===0));clock+=frame.samples;}assert.equal(clock,f.referenceSamples);assert.deepEqual(Buffer.concat(frames.map(frame=>Buffer.from(frame.pcm.buffer,frame.pcm.byteOffset,frame.pcm.byteLength))),reference);return frames;};
 let frames,seeks=[];try{frames=full();count=frames.length;d.reset();assert.deepEqual(full().map(({generation,...frame})=>frame),frames.map(({generation,...frame})=>frame));
  for(const fraction of [.8,.3,.95,.1]){d.reset();const target=Math.floor(f.referenceSamples*fraction),end=Math.min(f.referenceSamples,target+320),parts=[];let compared=0;for(const p of packets){if(f.codec.startsWith('pcm-')&&p.pts+p.duration<=target)continue;for(const frame of d.decode(p.bytes,p.pts)){const from=Math.max(target,frame.pts),to=Math.min(end,frame.pts+frame.samples);if(to>from){const actual=Buffer.from(frame.pcm.buffer,frame.pcm.byteOffset+(from-frame.pts)*f.channels*4,(to-from)*f.channels*4);assert.deepEqual(actual,reference.subarray(from*f.channels*4,to*f.channels*4));parts.push(actual);compared+=to-from;}}if(compared===end-target)break;}assert.equal(compared,end-target);seeks.push({targetSample:target,comparedSamples:compared,contract:f.seekContract,integerExact:true});}
 }finally{d.dispose();d.dispose();}
 for(const change of [{sampleRate:44100},{channels:6},{bitsPerSample:16},{blockAlign:0},{bitRate:0},{extradata:new Uint8Array([0])}]){assert.throws(()=>new PacketAudioDecoder(module,f.codec,signal,{...config,...change}),e=>e.code==='PROVIDER_PROFILE_MISMATCH');negativeControls++;}
 for(const mode of ['negativePTS','overflowEndPTS','packetSize',...(f.codec==='gsm'?['magic']:[])]){const victim=new PacketAudioDecoder(module,f.codec,signal,config);let packet=packets[0].bytes;if(mode==='packetSize')packet=f.codec.startsWith('pcm-')?new Uint8Array(4097):packet.subarray(0,packet.length-1);if(mode==='magic'){packet=packet.slice();packet[0]&=15;}try{assert.throws(()=>victim.decode(packet,mode==='negativePTS'?-1:mode==='overflowEndPTS'?Number.MAX_SAFE_INTEGER:0),e=>e.code==='PROVIDER_PROFILE_MISMATCH');}finally{victim.dispose();}negativeControls++;}
 const cancelled=new AbortController(),victim=new PacketAudioDecoder(module,f.codec,cancelled.signal,config);cancelled.abort();assert.throws(()=>victim.flush(),e=>e.name==='AbortError');victim.dispose();negativeControls++;
 results.push({id:f.id,codec:f.codec,sampleRate:f.sampleRate,channels:f.channels,codedBits:f.bitsPerSample,decodedBits:16,inputSHA256:f.inputSHA256,referenceSHA256:f.referenceSHA256,frames:count,nativeFrameDurations:[...new Set(frames.map(frame=>frame.duration))],samples:f.referenceSamples,maxFramesPerCall:maxFrames,resetExact:true,seeks});
}
// Independent C guards remain enforced when callers bypass the TypeScript adapter.
for(const [kind,rate,ch,bits,align,bitrate,extra]of [[31,8000,1,8,1,64000,[]],[32,16000,2,8,2,256000,[]],[33,8000,1,0,33,13200,[]],[34,8000,1,0,65,13000,[64,1]]]){
 const p=module._malloc(Math.max(1,extra.length));module.HEAPU8.set(extra,p);const create=(changes={})=>module._mc_create_config_v2(kind,changes.rate??rate,changes.ch??ch,changes.bits??bits,p,changes.size??extra.length,changes.align??align,changes.bitrate??bitrate);
 try{const valid=create({});assert.ok(valid>0);module._mc_destroy(valid);for(const bad of [{rate:48000},{ch:6},{bits:16},{align:0},{bitrate:0},{size:1}]){assert.equal(create(bad),0);negativeControls++;}const owner=create();assert.ok(owner);try{module.HEAPU8.fill(0,p,p+Math.max(extra.length,1));assert.ok(module._mc_decode(owner,p,1,-1)<0);assert.ok(module._mc_decode(owner,p,1,Number.NaN)<0);assert.ok(module._mc_decode(owner,p,1,Number.POSITIVE_INFINITY)<0);}finally{module._mc_destroy(owner);}}finally{module._free(p);}
}
const gsm=fixtures.find(f=>f.id==='gsm-long'),packets=JSON.parse(await readFile(root+'/'+gsm.id+'.json')).packets,reference=await readFile(root+'/'+gsm.id+'.s32'),p=packets[300],fresh=new PacketAudioDecoder(module,'gsm',new AbortController().signal,{sampleRate:8000,channels:1,bitsPerSample:0,extradata:new Uint8Array(),blockAlign:33,bitRate:13200});try{const frame=fresh.decode(unhex(p.data),p.pts)[0];assert.notDeepEqual(Buffer.from(frame.pcm.buffer),reference.subarray(p.pts*4,(p.pts+p.duration)*4),'GSM arbitrary block restart is not a qualified seek');}finally{fresh.dispose();}
const names=['packages/provider-audio/src/packet-decoder.ts','tests/telephony-audio-fixtures.py','tests/telephony-audio.mjs'],inputs=Object.fromEntries(await Promise.all(names.map(async p=>[p,sha(await readFile(p))]))),report={passed:true,scope:'Native finite telephony integer decoder packet proof; no low-rate FLAC composition/browser/source recipe admission',adapterSHA256:sha(await readFile(adapter)),inputs,fixturesSHA256:sha(await readFile(root+'/fixtures.json')),negativeControls,results,build:{recordSHA256:pointer.recordSHA256,nativeInputs:record.inputs,module:record.artifacts['module.mjs'],wasm:record.artifacts['module.wasm']}};await mkdir('results/media-components/codec-expansion',{recursive:true});await writeFile(process.env.TELEPHONY_REPORT??'results/media-components/codec-expansion/telephony-audio.json',JSON.stringify(report,null,2)+'\n');console.log('Telephony PASS',results.length,'fixtures',results.reduce((n,r)=>n+r.seeks.length,0),'seeks',negativeControls,'controls');
