// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out='results/top100/gpu',input=JSON.parse(await readFile(out+'/input.json','utf8'));const ivf=await readFile('results/full-completion/r332/altref.ivf');input.vp9=[...ivf.subarray(44,44+ivf.readUInt32LE(32))];const result={scope:'Actual WebGPU compressed Hap/FLIC representation, decoder-independent device recovery. Tiny component experiments, no physical overlay/energy or whole-player claims.'};const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser;
try{const origin=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('server')),10000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});});browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto(origin+'/examples/custom-controls.html');result.probes=await page.evaluate(async input=>{
 const adapter=await navigator.gpu?.requestAdapter();if(!adapter)return {blocked:'No WebGPU adapter'};const features=[...adapter.features],info={vendor:adapter.info.vendor,architecture:adapter.info.architecture,device:adapter.info.device,description:adapter.info.description};let device=await adapter.requestDevice({requiredFeatures:features.includes('texture-compression-bc')?['texture-compression-bc']:[]});const errors=[];device.addEventListener('uncapturederror',e=>errors.push(e.error.message));
 const vertex='@vertex fn vs(@builtin(vertex_index) i:u32)->@builtin(position) vec4f {var p=array<vec2f,3>(vec2f(-1,-1),vec2f(3,-1),vec2f(-1,3));return vec4f(p[i],0,1);}';
 const render=async(textures,fragment,w,h)=>{const shader=device.createShaderModule({code:vertex+fragment}),pipeline=device.createRenderPipeline({layout:'auto',vertex:{module:shader,entryPoint:'vs'},fragment:{module:shader,entryPoint:'fs',targets:[{format:'rgba8unorm'}]}});const bg=device.createBindGroup({layout:pipeline.getBindGroupLayout(0),entries:textures.map((t,i)=>({binding:i,resource:t.createView()}))});const target=device.createTexture({size:[w,h],format:'rgba8unorm',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC}),read=device.createBuffer({size:256*h,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ}),encoder=device.createCommandEncoder(),pass=encoder.beginRenderPass({colorAttachments:[{view:target.createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,1]}]});pass.setPipeline(pipeline);pass.setBindGroup(0,bg);pass.draw(3);pass.end();encoder.copyTextureToBuffer({texture:target},{buffer:read,bytesPerRow:256},[w,h]);device.queue.submit([encoder.finish()]);await read.mapAsync(GPUMapMode.READ);const mapped=new Uint8Array(read.getMappedRange()),bytes=[];for(let y=0;y<h;y++)bytes.push(...mapped.slice(y*256,y*256+w*4));read.unmap();read.destroy();target.destroy();return bytes;};
 const exact=(a,b)=>a.length===b.length&&a.every((x,i)=>x===b[i]);const sample='@group(0) @binding(0) var t:texture_2d<f32>;@fragment fn fs(@builtin(position) p:vec4f)->@location(0) vec4f{return textureLoad(t,vec2i(p.xy),0);}';
 const hap={supported:features.includes('texture-compression-bc')};if(hap.supported){const packet=new Uint8Array(input.hap.packet);if(packet[3]!==0xab||packet.length!==20)throw Error('Hap scoped header');const t=device.createTexture({size:[8,4],format:'bc1-rgba-unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST});device.queue.writeTexture({texture:t},packet.subarray(4),{bytesPerRow:16},[8,4]);const pixels=await render([t],sample,8,4);hap.exact=exact(pixels,input.hap.rgba);hap.compressedBytes=16;hap.rgbaBytes=128;t.destroy();}
 const b=new Uint8Array(input.flic.file),v=new DataView(b.buffer);if(v.getUint16(4,true)!==0xaf12)throw Error('FLC header');let p=128,indices=new Uint8Array(16),palette=new Uint8Array(1024);for(let i=0;i<256;i++)palette[i*4+3]=255;const flc=[];for(let n=0;n<2;n++){const size=v.getUint32(p,true),count=v.getUint16(p+6,true);let q=p+16;for(let c=0;c<count;c++){const len=v.getUint32(q,true),type=v.getUint16(q+4,true);if(q+len>p+size)throw Error('FLC chunk bounds');if(type===4){let a=q+8,index=0;const packets=v.getUint16(q+6,true);for(let k=0;k<packets;k++){index+=b[a++];let num=b[a++]||256;if(index+num>256)throw Error('Palette bounds');while(num--){palette.set(b.subarray(a,a+3),index++*4);a+=3;}}}else if(type===16){if(len!==22)throw Error('COPY bounds');indices=b.slice(q+6,q+len);}else throw Error('Unknown FLC chunk');q+=len;}p+=size;const ti=device.createTexture({size:[4,4],format:'r8uint',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST}),tp=device.createTexture({size:[256,1],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST});device.queue.writeTexture({texture:ti},indices,{bytesPerRow:4},[4,4]);device.queue.writeTexture({texture:tp},palette,{bytesPerRow:1024},[256,1]);const pixels=await render([ti,tp],'@group(0) @binding(0) var i:texture_2d<u32>;@group(0) @binding(1) var pal:texture_2d<f32>;@fragment fn fs(@builtin(position) p:vec4f)->@location(0) vec4f{let index=textureLoad(i,vec2i(p.xy),0).r;return textureLoad(pal,vec2i(i32(index),0),0);}',4,4);flc.push({exact:exact(pixels,input.flic.rgbaFrames[n]),pixels});ti.destroy();tp.destroy();}
 let resolveFrame;const frames=[],decoder=new VideoDecoder({output:f=>resolveFrame(f),error:e=>errors.push(String(e))});decoder.configure({codec:'vp09.00.10.08',codedWidth:160,codedHeight:96});const decode=timestamp=>new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('decode deadline')),5000);resolveFrame=f=>{clearTimeout(t);resolve(f);};decoder.decode(new EncodedVideoChunk({type:'key',timestamp,data:new Uint8Array(input.vp9)}));});const frame=await decode(0);const upload=async()=>{const t=device.createTexture({size:[160,96],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});device.queue.copyExternalImageToTexture({source:frame},{texture:t},[160,96]);const pixels=await render([t],sample,160,96);t.destroy();return pixels;};
 // Larger readback uses aligned rows; the small renderer above uses256, so compare a64-pixel crop for recovery.
 const recoveryRender=async()=>{const t=device.createTexture({size:[160,96],format:'rgba8unorm',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});device.queue.copyExternalImageToTexture({source:frame},{texture:t},[160,96]);const pixels=await render([t],sample,64,64);t.destroy();return pixels;};const before=await recoveryRender();device.destroy();const loss=await device.lost;const nextAdapter=await navigator.gpu.requestAdapter();device=await nextAdapter.requestDevice();const after=await recoveryRender(),nextFrame=await decode(1000000);const recovery={loss:loss.reason,redrawExact:exact(before,after),decoderStillConfigured:decoder.state==='configured',nextDecodedTimestamp:nextFrame.timestamp,decoderInstances:1};nextFrame.close();frame.close();decoder.close();device.destroy();return {features,info,hap,flic:flc,recovery,errors,cleanup:true};
},input);assert.ok(!result.probes.blocked,JSON.stringify(result.probes));if(result.probes.hap.supported)assert.ok(result.probes.hap.exact);assert.ok(result.probes.flic.every(x=>x.exact));assert.ok(result.probes.recovery.redrawExact&&result.probes.recovery.decoderStillConfigured&&result.probes.recovery.nextDecodedTimestamp===1000000);assert.equal(result.probes.errors.length,0);await page.evaluate(()=>player.destroy());result.passed=true;
}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();await writeFile(out+'/result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));}
