// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out='results/top100/gpu',input=JSON.parse(await readFile(out+'/zmbv-input.json','utf8')),result={scope:'Actual persistent browser zlib ZMBV32 reconstruction, eight frames against independent FFmpeg BGR0 oracle. CPU component, no GPU or integrated playback claim.'};const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser;
try{const origin=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('server')),10000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});});browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto(origin+'/examples/custom-controls.html');result.probe=await page.evaluate(async input=>{
 const deadline=p=>Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(Error('stream deadline')),3000))]);const ds=new DecompressionStream('deflate'),writer=ds.writable.getWriter(),reader=ds.readable.getReader();let pending=new Uint8Array(),previous=null,bw,bh;const rows=[];const validateState=(p,previous)=>{if(!(p[0]&1)&&!previous)throw Error('dependent frame without key');};let coldDeltaRejected=false;try{validateState(new Uint8Array(input.packets[1]),null);}catch(e){coldDeltaRejected=e.message==='dependent frame without key';}
 const take=async n=>{while(pending.length<n){const r=await deadline(reader.read());if(r.done)throw Error('early inflate EOF');const next=new Uint8Array(pending.length+r.value.length);next.set(pending);next.set(r.value,pending.length);pending=next;if(pending.length>32768)throw Error('inflate budget');}const result=pending.slice(0,n);pending=pending.slice(n);return result;};
 try{for(let i=0;i<input.packets.length;i++){const p=new Uint8Array(input.packets[i]),key=p[0]&1;validateState(p,previous);if(key){if(i!==0||p[1]!==0||p[2]!==1||p[3]!==1||p[4]!==8)throw Error('unsupported header');bw=p[5];bh=p[6];if(!bw||!bh)throw Error('block dimensions');}else if(!previous)throw Error('dependent frame without key');const write=writer.write(p.subarray(key?7:1));write.catch(()=>{});let current;
 if(key)current=await take(4096);else{const nx=Math.ceil(32/bw),ny=Math.ceil(32/bh),vectors=await take((nx*ny*2+3)&~3);current=new Uint8Array(4096);for(let by=0;by<ny;by++)for(let bx=0;bx<nx;bx++){const k=(by*nx+bx)*2,sx=(vectors[k]<<24)>>24,sy=(vectors[k+1]<<24)>>24,dx=sx>>1,dy=sy>>1,w=Math.min(bw,32-bx*bw),h=Math.min(bh,32-by*bh),xor=sx&1,residual=xor?await take(w*h*4):null;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const tx=bx*bw+x,ty=by*bh+y,px=tx+dx,py=ty+dy;for(let c=0;c<4;c++)current[(ty*32+tx)*4+c]=((px>=0&&px<32&&py>=0&&py<32)?previous[(py*32+px)*4+c]:0)^(xor?residual[(y*w+x)*4+c]:0);}}}
 await deadline(write);const exact=current.every((x,k)=>x===input.oracle[i][k]);rows.push({frame:i,key:!!key,exact});previous=current;
 }return {rows,coldDeltaRejected,persistentInflater:true,cleanup:true};}finally{await reader.cancel().catch(()=>{});await writer.abort().catch(()=>{});}
 },input);assert.ok(result.probe.rows.every(x=>x.exact));assert.equal(result.probe.rows.length,8);assert.ok(result.probe.coldDeltaRejected);await page.evaluate(()=>player.destroy());result.passed=true;}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();await writeFile(out+'/zmbv-result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));}
