// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='research/shared/runs/20260919T215400Z-queue-pcm-window-order';const fixtures='research/shared/runs/20260919T200300Z-mse-transactions';
const paths={old:fixtures+'/old-audio.mp4',next:fixtures+'/new-audio.mp4',small:'results/top100/lanes/small.mp4',large:'results/top100/lanes/large.mp4',red:'results/top100/mse/red.mp4',green:'results/top100/mse/lime.mp4'};
const files={};for(const [k,p] of Object.entries(paths))files[k]=[...await readFile(p)];
files.old=[...await readFile('research/shared/runs/20260919T215100Z-queue-fixtures/a-a.mp4')];files.next=[...await readFile('research/shared/runs/20260919T215100Z-queue-fixtures/b-a.mp4')];files.small=[...await readFile('research/shared/runs/20260919T215100Z-queue-fixtures/a-v.mp4')];files.large=[...await readFile('research/shared/runs/20260919T215100Z-queue-fixtures/b-v.mp4')];
const result={scope:'Actual source-linked A/V queue A→B→A, compatible AVC and independently encoded48kAAC; each audio clip priming offset1024/48000 and exact two-second append window. Boundary quiet gate5ms, tone440→880→440. This is preliminary PCM continuity; full picture/lifecycle gates remain conditional on it.',cases:[]};
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser;
try{
 const origin=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('server deadline')),10000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});});
 browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto(origin+'/examples/custom-controls.html');
 for(const mode of ['source-linked-queue']){
  const row=await page.evaluate(async({mode,files})=>{
   const v=document.createElement('video');document.body.append(v);const ac=new AudioContext({sampleRate:48000});await ac.resume();const source=ac.createMediaElementSource(v),an=ac.createAnalyser();an.fftSize=4096;source.connect(an);an.connect(ac.destination);const code=`class Capture extends AudioWorkletProcessor{process(inputs,outputs){const x=inputs[0]?.[0];if(x){const b=x.slice();this.port.postMessage({frame:currentFrame,pcm:b},[b.buffer]);outputs[0][0].set(x);}return true;}}registerProcessor('capture',Capture);`;const wu=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));await ac.audioWorklet.addModule(wu);URL.revokeObjectURL(wu);const worklet=new AudioWorkletNode(ac,'capture'),gain=ac.createGain();gain.gain.value=0;source.connect(worklet);worklet.connect(gain);gain.connect(ac.destination);const chunks=[];worklet.port.onmessage=({data})=>{if(v.currentTime>1.85&&v.currentTime<2.15)chunks.push({frame:data.frame,mediaTime:v.currentTime,pcm:[...data.pcm]});};const ms=new MediaSource(),url=URL.createObjectURL(ms),r={mode,observed:[]};let timer;
   const event=(o,n)=>new Promise((resolve,reject)=>{const t=setTimeout(()=>{clean();reject(Error(n+' deadline'));},10000);function clean(){clearTimeout(t);o.removeEventListener(n,ok);o.removeEventListener('error',bad);}function ok(){clean();resolve();}function bad(){clean();reject(Error(n+' failed'));}o.addEventListener(n,ok);o.addEventListener('error',bad);});
   const until=async f=>{const end=performance.now()+5000;while(!f()){if(performance.now()>end)throw Error('until deadline');await new Promise(r=>setTimeout(r,10));}};
   const canvas=new OffscreenCanvas(16,16),ctx=canvas.getContext('2d');const observe=()=>{if(v.readyState<2)return;const f=new Float32Array(an.frequencyBinCount);an.getFloatFrequencyData(f);let best=1;for(let i=2;i<f.length;i++)if(f[i]>f[best])best=i;ctx.drawImage(v,0,0,16,16);r.observed.push({time:v.currentTime,width:v.videoWidth,height:v.videoHeight,frames:v.getVideoPlaybackQuality().totalVideoFrames,hz:best*ac.sampleRate/an.fftSize,db:f[best],pixel:[...ctx.getImageData(8,8,1,1).data]});};
   try{
    const open=event(ms,'sourceopen');v.src=url;await open;const video=ms.addSourceBuffer('video/mp4; codecs="avc1.42C00A"'),audio=ms.addSourceBuffer('audio/mp4; codecs="mp4a.40.2"');const append=async(sb,k)=>{const done=event(sb,'updateend');sb.appendBuffer(new Uint8Array(files[k]));await done;};const remove=async(sb,a,b)=>{const done=event(sb,'updateend');sb.remove(a,b);await done;};
    const initial='small';for(let epoch=0;epoch<3;epoch++){const offset=epoch*2;video.timestampOffset=offset;await append(video,epoch===1?'large':'small');audio.appendWindowEnd=offset+2;audio.appendWindowStart=offset;audio.timestampOffset=offset-1024/48000;await append(audio,epoch===1?'next':'old');}
    timer=setInterval(observe,25);await v.play();await until(()=>v.currentTime>.5);const videoIdentity=video,audioIdentity=audio,sourceIdentity=v.src;let generation=2;
    const ranges=sb=>Array.from({length:sb.buffered.length},(_,i)=>[sb.buffered.start(i),sb.buffered.end(i)]);const before=JSON.stringify([ranges(video),ranges(audio)]);
    const commit=async epoch=>{if(epoch!==generation)return false;if(mode==='source-linked-queue')return true;if(mode.includes('audio')){await remove(audio,2,7);audio.appendWindowStart=2;audio.appendWindowEnd=6;audio.timestampOffset=2;await append(audio,'next');}else{await remove(video,2,6);video.timestampOffset=2;await append(video,mode==='queue'?'green':'large');video.timestampOffset=4;await append(video,initial);}return true;};
    r.staleGenerationRejected=!(await commit(1))&&JSON.stringify([ranges(video),ranges(audio)])===before;
    r.invalidPreparationRejected=!MediaSource.isTypeSupported('audio/invalid; codecs="not-real"')&&JSON.stringify([ranges(video),ranges(audio)])===before;
    if(mode==='paused-audio'){v.pause();r.pausedBeforeCommit=v.paused;v.currentTime=.25;await event(v,'seeked');r.seekBeforeCommit=v.currentTime;}
    r.wasPlayingAtCommit=!v.paused;r.commitTime=v.currentTime;r.committed=await commit(2);r.sameObjects=video===videoIdentity&&audio===audioIdentity&&v.src===sourceIdentity&&ms.sourceBuffers.length===2;r.afterRanges={video:ranges(video),audio:ranges(audio)};ms.endOfStream();const ended=event(v,'ended');await v.play();await ended;r.eof=true;
    v.currentTime=.5;await event(v,'seeked');observe();r.reverseSeek=v.currentTime;v.currentTime=4.5;await event(v,'seeked');observe();r.forwardSeek=v.currentTime;const pcm=chunks.flatMap(c=>c.pcm);let longest=0,quiet=0;for(let i=0;i+64<=pcm.length;i+=64){let power=0;for(let j=0;j<64;j++)power+=pcm[i+j]**2;quiet=Math.sqrt(power/64)<.005?quiet+64:0;longest=Math.max(longest,quiet);}r.captureAroundBoundary=chunks;r.longestQuietSamples=longest;r.longestQuietMs=longest/48;r.captureSamples=pcm.length;r.fidelityPassed=pcm.length>9600&&longest<=240;
   }catch(e){r.error=String(e);r.mediaError=v.error?.message;}finally{clearInterval(timer);v.pause();v.removeAttribute('src');v.load();v.remove();URL.revokeObjectURL(url);source.disconnect();an.disconnect();worklet.disconnect();gain.disconnect();await ac.close();r.cleanup=true;}return r;
  },{mode,files});result.cases.push(row);await writeFile(out+'/results.json',JSON.stringify(result,null,2)+'\n');
 }
 for(const r of result.cases){assert.ok(!r.error&&r.eof&&r.sameObjects&&r.staleGenerationRejected&&r.invalidPreparationRejected,JSON.stringify(r));assert.ok(r.observed.some(o=>o.time>.2&&o.time<1.5&&Math.abs(o.hz-440)<25&&o.db>-70));if(r.mode.includes('audio'))assert.ok(r.observed.some(o=>o.time>2.5&&o.time<5.5&&Math.abs(o.hz-880)<25&&o.db>-70));if(r.mode==='future-audio')assert.ok(r.wasPlayingAtCommit);if(r.mode==='video-config'){assert.ok(r.observed.some(o=>o.time>2.3&&o.time<3.7&&o.width===320&&Math.abs(o.hz-440)<25));assert.ok(r.observed.some(o=>o.time>4.3&&o.width===160&&Math.abs(o.hz-440)<25));}if(r.mode==='queue')assert.ok(r.observed.some(o=>o.time>2.3&&o.time<3.7&&o.pixel[1]>180&&o.pixel[0]<60));}
 await page.evaluate(()=>player.destroy());result.correctnessPassed=result.cases.every(c=>c.fidelityPassed);result.completed=true;
}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();await writeFile(out+'/results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,cases:result.cases.map(({observed,captureAroundBoundary,...r})=>({...r,observations:observed.length}))},null,2));}
