// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const out=process.argv[2],files={};for(const n of ['red.mp4','green.mp4','blue.mp4','long.mp4','blue-0.bin','long-1.bin'])files[n]=[...fs.readFileSync(out+'/'+n)];
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser,result={scope:'Video-only clean-RAP continuation shared by two histories; deliberately wrong non-RAP continuation.'};
try{const origin=await new Promise((resolve,reject)=>{let t=setTimeout(()=>reject(Error('serve')),10000);server.stdout.on('data',x=>{let m=String(x).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0])}})});browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto(origin+'/web/audio-worklet.js');result.probe=await page.evaluate(async(files)=>{
const bytes=Object.fromEntries(Object.entries(files).map(([k,v])=>[k,new Uint8Array(v)])),owners=[];const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const event=(o,n)=>new Promise((res,rej)=>{let t=setTimeout(()=>end(Error(n+' timeout')),7000);function end(e){clearTimeout(t);o.removeEventListener(n,ok);o.removeEventListener('error',bad);e?rej(e):res()}const ok=()=>end(),bad=()=>end(Error(n+' error'));o.addEventListener(n,ok);o.addEventListener('error',bad)});
async function owner(){const v=document.createElement('video');v.muted=true;v.width=160;v.height=96;document.body.append(v);const ms=new MediaSource(),url=URL.createObjectURL(ms),ready=event(ms,'sourceopen');v.src=url;await ready;const sb=ms.addSourceBuffer('video/mp4; codecs="avc1.42c00a"'),cv=new OffscreenCanvas(160,96),ctx=cv.getContext('2d');let generation=1;
async function append(b,g=generation){if(g!==generation)return false;let e=event(sb,'updateend');sb.appendBuffer(b);await e;return true}
function pixels(){ctx.drawImage(v,0,0);return ctx.getImageData(0,0,160,96).data.slice()}
async function frame(t){let e=event(v,'seeked');v.currentTime=t;await e;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));let p=pixels();return {hash:hex(await crypto.subtle.digest('SHA-256',p)),pixels:[...p]}}
async function play(){let rows=[],pending=[],id;const tick=(now,m)=>{let p=pixels();pending.push(crypto.subtle.digest('SHA-256',p).then(h=>rows.push({time:m.mediaTime,hash:hex(h)})));id=v.requestVideoFrameCallback(tick)};id=v.requestVideoFrameCallback(tick);let ended=event(v,'ended');await v.play();await ended;v.cancelVideoFrameCallback(id);await Promise.all(pending);return rows}
function destroy(){generation++;v.pause();v.removeAttribute('src');v.load();v.remove();URL.revokeObjectURL(url)};const o={v,ms,sb,append,frame,play,destroy,retire(){generation++}};owners.push(o);return o}
try{let references={};for(const name of ['red','green','blue','long']){let o=await owner();await o.append(bytes[name+'.mp4']);o.ms.endOfStream();references[name]=[];for(let i=0;i<(name==='long'?24:12);i++)references[name].push(await o.frame((i+.5)/12));o.destroy()}
let branches=[];for(const name of ['red','green']){let o=await owner();await o.append(bytes[name+'.mp4']);const same=o.sb;o.sb.timestampOffset=1;await o.append(bytes['blue-0.bin']);o.ms.endOfStream();let queried=[];for(let i=0;i<24;i++)queried.push((await o.frame((i+.5)/12)).hash);const expected=[...references[name],...references.blue].map(x=>x.hash);if(JSON.stringify(queried)!==JSON.stringify(expected))throw Error('branch pixels '+name);const backwards=(await o.frame(.5/12)).hash,forwards=(await o.frame(23.5/12)).hash;await o.frame(.5/12);let presented=await o.play();let errors=presented.filter(f=>f.hash!==expected[Math.round(f.time*12)]);if(errors.length)throw Error('continuous pixels '+name);o.retire();let stale=await o.append(bytes['blue-0.bin'],1);branches.push({name,queried,expected,backwards,forwards,presented,errors,sameSourceBuffer:same===o.sb,staleRejected:!stale,eof:o.v.ended});o.destroy()}
let bad=await owner();await bad.append(bytes['green.mp4']);let accepted=true,error=null;try{await bad.append(bytes['long-1.bin']);bad.ms.endOfStream()}catch(e){accepted=false;error=String(e)}let wrong={accepted,error};if(accepted){try{let got=await bad.frame(18.5/12),ref=references.long[18];let diffs=got.pixels.map((v,i)=>Math.abs(v-ref.pixels[i]));wrong={...wrong,gotHash:got.hash,expected:ref.hash,meanRGBA:diffs.reduce((a,b)=>a+b,0)/diffs.length,maxRGBA:Math.max(...diffs),mismatched:got.hash!==ref.hash}}catch(e){wrong.outputError=String(e)}}bad.destroy();return {branches,wrong,references:Object.fromEntries(Object.entries(references).map(([k,v])=>[k,v.map(x=>x.hash)])),cleanup:true}}finally{for(const o of owners)o.destroy()}
},files);assert.ok(result.probe.branches.every(b=>b.sameSourceBuffer&&b.staleRejected&&b.eof&&b.presented.length>=22));assert.ok(!result.probe.wrong.accepted||result.probe.wrong.mismatched||result.probe.wrong.outputError);result.passed=true;result.sharedContinuationSha256=crypto.createHash('sha256').update(Buffer.from(files['blue-0.bin'])).digest('hex');}catch(e){result.error=String(e.stack);process.exitCode=1}finally{await browser?.close();server.kill();fs.writeFileSync(out+'/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,wrong:result.probe?.wrong,error:result.error}));}
