// SPDX-License-Identifier: Apache-2.0
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import ts from 'typescript';import {pathToFileURL} from 'node:url';
const out=process.argv[2],rt=path.join(out,'runtime');const source=fs.readFileSync(path.join(rt,'cea-608-parser.ts'),'utf8');
// Preserve upstream parser operations. Only imports for disabled logging/stringification are adapted.
const adapted=source.replace("import { stringify } from './safe-json-stringify';","const stringify = JSON.stringify;").replace("import { logger } from '../utils/logger';","const logger = {log() {}};");
fs.writeFileSync(path.join(rt,'cea608-runtime.mjs'),ts.transpileModule(adapted,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
const {default:Parser}=await import(pathToFileURL(path.resolve(rt,'cea608-runtime.mjs')));const hash=x=>crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(x)).digest('hex');
const pairs=[[0x14,0x20],[0x14,0x20],[0x14,0x60],[0x4f,0x4c],[0x44,0x20],[0x14,0x2f],[0x14,0x2f], // displayed OLD
[0x14,0x20],[0x14,0x2e],[0x14,0x60],[0x11,0x2f],[0x4e,0x45],[0x57,0x20],[0x14,0x2f],[0x14,0x2f], // hidden NEW, italic underlined, duplicate EOC
[0x14,0x29],[0x14,0x21],[0x21,0x20],[0x14,0x2c],[0x14,0x2c], // paint-on backspace clear
[0x14,0x25],[0x14,0x60],[0x52,0x31],[0x14,0x2d],[0x52,0x32],[0x14,0x2d],[0x14,0x2c]];
const events=pairs.map((bytes,i)=>({time:i/2,bytes}));const sourceId=hash(events),version='hls.js-1.6.13-caption-logical-v1';const names=['displayedMemory','nonDisplayedMemory','lastOutputScreen'];
function screen(s){return {currRow:s.currRow,nrRollUpRows:s.nrRollUpRows,rows:s.rows.map(r=>({pos:r.pos,cueStartTime:r.cueStartTime,currPenState:{...r.currPenState},chars:r.chars.map(c=>({uchar:c.uchar,penState:{...c.penState}}))}))};}
function state(p){return {currentChannel:p.currentChannel,cmdHistory:{...p.cmdHistory},channels:p.channels.slice(1).map(c=>({mode:c.mode,cueStartTime:c.cueStartTime,writeScreen:names.find(n=>c[n]===c.writeScreen),screens:Object.fromEntries(names.map(n=>[n,screen(c[n])]))}))};}
function make(){let cues=[];const handler={reset(){cues.length=0},newCue(a,b,s){cues.push({a,b,screen:screen(s)})},dispatchCue(){}};return {p:new Parser(1,handler,handler),cues};}
function restore(caps,expected={sourceId,service:1}){assert.equal(caps.version,version);assert.equal(caps.sourceId,expected.sourceId);assert.equal(caps.service,expected.service);assert.equal(caps.integrity,hash(caps.state));let owner=make(),p=owner.p,s=caps.state;p.currentChannel=s.currentChannel;p.cmdHistory={...s.cmdHistory};s.channels.forEach((sc,i)=>{const c=p.channels[i+1];c.mode=sc.mode;c.cueStartTime=sc.cueStartTime;for(const n of names){const dst=c[n],src=sc.screens[n];dst.currRow=src.currRow;dst.nrRollUpRows=src.nrRollUpRows;src.rows.forEach((r,j)=>{const d=dst.rows[j];d.pos=r.pos;d.cueStartTime=r.cueStartTime;Object.assign(d.currPenState,r.currPenState);r.chars.forEach((ch,k)=>{d.chars[k].uchar=ch.uchar;Object.assign(d.chars[k].penState,ch.penState)})})}c.writeScreen=c[sc.writeScreen];});return owner;}
function capsule(p,cut){const s=state(p);return {version,sourceId,service:1,cut,state:s,integrity:hash(s)}};
const oracle=make(),observed=[];for(const e of events){oracle.p.addData(e.time,e.bytes);observed.push({state:state(oracle.p),cues:structuredClone(oracle.cues),text:oracle.p.channels[1].displayedMemory.getDisplayText()})}
assert.match(observed[5].text,/OLD/);assert.match(observed[12].text,/OLD/);assert.match(observed[13].text,/NEW/);assert.equal(observed[13].text,observed[14].text);assert.equal(observed[18].text,'');
let cases=[];for(let cut=1;cut<events.length;cut++){let prefix=make();for(const e of events.slice(0,cut))prefix.p.addData(e.time,e.bytes);let caps=JSON.parse(JSON.stringify(capsule(prefix.p,cut))),fresh=restore(caps),n=0;for(let j=cut;j<events.length;j++){let e=events[j];fresh.p.addData(e.time,e.bytes);assert.deepEqual(state(fresh.p),observed[j].state);assert.deepEqual(fresh.cues,observed[j].cues.slice(prefix.cues.length));n++}fresh.p.reset();assert.equal(fresh.p.channels[1].displayedMemory.getDisplayText(),'');cases.push({cut,checks:n,bytes:JSON.stringify(caps).length});if(cut===13)fs.writeFileSync(path.join(out,'hidden-capsule.json'),JSON.stringify(caps));}
let hidden=JSON.parse(fs.readFileSync(path.join(out,'hidden-capsule.json')));let visibleOnly=structuredClone(hidden),empty=make();visibleOnly.state.channels[0].screens.nonDisplayedMemory=screen(empty.p.channels[1].nonDisplayedMemory);visibleOnly.integrity=hash(visibleOnly.state);let wrong=restore(visibleOnly);wrong.p.addData(events[13].time,events[13].bytes);assert.notEqual(wrong.p.channels[1].displayedMemory.getDisplayText(),observed[13].text);
let prefix=make();for(const e of events.slice(0,14))prefix.p.addData(e.time,e.bytes);let repeat=capsule(prefix.p,14);repeat.state.cmdHistory={a:null,b:null};repeat.integrity=hash(repeat.state);let duplicate=restore(repeat);duplicate.p.addData(events[14].time,events[14].bytes);assert.notEqual(duplicate.p.channels[1].displayedMemory.getDisplayText(),observed[14].text);
let rejects=[];for(const [kind,edit] of [['wrong-source',c=>c.sourceId='stale'],['wrong-service',c=>c.service=3],['wrong-version',c=>c.version='future'],['corrupt-hidden-state',c=>c.state.channels[0].mode='MODE_TEXT']]){let c=structuredClone(hidden);edit(c);assert.throws(()=>restore(c));rejects.push(kind)}
fs.writeFileSync(path.join(out,'events.json'),JSON.stringify(events,null,2));fs.writeFileSync(path.join(out,'oracle.json'),JSON.stringify(observed));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({sourceId,upstream:'https://github.com/video-dev/hls.js/tree/v1.6.13',parserSha:hash(source),profile:'Two CEA608 channels; authored channel1 pop-on, hidden styled text, duplicate commands, paint-on, roll-up, clears. Fresh logical state restore, no A/V demux integration.',cases,checks:cases.reduce((n,c)=>n+c.checks,0),controls:{visibleOnlyFails:true,omittedCommandHistoryFails:true,rejects,resetClears:true},oracle:'Uninterrupted independent parser owner plus authored OLD/NEW/clear text assertions; same pinned parser implementation, not independent decoder conformance.',performance:'N/A capability only; full JSON logical capsule is not optimized nor cheaper than replay for this tiny trace.'},null,2));console.log('caption suffix checks passed',cases.length);
