// SPDX-License-Identifier: Apache-2.0
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <libplacebo/log.h>
#include <libplacebo/vulkan.h>
#include <libplacebo/renderer.h>
#include <libplacebo/utils/libav.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"failed %s:%d: %s\n",__FILE__,__LINE__,#x);exit(1);}}while(0)
int main(int argc,char**argv){CHECK(argc==5);int target=atoi(argv[3]),enabled=atoi(argv[4]);AVFormatContext*fmt=NULL;CHECK(avformat_open_input(&fmt,argv[1],NULL,NULL)>=0);CHECK(avformat_find_stream_info(fmt,NULL)>=0);int vi=av_find_best_stream(fmt,AVMEDIA_TYPE_VIDEO,-1,-1,NULL,0);CHECK(vi>=0);const AVCodec*codec=avcodec_find_decoder(fmt->streams[vi]->codecpar->codec_id);AVCodecContext*dc=avcodec_alloc_context3(codec);CHECK(avcodec_parameters_to_context(dc,fmt->streams[vi]->codecpar)>=0);CHECK(avcodec_open2(dc,codec,NULL)>=0);AVPacket*p=av_packet_alloc();AVFrame*f=av_frame_alloc();int n=0,found=0;
while(!found){int eof=av_read_frame(fmt,p)<0;if(eof||p->stream_index==vi){CHECK(avcodec_send_packet(dc,eof?NULL:p)>=0);while(avcodec_receive_frame(dc,f)>=0){if(n++==target){found=1;break;}av_frame_unref(f);}}av_packet_unref(p);if(eof)break;}CHECK(found);
pl_log log=pl_log_create(PL_API_VER,pl_log_params(.log_cb=pl_log_simple,.log_priv=stderr,.log_level=PL_LOG_INFO));pl_vulkan vk=pl_vulkan_create(log,pl_vulkan_params());CHECK(vk);pl_gpu gpu=vk->gpu;pl_renderer rr=pl_renderer_create(log,gpu);CHECK(rr);pl_tex textures[4]={0};struct pl_frame in={0};CHECK(pl_map_avframe_ex(gpu,&in,pl_avframe_params(.frame=f,.tex=textures,.map_dovi=enabled)));CHECK(!enabled||in.repr.dovi);struct pl_dovi_metadata custom;if(enabled==2){custom=*in.repr.dovi;for(int c=0;c<3;c++){memset(&custom.comp[c],0,sizeof(custom.comp[c]));custom.comp[c].num_pivots=2;custom.comp[c].pivots[1]=1;custom.comp[c].poly_coeffs[0][1]=1;}in.repr.dovi=&custom;}
pl_fmt rgba=pl_find_fmt(gpu,PL_FMT_FLOAT,4,32,32,PL_FMT_CAP_RENDERABLE|PL_FMT_CAP_HOST_READABLE);CHECK(rgba);pl_tex dst=pl_tex_create(gpu,pl_tex_params(.w=f->width,.h=f->height,.format=rgba,.renderable=true,.host_readable=true));CHECK(dst);
struct pl_frame out={.num_planes=1,.planes={{.texture=dst,.components=4,.component_mapping={0,1,2,3}}},.repr=pl_color_repr_rgb,.color=in.color};out.color.primaries=PL_COLOR_PRIM_BT_2020;out.color.transfer=PL_COLOR_TRC_PQ;out.repr.alpha=PL_ALPHA_INDEPENDENT;struct pl_render_params params=pl_render_fast_params;params.dither_params=NULL;
CHECK(pl_render_image(rr,&in,&out,&params));size_t count=(size_t)f->width*f->height*4;float*data=malloc(count*sizeof(float));CHECK(data);CHECK(pl_tex_download(gpu,pl_tex_transfer_params(.tex=dst,.ptr=data)));char name[4096];snprintf(name,sizeof(name),"%s.rgba32f",argv[2]);FILE*file=fopen(name,"wb");CHECK(file);CHECK(fwrite(data,sizeof(float),count,file)==count);fclose(file);float lo=INFINITY,hi=-INFINITY;size_t nonfinite=0;for(size_t i=0;i<count;i++){if(!isfinite(data[i]))nonfinite++;else{if(data[i]<lo)lo=data[i];if(data[i]>hi)hi=data[i];}}
snprintf(name,sizeof(name),"%s.json",argv[2]);file=fopen(name,"w");CHECK(file);fprintf(file,"{\"width\":%d,\"height\":%d,\"frame\":%d,\"pts\":%lld,\"mappedDovi\":%s,\"mappedSystem\":%d,\"format\":\"%s\",\"floatMin\":%.9g,\"floatMax\":%.9g,\"nonfinite\":%zu,\"target\":\"fullrange RGB BT2020 PQ, float32, targetHDR matches source, no display\"",f->width,f->height,target,(long long)f->pts,in.repr.dovi?"true":"false",in.repr.sys,rgba->name,lo,hi,nonfinite);
struct pl_color_repr cp=in.repr;float initial=pl_color_repr_normalize(&cp);pl_transform3x3 tr=pl_color_repr_decode(&cp,NULL);fprintf(file,",\"initialTextureNormalization\":%.9g,\"sampleDepth\":%d,\"colorDepth\":%d,\"effectiveNonlinearMatrix\":[",initial,in.repr.bits.sample_depth,in.repr.bits.color_depth);for(int i=0;i<9;i++)fprintf(file,"%s%.9g",i?",":"",tr.mat.m[i/3][i%3]);fprintf(file,"],\"effectiveNonlinearBias\":[%.9g,%.9g,%.9g]",tr.c[0],tr.c[1],tr.c[2]);if(in.repr.dovi){const struct pl_dovi_metadata*d=in.repr.dovi;fprintf(file,",\"nonlinearOffset\":[%.9g,%.9g,%.9g],\"nonlinear\":[",d->nonlinear_offset[0],d->nonlinear_offset[1],d->nonlinear_offset[2]);for(int i=0;i<9;i++)fprintf(file,"%s%.9g",i?",":"",d->nonlinear.m[i/3][i%3]);fprintf(file,"],\"linear\":[");for(int i=0;i<9;i++)fprintf(file,"%s%.9g",i?",":"",d->linear.m[i/3][i%3]);fprintf(file,"],\"components\":[");for(int c=0;c<3;c++){const struct pl_reshape_data*t=&d->comp[c];fprintf(file,"%s{\"pivots\":[",c?",":"");for(int i=0;i<t->num_pivots;i++)fprintf(file,"%s%.9g",i?",":"",t->pivots[i]);fprintf(file,"],\"methods\":[");for(int i=0;i<t->num_pivots-1;i++)fprintf(file,"%s%d",i?",":"",t->method[i]);fprintf(file,"],\"poly\":[");for(int i=0;i<t->num_pivots-1;i++)fprintf(file,"%s[%.9g,%.9g,%.9g]",i?",":"",t->poly_coeffs[i][0],t->poly_coeffs[i][1],t->poly_coeffs[i][2]);fprintf(file,"]}");}fprintf(file,"]");}fprintf(file,"}\n");fclose(file);free(data);pl_unmap_avframe(gpu,&in);for(int i=0;i<4;i++)pl_tex_destroy(gpu,&textures[i]);pl_tex_destroy(gpu,&dst);pl_renderer_destroy(&rr);pl_vulkan_destroy(&vk);pl_log_destroy(&log);av_frame_free(&f);av_packet_free(&p);avcodec_free_context(&dc);avformat_close_input(&fmt);return 0;}
