# SPDX-License-Identifier: Apache-2.0
from pathlib import Path
import subprocess,sys,json
p=Path(sys.argv[1]);p.mkdir(parents=True,exist_ok=False);w,h=128,96;frames=[]
for n in range(3):
 y=bytes(235 if ((x//16+y//16+n)%2 if y>=16 else (n+1)>>(x//32)%4&1) else 16 for y in range(h)for x in range(w));frames.append(y+bytes([128])*(w*h//2))
(p/'source.yuv').write_bytes(b''.join(frames));cmds=[['ffmpeg','-v','error','-f','rawvideo','-pixel_format','yuv420p','-video_size',f'{w}x{h}','-framerate','24','-i',str(p/'source.yuv'),'-c:v','libvpx-vp9','-lossless','1','-deadline','realtime','-cpu-used','8','-g','3','-lag-in-frames','0','-f','ivf','-y',str(p/'source.ivf')],['ffmpeg','-v','error','-i',str(p/'source.ivf'),'-f','rawvideo','-pix_fmt','rgba','-y',str(p/'source.rgba')]]
for cmd in cmds:
 q=subprocess.run(cmd,capture_output=True,text=True);assert q.returncode==0,q.stderr
raw=(p/'source.rgba').read_bytes();assert len(raw)==3*w*h*4;assert all(raw[i]in[0,255]for i in range(len(raw)));inverse=bytes(255-v if i%4!=3 else v for i,v in enumerate(raw));(p/'inverse.rgba').write_bytes(inverse);(p/'prepare-results.json').write_text(json.dumps({'frames':3,'width':w,'height':h,'timestamps':[0,41667,83333],'duration':41667,'commands':cmds},indent=2)+'\n');(p/'plan.json').write_text(json.dumps({'contract':'3actual128x96 lossless VP9 frames distinctvisibleIDs, sourcePTS0/41667/83333. WebCodecs VideoDecoder→WebGPU RGBinversion→canvasVideoFrame withownedPTS/duration→VideoEncoder; compare allfinaldecodedI420 planes+PTS to sameencoder CPUinvert route. IndependenthostsourceRGBA checks CPUconversion; hostdecodes finalIVFs. No captureStream/MediaRecorder realtime assumptions.','correctness':'Exactly3encodedanddecodedoutputs, include lastframe, wrongnoinvert controldiffers; stale sourcegeneration transformedframeclosedbeforeencoderhandoff, freshsurvivor exact; encoder/decoder/frame/GPUowners cleanup.','performance':'9alternating whole3frame jobs including sourceread/decode/copy+CPUinvertorGPUsetup/upload/render/framecreation/nativeencode/flush/finaldecode/hash/teardown. Lower95saving>=10%. Boundedpipelinecapability tested before realtime, no sustained90frame/dropdeadline/hardwareattribution claim.'},indent=2)+'\n')
