# SPDX-License-Identifier: Apache-2.0
import pathlib,json,datetime,importlib.util,shutil,sys
root=pathlib.Path.cwd();perf=pathlib.Path(sys.argv[1]);proof=pathlib.Path(sys.argv[2]);r=json.loads((perf/'result.json').read_text());assert r['passed'] and len(r['trials'])==10
key='R003.coalesce-range-reads-around-useful-media-boundaries';folder=pathlib.Path('research/shared/runs')/(datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%SZ')+'-range-latency-whole-player');folder.mkdir()
for name in ['prepare-latency.py','measure-range-latency.mjs','register-latency.py']:shutil.copyfile(pathlib.Path(__file__).parent/name,folder/name)
result={k:r[k] for k in ['protocol','pairs','medianDeltaPercent','benefitPassed','startedAt','finishedAt']};(folder/'results.json').write_text(json.dumps(result,indent=2)+'\n')
passed=r['benefitPassed'];reason=f"Five alternating complete-player pairs under50ms media-response delay: median startup-plus-three-seek latency delta {r['medianDeltaPercent']:.4f}%; predeclared median10%+allpairs-lower+30%maximumextra-server-read-media-byte gate {'passed' if passed else 'failed'}. "+r['protocol']['scope']+' '+r['protocol']['limits']+' Prior local-only whole-player result remains a valid negative (startup+one-seek median+3.314%); this is a separately declared latency-sensitive workload, not removal of that result.'
art=[]
failed=pathlib.Path('results/head-to-head/policy-player-latency-performance-01')
for base in [failed,perf,proof,folder]:
 for p in sorted(base.rglob('*')):
  if p.is_file():art.append({'path':str(p),'role':'frozen source or complete-player observation','license':'Apache-2.0' if p.suffix in ['.mjs','.py','.swift'] else 'GPL-3.0-or-later' if p.suffix in ['.js','.html'] else 'CC-BY-4.0'})
d={'key':key,'disposition':'pursue' if passed else 'stop_current_profile','evidence_level':'scoped_whole_player_paired_comparison','candidate_executed':True,'reason':reason,'next_action':'Qualify latency-aware bounded coalescing with representative remote source identities, cancellation and bandwidth budgets before production integration; no expected improvement on fast local sources.' if passed else 'Reopen only with a demonstrated latency/bandwidth/workload opportunity beyond the two tested whole-player profiles.','stages':{'correctness':{'status':'passed','basis':'Both exactruntime variants passed markedpicture/audio/seek/EOF/cleanup under the identical50ms media-response-delay server; measured runs assert intendedNative-remux route, progression and cleanup.'},'performance':{'status':'passed' if passed else 'failed','basis':reason}}}
spec={'folder':str(folder),'stage':'latency-sensitive whole-player follow-up','items':[key],'decisions':[d],'artifacts':art,'commands':[' '.join(r['command'])],'analysis':'# Latency-sensitive range coalescing\n\n'+reason+'\n\nThe profile was declared before execution because source definition explicitly predicts a latency-sensitive request-count benefit. Delay applies only to media responses. It is an emulated50ms response latency, not an actualWAN benchmark. The earlier baseline-only fast2x drain attempt produced8droppedframes out of241 and failed its quality gate; that attempt is retained. Before a fresh comparison, the workload was narrowed to normal1x playback and the identical frame-quality gate retained. There is no2x delayed-link qualification. Fixed3seek workload and0.2s targetprogression differ from priorlocalone-seek profile, so percentages must not be directly subtracted.'}
s=importlib.util.spec_from_file_location('record',root/'research/shared/tooling/record-research-stage.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.record(spec)
p=root/'research/items'/key/'item.json';x=json.loads(p.read_text());old=x.get('whole_player_qualification');x['whole_player_qualification']={'status':'measured_lab_benefit' if passed else 'benefit_gate_failed','tier_effect':'Native remux -> Native remux','production_admission_changed':False,'evidence':str(folder/'run.json'),'protocol':r['protocol'],'median_delta_percent':r['medianDeltaPercent'],'benefit_passed':passed,'prior_local_profile':old};p.write_text(json.dumps(x,indent=2)+'\n');print(folder)
