# SPDX-License-Identifier: Apache-2.0
from pathlib import Path
import json,statistics,random,sys,time
out=Path(sys.argv[1]);source=Path('research/items/R126.find-where-hardware-decoding-loses-on-short-jobs/evidence/20260919T212248Z-short-jobs/results.json')
plan={'declared_before_analysis':True,'scope':'Revalidate existing packet-byte affine latency predictor against constantmean using9newactual72frame serialized decoder traces perhint. This is a cheap predictor prerequisite, not a bufferingcontroller or deadline experiment. Existing source says actualpresentationdeadlines are ultimatelyrequired; do not claim controller correctness from this analysis.','split':'Each independentowner learnsframes1..47, holdsout48..71. Same47/24split andclamp0 as historicalcandidate; no fitting onheldoutframes. Separate Vpx/software andVideoToolbox/platform hint profiles, no blending.','gate':'Atleast10%aggregateheldoutMAE reduction with paired95bootstraplower>=10%,10000owner resamplesseed1251/1252, beforeimplementing controller. Calibration47frames+modelcomputation areadditionalcost, not free; computeoverhead reported separately diagnostic, not throughputclaim.','stop':'If simple currentpredictor fails prerequisite, stopthatvariant withoutbuilding controller; latercontrollercorrectness/performanceN/A for rejectedpredictor. Doesnotruleout richer structure-awaremodels.'};(out/'plan.json').write_text(json.dumps(plan,indent=2)+'\n');data=json.loads(source.read_text());profile=next(x for x in data['profiles'] if x['count']==72);result={}
for backend,seed in [('baseline',1251),('candidate',1252)]:
 rows=[]
 for pair in profile['pairs']:
  trace=pair[backend]['rows'];assert all(x['exact'] and x['timestampExact'] for x in trace);train=trace[1:48];test=trace[48:];start=time.perf_counter_ns();xm=statistics.mean(x['packetBytes'] for x in train);ym=statistics.mean(x['latencyMs'] for x in train);den=sum((x['packetBytes']-xm)**2 for x in train);slope=sum((x['packetBytes']-xm)*(x['latencyMs']-ym) for x in train)/den;pred=[max(0,ym+slope*(x['packetBytes']-xm)) for x in test];calc=time.perf_counter_ns()-start;const=statistics.mean(abs(x['latencyMs']-ym) for x in test);affine=statistics.mean(abs(x['latencyMs']-p) for x,p in zip(test,pred));rows.append({'pair':pair['pair'],'constant_mae_ms':const,'affine_mae_ms':affine,'slope_ms_per_byte':slope,'intercept_ms':ym-slope*xm,'training_frames':47,'heldout_frames':24,'training_decode_ms':sum(x['latencyMs'] for x in train),'fit_and24predict_us':calc/1000})
 r=random.Random(seed);boot=[]
 for _ in range(10000):
  ids=[r.randrange(9) for _ in range(9)];boot.append(100*(1-sum(rows[i]['affine_mae_ms'] for i in ids)/sum(rows[i]['constant_mae_ms'] for i in ids)))
 boot.sort();b=sum(x['constant_mae_ms'] for x in rows);c=sum(x['affine_mae_ms'] for x in rows);result[backend]={'rows':rows,'aggregate_mae_saving_percent':100*(1-c/b),'bootstrap95':[boot[250],boot[9749]],'gate_passed':boot[250]>=10,'mean_fit_predict_us':statistics.mean(x['fit_and24predict_us'] for x in rows),'source':str(source),'new_media_execution':False,'scope':'Analysis of actualfreshtraces, not new decode or controller experiment'}
(out/'results.json').write_text(json.dumps(result,indent=2)+'\n');(out/'commands.log').write_text('python3 research/items/R125.buffer-according-to-predicted-decode-work/tests/predictor-validation.py '+str(out)+'\n');print(json.dumps({k:{a:b for a,b in v.items() if a!='rows'} for k,v in result.items()},indent=2))
