// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const out=process.argv[2],files={};for(const n of ['source.mp4','candidate.mp4'])files[n]=[...fs.readFileSync(out+'/'+n)];
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser,result={scope:'Actual I_PCM P1seed as hidden preroll plus copied reference-repaired P2..23 suffix.'};
try{const origin=await new Promise((resolve,reject)=>{let t=setTimeout(()=>reject(Error('serve')),10000);server.stdout.on('data',x=>{let m=String(x).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0])}})});browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto(origin+'/web/audio-worklet.js');result.probe=await page.evaluate(async(files)=>{
const bytes=Object.fromEntries(Object.entries(files).map(([k,v])=>[k,new Uint8Array(v)])),owners=[];const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const event=(o,n)=>new Promise((res,rej)=>{let t=setTimeout(()=>end(Error(n+' timeout')),7000);function end(e){clearTimeout(t);o.removeEventListener(n,ok);o.removeEventListener('error',bad);e?rej(e):res()}const ok=()=>end(),bad=()=>end(Error(n+' error'));o.addEventListener(n,ok);o.addEventListener('error',bad)});
async function owner(){const v=document.createElement('video');v.muted=true;v.width=160;v.height=96;v.style.visibility="hidden";document.body.append(v);const ms=new MediaSource(),url=URL.createObjectURL(ms),ready=event(ms,'sourceopen');v.src=url;await ready;const sb=ms.addSourceBuffer('video/mp4; codecs="avc1.42c00a"'),cv=new OffscreenCanvas(160,96),ctx=cv.getContext('2d');let generation=1;
async function append(b,g=generation){if(g!==generation)return false;let e=event(sb,'updateend');sb.appendBuffer(b);await e;return true}
function pixels(){ctx.drawImage(v,0,0);return ctx.getImageData(0,0,160,96).data.slice()}
async function frame(t){let e=event(v,'seeked');v.currentTime=t;await e;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));let p=pixels();return {hash:hex(await crypto.subtle.digest('SHA-256',p)),pixels:[...p]}}
async function play(){let rows=[],pending=[],id;const tick=(now,m)=>{let p=pixels();pending.push(crypto.subtle.digest('SHA-256',p).then(h=>rows.push({time:m.mediaTime,hash:hex(h)})));id=v.requestVideoFrameCallback(tick)};id=v.requestVideoFrameCallback(tick);let ended=event(v,'ended');await v.play();await ended;v.cancelVideoFrameCallback(id);await Promise.all(pending);return rows}
function destroy(){generation++;v.pause();v.removeAttribute('src');v.load();v.remove();URL.revokeObjectURL(url)};const o={v,ms,sb,append,frame,play,destroy,retire(){generation++}};owners.push(o);return o}
try{let ref=await owner();await ref.append(bytes['source.mp4']);ref.ms.endOfStream();let references=[];for(let i=0;i<24;i++)references.push((await ref.frame((i+.5)/24)).hash);ref.destroy();let o=await owner();await o.append(bytes['candidate.mp4']);o.ms.endOfStream();const seed=(await o.frame(.5/24)).hash;if(seed!==references[1])throw Error('seed native mismatch');let queried=[];for(let i=0;i<22;i++)queried.push((await o.frame((i+1.5)/24)).hash);const expected=references.slice(2),errors=queried.flatMap((h,i)=>h===expected[i]?[]:[i]);if(errors.length)throw Error('query mismatch '+errors);const backwards=(await o.frame(1.5/24)).hash,forwards=(await o.frame(22.5/24)).hash;await o.frame(1.5/24);o.v.style.visibility='visible';const presented=await o.play();const presentationErrors=presented.filter(f=>f.hash!==references[Math.round(f.time*24)+1]);if(presentationErrors.length)throw Error('presented mismatch '+JSON.stringify(presentationErrors));o.retire();const stale=await o.append(bytes['candidate.mp4'],1);return {references,seed,queried,errors,backwards,forwards,presented,presentationErrors,staleRejected:!stale,eof:o.v.ended,seedHiddenUntilWantedFrame:true,cleanup:true}}finally{for(const o of owners)o.destroy()}
},files);assert.ok(result.probe.staleRejected&&result.probe.eof);assert.ok(result.probe.presented.length>=20);result.passed=true;}catch(e){result.error=String(e.stack);process.exitCode=1}finally{await browser?.close();server.kill();fs.writeFileSync(out+'/browser-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,wrong:result.probe?.wrong,error:result.error}));}
