// SPDX-License-Identifier: Apache-2.0
import fs from'node:fs';import http from'node:http';import path from'node:path';import {chromium}from'playwright';
const dir=path.resolve(process.argv[2]),tool=path.resolve('research/items/R081.definition-not-recovered/tests'),results={};const server=http.createServer((req,res)=>{try{const name=path.basename(new URL(req.url,'http://local').pathname);if(name.endsWith('.mjs')){res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync(path.join(tool,name)));}else res.end('<!doctype html>');}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({channel:'chrome',headless:true});results.browser=browser.version();const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);for(const size of[256,512]){
 const data={compressed:fs.readFileSync(dir+'/'+size+'/dc-ip.m2v').toString('base64'),reference:fs.readFileSync(dir+'/'+size+'/reference.yuv').toString('base64')};
 results[size]=await page.evaluate(async data=>{
  const{parseCompressed,reconstructCPU}=await import('/scaled-codec.mjs'),{createGPUOwner}=await import('/scaled-gpu.mjs'),source=Uint8Array.from(atob(data.compressed),c=>c.charCodeAt(0)),reference=Uint8Array.from(atob(data.reference),c=>c.charCodeAt(0)),s=parseCompressed(source),assert=(v,m)=>{if(!v)throw Error(m)},eq=(a,b)=>a.length===b.length&&a.every((v,i)=>v===b[i]),last=reference.subarray(32*s.N),fullCPU=reconstructCPU(s,true),control=await createGPUOwner(s.W,s.H),fullGPU=await control.execute(s,true);
  const exact=fullGPU.frames.map((f,i)=>eq(f,reference.subarray(i*s.N,(i+1)*s.N)));assert(exact.every(Boolean)&&fullCPU.frames.every((f,i)=>eq(f,reference.subarray(i*s.N,(i+1)*s.N))),'full picture oracle');assert(!eq((await control.execute(s,false,true)).output,last),'wrong DC sensitivity');const wrongMotion={...s,pictures:s.pictures.map(p=>({...p,vectors:p.vectors.map(v=>[v[0],v[1],0,0])}))};assert(!eq((await control.execute(wrongMotion)).output,last),'wrong motion sensitivity');assert(eq((await control.execute(s)).output,last),'state restoration');let mismatch=false;try{await control.execute({...s,W:s.W+16})}catch{mismatch=true}assert(mismatch,'source change rejection');control.close();let closed=false;try{await control.execute(s)}catch{closed=true}assert(closed,'closed owner');
  const cold=[];for(let pair=0;pair<11;pair++){const r={pair};for(const mode of pair%2?['gpu','cpu']:['cpu','gpu']){const begin=performance.now(),syntax=parseCompressed(source);let out;if(mode==='cpu')out=reconstructCPU(syntax).output;else{const owner=await createGPUOwner(s.W,s.H);try{out=(await owner.execute(syntax)).output;}finally{owner.close();}}r[mode+'Ms']=performance.now()-begin;assert(eq(out,last),'cold output');}cold.push(r);}
  let begin=performance.now();const cpuOwner={a:new Uint8Array(s.N),b:new Uint8Array(s.N)};const cpuSetupMs=performance.now()-begin;begin=performance.now();const owner=await createGPUOwner(s.W,s.H),gpuSetupMs=performance.now()-begin,warm=[];
  for(let pair=0;pair<11;pair++){const r={pair};for(const mode of pair%2?['gpu','cpu']:['cpu','gpu']){const start=performance.now(),syntax=parseCompressed(source),out=mode==='cpu'?reconstructCPU(syntax,false,cpuOwner).output:(await owner.execute(syntax)).output;r[mode+'Ms']=performance.now()-start;assert(eq(out,last),'persistent output');}warm.push(r);}
  const gpuBytes=owner.retainedGPUBytes,adapter=owner.adapter;begin=performance.now();owner.close();const gpuTeardownMs=performance.now()-begin;begin=performance.now();cpuOwner.a=cpuOwner.b=null;const cpuTeardownMs=performance.now()-begin;
  return{width:s.W,pictures:33,parsedDCBlocks:s.coeff.length,parsedPredictionMacroblocks:s.M*s.M*32,allPicturesExact:exact,wrongDCDiffers:true,wrongMotionDiffers:true,stateRecoveryExact:true,sourceMismatchRejected:mismatch,closedOwnerRejected:closed,cold,warm,cpuSetupMs,gpuSetupMs,cpuTeardownMs,gpuTeardownMs,retainedGPUBytes:gpuBytes,retainedCPUBytes:s.N*2,adapter,allTimedOutputsExact:true};
 },data);fs.writeFileSync(dir+'/browser-results.json',JSON.stringify(results,null,2));}results.passed=true;
}catch(e){results.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();await new Promise(r=>server.close(r));fs.writeFileSync(dir+'/browser-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify({passed:results.passed,error:results.error}));}
