// SPDX-License-Identifier: Apache-2.0
// Dimension-parameterized actual DC inverse + resident predictive MPEG2 reconstruction.
export async function createGPUOwner(W,H){
 const adapter=await navigator.gpu?.requestAdapter();if(!adapter)throw Error('WebGPU adapter unavailable');const d=await adapter.requestDevice(),buffers=[],N=W*H*3/2,M=W/16,uv=W*H/4,dcY=W*H/64,dcUV=dcY/4;
 function buffer(size,usage,data){const b=d.createBuffer({size,usage});buffers.push(b);if(data)d.queue.writeBuffer(b,0,data);return b;}
 const errors=[];d.addEventListener('uncapturederror',e=>errors.push(String(e.error)));
 const init=`@group(0) @binding(0) var<storage,read> c:array<i32>;@group(0) @binding(1) var<storage,read_write> dst:array<u32>;@compute @workgroup_size(64) fn main(@builtin(global_invocation_id) gid:vec3u){let i=gid.x;if(i>=${N}u){return;}var local=i;var w=${W}u;var off=0u;if(i>=${W*H}u){w=${W/2}u;local=(i-${W*H}u)%${uv}u;off=${dcY}u+((i-${W*H}u)/${uv}u)*${dcUV}u;}let x=local%w;let y=local/w;let block=off+(y/8u)*(w/8u)+x/8u;dst[i]=u32(c[block]/8);}`;
 const pred=`@group(0) @binding(0) var<storage,read> src:array<u32>;@group(0) @binding(1) var<storage,read_write> dst:array<u32>;@group(0) @binding(2) var<storage,read> mv:array<i32>;@group(0) @binding(3) var<uniform> frame:vec4u;@compute @workgroup_size(64) fn main(@builtin(global_invocation_id) gid:vec3u){let i=gid.x;if(i>=${N}u){return;}var local=i;var w=${W}u;var off=0u;var block=16u;var scale=2;if(i>=${W*H}u){w=${W/2}u;local=(i-${W*H}u)%${uv}u;off=${W*H}u+((i-${W*H}u)/${uv}u)*${uv}u;block=8u;scale=4;}let x=local%w;let y=local/w;let m=(frame.x*${M*M}u+(y/block)*${M}u+x/block)*2u;let sx=i32(x)+mv[m]/scale;let sy=i32(y)+mv[m+1u]/scale;dst[i]=src[off+u32(sy)*w+u32(sx)];}`;
 const cb=buffer((dcY+2*dcUV)*4,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST),mb=buffer(32*M*M*2*4,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST),a=buffer(N*4,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC),b=buffer(N*4,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC),rb=buffer(N*4,GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST),params=Array.from({length:32},(_,f)=>buffer(16,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST,new Uint32Array([f,0,0,0])));
 const ip=await d.createComputePipelineAsync({layout:'auto',compute:{module:d.createShaderModule({code:init}),entryPoint:'main'}}),pp=await d.createComputePipelineAsync({layout:'auto',compute:{module:d.createShaderModule({code:pred}),entryPoint:'main'}});
 function group(pipe,bs){return d.createBindGroup({layout:pipe.getBindGroupLayout(0),entries:bs.map((b,binding)=>({binding,resource:{buffer:b}}))});}
 const ig=group(ip,[cb,a]),pg=params.map((p,f)=>group(pp,[f%2?b:a,f%2?a:b,mb,p]));let closed=false;
 async function execute(s,capture=false,wrong=false){if(closed)throw Error('closed owner');if(s.W!==W||s.H!==H||s.pictures.length!==32)throw Error('source dimensions');d.queue.writeBuffer(cb,0,wrong?new Int32Array(s.coeff.length):s.coeff);const motions=new Int32Array(32*M*M*2);let mi=0;for(const p of s.pictures)for(const v of p.vectors){motions[mi++]=v[2];motions[mi++]=v[3];}if(motions.some(v=>v%4))throw Error('fractional chroma');d.queue.writeBuffer(mb,0,motions);let enc=d.createCommandEncoder();const frames=[];
  function dispatch(pipe,g){const p=enc.beginComputePass();p.setPipeline(pipe);p.setBindGroup(0,g);p.dispatchWorkgroups(Math.ceil(N/64));p.end();}
  async function read(src){enc.copyBufferToBuffer(src,0,rb,0,N*4);d.queue.submit([enc.finish()]);await rb.mapAsync(GPUMapMode.READ);const output=Uint8Array.from(new Uint32Array(rb.getMappedRange()));rb.unmap();enc=d.createCommandEncoder();return output;}
  dispatch(ip,ig);if(capture)frames.push(await read(a));for(let f=0;f<32;f++){dispatch(pp,pg[f]);if(capture)frames.push(await read(f%2?a:b));}const output=capture?frames.at(-1):await read(a);if(errors.length)throw Error(errors.join(','));return{output,frames};
 }
 return{execute,close(){if(!closed){buffers.forEach(b=>b.destroy());d.destroy();closed=true;}},retainedGPUBytes:buffers.reduce((n,b)=>n+b.size,0),adapter:{vendor:adapter.info.vendor,architecture:adapter.info.architecture,description:adapter.info.description}};
}
