// SPDX-License-Identifier: Apache-2.0
import {webkit} from 'playwright';import {spawn} from 'node:child_process';import {readFile,writeFile} from 'node:fs/promises';
const root='research/shared/runs/20260919T200500Z-managed',b=await readFile(root+'/source.mp4'),parts=[];let start=0;for(let p=0;p<b.length;){const n=b.readUInt32BE(p),type=b.toString('ascii',p+4,p+8);if(!n||p+n>b.length)throw Error('box');if(type==='moof'){parts.push([...b.subarray(start,p)]);start=p;}p+=n;}parts.push([...b.subarray(start)]);const input={init:parts.shift(),fragments:parts},result={scope:'Real WebKit ManagedMediaSource demand signals controlling prepared-fragment production; host prepared video only, not integrated demux/remux or A/V lifecycle.'};let browser;const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});
try{const origin=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('server')),10000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});});browser=await webkit.launch({headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto(origin+'/examples/custom-controls.html');result.probe=await page.evaluate(async input=>{
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),video=document.createElement('video');video.muted=true;video.disableRemotePlayback=true;video.playsInline=true;document.body.append(video);const ms=new ManagedMediaSource(),url=URL.createObjectURL(ms),events=[],counts={produced:0,bufferedChanges:0},errors=[];let nextIndex=0,sb,init=false,closed=false,busy=false,pending;const once=(o,n)=>new Promise((r,j)=>{o.addEventListener(n,r,{once:true});o.addEventListener('error',()=>j(Error(n+' error')),{once:true});});
async function append(bytes){const done=once(sb,'updateend');sb.appendBuffer(new Uint8Array(bytes));await done;}
async function pump(){if(busy||closed||!sb||!init)return;busy=true;try{while(ms.streaming&&!closed&&nextIndex<input.fragments.length){await append(input.fragments[nextIndex++]);counts.produced++;await sleep(100);}}catch(e){errors.push(String(e));}finally{busy=false;}}
ms.addEventListener('startstreaming',()=>{events.push({type:'start',produced:counts.produced,t:video.currentTime});pending=pump();});ms.addEventListener('endstreaming',()=>events.push({type:'end',produced:counts.produced,t:video.currentTime}));
try{const opened=once(ms,'sourceopen');video.src=url;await opened;sb=ms.addSourceBuffer('video/mp4; codecs="avc1.42c00b"');sb.addEventListener('bufferedchange',e=>{counts.bufferedChanges++;});await append(input.init);ms.duration=90;init=true;pending=pump();await video.play();await sleep(7000);const stopped=events.find(e=>e.type==='end');const atStop=counts.produced;await sleep(250);const stable=counts.produced===atStop&&!ms.streaming;const before={time:video.currentTime,produced:counts.produced,streaming:ms.streaming,buffered:sb.buffered.length?[sb.buffered.start(0),sb.buffered.end(0)]:[]};nextIndex=75;video.currentTime=75;await sleep(6000);return {events,counts,stoppedProduction:!!stopped&&stable,before,after:{time:video.currentTime,produced:counts.produced,streaming:ms.streaming,readyState:video.readyState},errors,actualFrames:video.getVideoPlaybackQuality?.().totalVideoFrames,cleanup:true};}finally{closed=true;await pending;video.pause();video.removeAttribute('src');video.load();video.remove();URL.revokeObjectURL(url);}
},input);await page.evaluate(()=>player.destroy());result.completed=true;}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();await writeFile(root+'/result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));}
