# SPDX-License-Identifier: Apache-2.0
import pathlib,subprocess,json,sys,time,hashlib
out=pathlib.Path(sys.argv[1]);out.mkdir(parents=True,exist_ok=True);commands=[]
def run(args):
 commands.append(['ffmpeg',*args]);return subprocess.check_output(['ffmpeg','-v','error','-nostdin','-y',*args],timeout=30)
def decode(p,kind):return run(['-i',str(p),'-map','0:'+kind+':0',*(['-pix_fmt','yuv420p','-fps_mode','passthrough','-f','rawvideo'] if kind=='v' else ['-f','f32le']),'-'])
def facts(p):
 d=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_streams','-show_format','-show_packets','-show_data_hash','sha256','-of','json',str(p)]));return {'streams':[{k:s.get(k) for k in ['codec_type','codec_name','width','height','pix_fmt','sample_rate','channels','channel_layout','extradata_hash']} for s in d['streams']],'packets':[{k:p.get(k) for k in ['stream_index','data_hash','pts_time','dts_time','duration_time','side_data_list']} for p in d['packets']]}
source=out/'source.mp4';run(['-f','lavfi','-i','testsrc2=size=160x96:rate=24:duration=6','-f','lavfi','-i','sine=frequency=523:sample_rate=48000:duration=6','-c:v','libx264','-preset','fast','-g','24','-bf','2','-pix_fmt','yuv420p','-c:a','aac','-b:a','96k',str(source)])
plan={'scope':'Bounded offline search, two vetted packet-copy MP4 recipes (faststart and fragmented); explicit AVC/AAC finite source. Full host video/audio and packet timestamps/side-data plus configuration must remain exact. Wrong missing-audio recipe must reject. Actual native destination tested for admitted recipe. Original playback remains fallback.','gate':'Select only output-equivalent recipe within 2-candidate search budget. Complete cold search+chosen native startup/seek compared with direct source owner,5 alternating pairs; pursue cost only if median complete task improves5percent. Repeated-use preparation amortization not assumed.'};(out/'plan.json').write_text(json.dumps(plan,indent=2))
t=time.perf_counter();oracle={'v':decode(source,'v'),'a':decode(source,'a')};original=facts(source);rows=[]
for name,flags in [('faststart','+faststart'),('fragmented','+frag_keyframe+empty_moov+default_base_moof')]:
 p=out/(name+'.mp4');start=time.perf_counter();run(['-i',str(source),'-map','0','-c','copy','-movflags',flags,str(p)]);f=facts(p);raw={k:decode(p,k) for k in oracle};rows.append({'name':name,'bytes':p.stat().st_size,'ms':(time.perf_counter()-start)*1000,'videoExact':raw['v']==oracle['v'],'audioExact':raw['a']==oracle['a'],'configurationExact':f['streams']==original['streams'],'packetsExact':f['packets']==original['packets'],'decodedBytes':{k:len(v) for k,v in raw.items()},'admitted':raw==oracle and f==original})
search_ms=(time.perf_counter()-t)*1000
wrong=out/'wrong-no-audio.mp4';run(['-i',str(source),'-map','0:v','-c','copy',str(wrong)]);wrongRejected=facts(wrong)['streams']!=original['streams'];assert wrongRejected
eligible=[r for r in rows if r['admitted']];assert eligible;chosen=min(eligible,key=lambda r:r['bytes'])['name'];result={'plan':plan,'rows':rows,'chosen':chosen,'searchMs':search_ms,'wrongMissingAudioRejected':wrongRejected,'oracleBytes':{k:len(v) for k,v in oracle.items()},'oracleSHA256':{k:hashlib.sha256(v).hexdigest() for k,v in oracle.items()},'passed':True};(out/'result.json').write_text(json.dumps(result,indent=2)+'\n');(out/'commands.json').write_text(json.dumps(commands,indent=2)+'\n');print(json.dumps(result))
