export const styles = `
:host{display:block;contain:layout;container-type:inline-size;container-name:player;--webmpv-background:#101114;--webmpv-foreground:#f6f3ed;--webmpv-accent:#f3ead8;--webmpv-border:#ffffff24;--webmpv-radius:14px;color:var(--webmpv-foreground);font:14px/1.5 system-ui,sans-serif;color-scheme:dark}
*{box-sizing:border-box}[hidden]{display:none!important}button,input,select{font:inherit;color:inherit}button,select{cursor:pointer}button{min-height:44px;border:1px solid var(--webmpv-border);border-radius:8px;background:#ffffff08;padding:8px 14px}button:hover{background:#ffffff18}button:disabled,input:disabled,select:disabled{opacity:.4;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible,[tabindex]:focus-visible{outline:2px solid var(--webmpv-accent);outline-offset:4px}input[type=file]{width:100%;min-width:0;font-size:12px}input[type=range]{accent-color:var(--webmpv-accent);cursor:pointer;margin:0;min-height:32px}
.shell{position:relative;isolation:isolate;background:var(--webmpv-background);border:1px solid var(--webmpv-border);border-radius:var(--webmpv-radius);overflow:clip}.stage{position:relative;width:100%;min-width:0;display:grid;place-items:center;background:#08090c;min-height:240px;aspect-ratio:var(--media-aspect,16/9);max-height:80vh;overflow:hidden}.surface,.poster{position:absolute;inset:0;width:100%;height:100%;display:grid;place-items:center}.surface .webmpv-player{width:100%;height:100%;display:grid;place-items:center}.surface video,.surface canvas,.poster{width:100%;height:100%;max-width:100%;max-height:100%;object-fit:contain}
.topbar{position:absolute;inset:0 0 auto;z-index:2;display:flex;align-items:center;gap:6px;padding:clamp(8px,1.3cqw,16px) clamp(12px,2.2cqw,26px) 24px;background:linear-gradient(#0008,transparent);pointer-events:none}.topbar>*{pointer-events:auto}.player-title{font-size:clamp(12px,1.3cqw,15px);font-weight:450;letter-spacing:.1px}.space{flex:1}.icon-button{display:inline-grid;place-items:center;flex:0 0 36px;width:36px;height:36px;min-width:36px;min-height:36px;padding:8px;border:0;border-radius:50%;background:transparent;transition:background .15s,transform .15s}.icon-button:hover{background:#ffffff15}.icon-button svg{width:20px;height:20px;display:block;pointer-events:none;filter:drop-shadow(0 1px 4px #0008)}.icon-button[aria-expanded=true],.icon-button[aria-pressed=true]{color:var(--webmpv-accent);background:#ffffff12}
.transport{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:2;display:flex;align-items:center;gap:clamp(16px,3cqw,36px)}.transport .play{width:clamp(56px,8cqw,88px);height:clamp(56px,8cqw,88px);flex-basis:clamp(56px,8cqw,88px);border:0;border-radius:8px;background:transparent;backdrop-filter:none}.transport .icon-button:hover{background:transparent;transform:scale(1.06)}.transport .play svg{width:clamp(44px,6.5cqw,72px);height:clamp(44px,6.5cqw,72px)}.transport #back,.transport #forward{width:60px;height:60px;flex-basis:60px;padding:10px}.transport #back svg,.transport #forward svg{width:clamp(28px,3cqw,36px);height:clamp(28px,3cqw,36px);stroke-width:1.5}
.controls{position:absolute;z-index:2;inset:auto 0 0;padding:20px clamp(12px,2.3cqw,28px) clamp(8px,1.2cqw,14px);background:linear-gradient(transparent,#0009);pointer-events:none}.controls>*{pointer-events:auto}.row{display:flex;align-items:center;gap:4px;margin-bottom:0}.volume{width:clamp(42px,5cqw,60px)}.times{display:flex;justify-content:space-between;gap:20px}.time{font-size:clamp(10px,1.1cqw,12px);font-variant-numeric:tabular-nums;text-shadow:0 1px 4px #0008}.timeline{width:100%;display:block;appearance:none;background:transparent;padding:0;height:28px;--progress:0%}.timeline::-webkit-slider-runnable-track{height:3px;border-radius:3px;background:linear-gradient(to right,var(--webmpv-foreground) var(--progress),#ffffff42 var(--progress))}.timeline::-webkit-slider-thumb{appearance:none;width:12px;height:12px;border-radius:50%;background:var(--webmpv-accent);margin-top:-4.5px}.timeline::-moz-range-track{height:3px;background:#ffffff42;border-radius:3px}.timeline::-moz-range-progress{height:3px;background:var(--webmpv-foreground)}.timeline::-moz-range-thumb{width:12px;height:12px;border:0;border-radius:50%;background:var(--webmpv-accent)}
.settings{position:absolute;z-index:4;right:clamp(12px,2.2cqw,26px);bottom:106px;width:260px;max-width:calc(100% - 24px);max-height:calc(100% - 124px);padding:6px 14px 10px;font-size:12px;background:#151619;border:1px solid #ffffff14;border-radius:10px;box-shadow:0 16px 40px #0007;color:#e5e5e7;overflow:auto}.settings header{display:flex;align-items:center;justify-content:space-between;gap:8px;position:sticky;top:-6px;background:#151619;border-radius:0;border-bottom:1px solid #ffffff0c;z-index:1}.settings header strong{font-size:12px;font-weight:550;letter-spacing:.1px}.settings header .icon-button{margin-right:-10px}.settings label{display:grid;gap:8px;margin:12px 0}.settings .setting-row{display:flex;align-items:center;justify-content:space-between;gap:14px;min-height:44px;margin:0;border-bottom:1px solid #ffffff08}.setting-row span{flex-shrink:0}.settings select{color:#b9bac0;min-height:44px;width:100%;min-width:0;border:0;border-radius:5px;background:transparent;padding:8px}.setting-row select{width:auto;max-width:60%;text-align:right;text-overflow:ellipsis}.more-options{margin-top:12px}.more-options summary{font-size:12px;color:#a5a6ad;cursor:pointer;padding:6px 0}.settings .subtitle-picker{font-size:12px;color:#a5a6ad;padding-top:6px}.settings input[type=url]{width:100%;min-width:0;background:#0e0f11;border:1px solid #ffffff12;border-radius:6px;padding:10px}.settings .check{display:flex;align-items:center;gap:8px}.source-menu{top:76px;bottom:auto;max-height:calc(100% - 100px);width:320px}.settings form{border-top:1px solid #ffffff18;margin-top:18px;padding-top:4px}.help{font-size:11px;color:#999792;line-height:1.7;margin:14px 0 0}
.notice{position:absolute;z-index:5;top:78px;left:20px;right:20px;display:flex;align-items:center;gap:12px;padding:12px 16px;background:#301d2af5;border:1px solid #805466;border-radius:10px;overflow-wrap:anywhere}.notice span{flex:1}.status{position:absolute;z-index:2;bottom:132px;left:24px;max-width:calc(100% - 48px);padding:6px 10px;background:#15131ddd;border-radius:6px;font-size:12px;pointer-events:none}.status:empty{display:none}.busy{position:absolute;top:80px;left:26px;z-index:2;padding:6px 12px;background:#141414bb;border-radius:20px;font-size:12px}
.empty{position:relative;text-align:center;max-width:100%;padding:80px 24px}.empty strong{display:block;font-size:25px;font-weight:450;letter-spacing:-.5px}.empty p{color:#a6a29b;margin:8px 0 24px}.emblem{display:grid;place-items:center;width:80px;height:80px;margin:0 auto 24px;border:1px solid #ffffff60;border-radius:50%;font-size:32px}.empty button{background:var(--webmpv-foreground);color:#171719;border:0;padding:10px 24px}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
.topbar,.controls,.transport{transition:opacity .22s}.idle .topbar,.idle .controls,.idle .transport{opacity:0;pointer-events:none}.idle .topbar *,.idle .controls *,.idle .transport *{pointer-events:none}.idle{cursor:none}.shell:not(.idle):has(:focus-visible) .topbar,.shell:not(.idle):has(:focus-visible) .controls,.shell:not(.idle):has(:focus-visible) .transport{opacity:1}.shell:not(.idle):has(:focus-visible) .topbar *,.shell:not(.idle):has(:focus-visible) .controls *,.shell:not(.idle):has(:focus-visible) .transport *{pointer-events:auto}
:host(:fullscreen){background:#08090c;width:100%;height:100%}:host(:fullscreen) .shell{height:100%;border:0;border-radius:0}:host(:fullscreen) .stage{height:100%;width:100%;max-height:none;min-height:0;aspect-ratio:auto}
@container player (max-width:600px){.stage{min-height:240px;max-height:none}.topbar{padding:6px 10px 18px}.controls{padding:12px 12px 8px}.settings{right:10px;bottom:94px;max-height:calc(100% - 108px);width:240px}.source-menu{top:50px;bottom:auto;max-height:calc(100% - 62px)}.menu-open .transport{opacity:0;visibility:hidden}.empty{padding:48px 16px}.empty strong{font-size:18px}.empty p{font-size:12px;margin:6px 0 12px}.emblem{width:44px;height:44px;font-size:23px;margin-bottom:12px}.status{bottom:100px;left:12px}.busy{top:50px;left:12px}.volume{width:42px}}
@media(pointer:coarse){.icon-button{width:44px;height:44px;min-width:44px;min-height:44px;flex-basis:44px}.settings{bottom:114px;max-height:calc(100% - 126px)}.source-menu{bottom:auto;max-height:calc(100% - 80px)}}
.settings button,.empty button{background:#25262b;color:#eeeef0;border:1px solid #ffffff16;border-radius:7px;box-shadow:0 1px 2px #0003;font-weight:500}.settings button:hover,.empty button:hover{background:#303137;border-color:#ffffff25}.settings .icon-button{background:transparent;border:0;box-shadow:none;border-radius:6px;color:#a5a6ad}.settings .icon-button:hover{background:#ffffff08;color:#fff}.settings .icon-button svg{width:17px;height:17px;filter:none}.settings select:hover:not(:disabled){background:#ffffff05;color:#f3f3f5}.settings option{background:#202125;color:#eee}.settings input::file-selector-button{font:inherit;color:#d5d5da;background:#25262b;border:1px solid #ffffff14;border-radius:6px;padding:8px 10px;margin-right:8px;cursor:pointer}.topbar .icon-button:hover,.row .icon-button:hover{background:#111318b3}.row .icon-button[aria-expanded=true],.row .icon-button[aria-pressed=true]{background:#17191dcc;color:#fff}
/* One quiet, distinctive entry point into the empty player. */
.empty #open{display:inline-flex;align-items:center;gap:16px;min-height:62px;padding:12px 22px;background:linear-gradient(135deg,#ffffff08,#ffffff02);border:1px solid #ffffff16;border-radius:18px;box-shadow:inset 0 1px 0 #ffffff08;color:#d6d7dc;font-size:14px;font-weight:450;letter-spacing:.2px;transition:border-color .2s,background .2s,box-shadow .2s}.empty #open .open-folder{width:28px;height:28px;color:#c9c2b5}.empty #open .open-arrow{width:18px;height:18px;color:#777b85;margin-left:10px;transition:transform .2s,color .2s}.empty #open:hover{background:linear-gradient(135deg,#ffffff10,#ffffff04);border-color:#ffffff30;box-shadow:inset 0 1px 0 #ffffff10,0 8px 30px #0002;color:#fff}.empty #open:hover .open-arrow{transform:translateX(3px);color:#e7e4dd}.empty #open:active{transform:translateY(1px)}
/* Top-right menus align with their triggers; volume sits under the timeline. */
.settings{top:64px;bottom:auto;max-height:calc(100% - 80px);transform-origin:top right;--menu-offset:-6px}.settings:not([hidden]){transform-origin:top right}.source-menu{top:64px}.controls .times{align-items:center;gap:12px}.controls .row{margin:0}
@container player (max-width:600px){.transport{top:42%}.settings,.source-menu{top:50px;bottom:auto;max-height:calc(100% - 62px)}}
/* Show only the existing timeline briefly after a hidden-control seek. */
.idle.seek-preview .controls{opacity:1;translate:0 0}.idle .controls .row,.idle .controls slot{visibility:hidden}.idle.seek-preview .controls,.idle.seek-preview .controls *{pointer-events:none}
/* A slim volume track inside the existing pointer target. */
.volume{appearance:none;background:transparent;height:32px;padding:0;--volume-progress:100%}
.volume::-webkit-slider-runnable-track{height:2px;border-radius:2px;background:linear-gradient(to right,#e5e2dc var(--volume-progress),#ffffff30 var(--volume-progress))}
.volume::-webkit-slider-thumb{appearance:none;width:8px;height:8px;margin-top:-3px;border:0;border-radius:50%;background:#e5e2dc;transition:scale .16s,box-shadow .16s}
.volume::-moz-range-track{height:2px;border-radius:2px;background:#ffffff30}.volume::-moz-range-progress{height:2px;border-radius:2px;background:#e5e2dc}.volume::-moz-range-thumb{width:8px;height:8px;border:0;border-radius:50%;background:#e5e2dc;transition:scale .16s,box-shadow .16s}
.volume:hover::-webkit-slider-thumb,.volume:focus-visible::-webkit-slider-thumb{scale:1.25;box-shadow:0 0 0 3px #ffffff10}.volume:hover::-moz-range-thumb,.volume:focus-visible::-moz-range-thumb{scale:1.25;box-shadow:0 0 0 3px #ffffff10}
@media(forced-colors:active){.volume{appearance:auto}}
/* Motion stays on overlays so playback geometry never shifts. */
:host{--motion-ease:cubic-bezier(.22,1,.36,1)}
.topbar,.controls,.transport{transition:opacity .24s ease,translate .32s var(--motion-ease),scale .32s var(--motion-ease)}
.idle .topbar{translate:0 -6px}.idle .controls{translate:0 8px}.idle .transport{scale:.96}
.shell:not(.idle):has(:focus-visible) .topbar,.shell:not(.idle):has(:focus-visible) .controls{translate:0 0}.shell:not(.idle):has(:focus-visible) .transport{scale:1}
button{transition:background .16s,color .16s,border-color .16s,scale .18s var(--motion-ease)}button:active:not(:disabled){scale:.94}
.icon-button svg{transition:transform .28s var(--motion-ease)}#settings-toggle[aria-expanded=true] svg{transform:rotate(35deg)}
.settings:not([hidden]){animation:menu-enter .22s var(--motion-ease);transform-origin:bottom right}.settings.source-menu{transform-origin:top right;--menu-offset:-6px}
@keyframes menu-enter{from{opacity:0;translate:0 var(--menu-offset,6px);scale:.98}to{opacity:1;translate:0 0;scale:1}}
.more-options[open]>*:not(summary){animation:detail-enter .18s ease-out}@keyframes detail-enter{from{opacity:0;translate:0 -3px}to{opacity:1;translate:0 0}}
.timeline::-webkit-slider-thumb{transition:scale .16s var(--motion-ease),box-shadow .16s}.timeline:hover:not(:disabled)::-webkit-slider-thumb,.timeline:focus-visible::-webkit-slider-thumb{scale:1.2;box-shadow:0 0 0 4px #ffffff14}.timeline:active:not(:disabled)::-webkit-slider-thumb{scale:1.35}
.timeline::-moz-range-thumb{transition:scale .16s var(--motion-ease),box-shadow .16s}.timeline:hover:not(:disabled)::-moz-range-thumb,.timeline:focus-visible::-moz-range-thumb{scale:1.2;box-shadow:0 0 0 4px #ffffff14}.timeline:active:not(:disabled)::-moz-range-thumb{scale:1.35}
.empty #open{transition:border-color .2s,background .2s,box-shadow .2s,scale .18s var(--motion-ease)}.empty #open .open-folder{transition:transform .25s var(--motion-ease)}.empty #open:hover .open-folder{transform:translateY(-2px) rotate(-5deg)}
.busy{display:flex;align-items:center;gap:8px}.busy::before{content:"";width:10px;height:10px;flex:none;border:1.5px solid #ffffff30;border-top-color:currentColor;border-radius:50%;animation:busy-turn .8s linear infinite}@keyframes busy-turn{to{transform:rotate(360deg)}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto;transition:none!important;animation:none!important}}

@media(forced-colors:active){button,select,.shell,.settings{border:1px solid ButtonText}.transport .play{border-color:ButtonText}.stage{background:Canvas}.settings,.source-menu{background:Canvas}.timeline{appearance:auto;accent-color:Highlight}.icon-button,.time,.empty,.help{color:CanvasText}}
`;
