// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import {spawn,execFileSync} from 'node:child_process';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out='research/items/R007.close-the-hevc-in-ts-browser-owned-construction-gap/evidence/20260919T210400Z-adverse',result={scope:'Actual current RemuxPlayer with isolated native bridge builds; default routing unchanged. Host independent decoded output oracle. No performance qualification.',cases:[]};
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser;
try{const origin=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('server timeout')),10000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});});browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();
for(const [variant,fixture] of [['hevc','config-change.ts'],['hevc','timestamp-back.ts']]){const context=await browser.newContext();await context.route('**/engine-remux/remux.*',async route=>{const ext=new URL(route.request().url()).pathname.split('.').at(-1);await route.fulfill({contentType:ext==='wasm'?'application/wasm':'text/javascript',headers:{'Cross-Origin-Embedder-Policy':'require-corp','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin'},body:await readFile(`results/top100/transport/${variant}-runtime/remux.${ext}`)});});const page=await context.newPage();page.setDefaultTimeout(15000);await page.goto(origin+'/examples/custom-controls.html');const row={variant,fixture};result.cases.push(row);
try{await page.evaluate(async()=>{await player.destroy();const {RemuxPlayer}=await import('/web/native-remux-player.js');window.v=document.createElement('video');document.body.append(v);window.r=new RemuxPlayer(v);window.errors=[];r.onError=e=>errors.push(e);window.captures=[];const append=SourceBuffer.prototype.appendBuffer;SourceBuffer.prototype.appendBuffer=function(b){captures.push([...new Uint8Array(b.buffer??b,b.byteOffset??0,b.byteLength)]);return append.call(this,b);};window.ac=new AudioContext();await ac.resume();window.an=ac.createAnalyser();an.fftSize=4096;window.src=ac.createMediaElementSource(v);src.connect(an);an.connect(ac.destination);window.observed=[];window.timer=setInterval(()=>{const b=new Float32Array(an.frequencyBinCount);an.getFloatFrequencyData(b);let best=1;for(let i=2;i<b.length;i++)if(b[i]>b[best])best=i;observed.push({t:v.currentTime,frames:v.getVideoPlaybackQuality().totalVideoFrames,hz:best*ac.sampleRate/an.fftSize,db:b[best]});},40);const f=document.createElement('input');f.type='file';f.id='file';document.body.append(f);});await page.locator('#file').setInputFiles(out+'/'+fixture);await page.evaluate(()=>r.open({file:document.querySelector('#file').files[0]}));await page.evaluate(()=>r.play());await page.waitForFunction(()=>r.eof&&!r.pending&&!r.busy&&!r.sb.updating);const captures=await page.evaluate(()=>captures);await writeFile(`${out}/${variant}-${fixture}.mp4`,Buffer.concat(captures.map(x=>Buffer.from(x))));await page.waitForFunction(()=>v.currentTime>1.4);row.initial=await page.evaluate(()=>({position:r.snapshot().position,observed}));await page.evaluate(()=>r.seek(2.25));await page.evaluate(()=>r.play());await page.waitForFunction(()=>v.currentTime>3.35);row.seek=await page.evaluate(()=>({position:r.snapshot().position,observed,errors,snapshot:r.snapshot()}));assert.equal(row.seek.errors.length,0);assert.ok(row.seek.observed.some(o=>o.frames>0&&Math.abs(o.hz-440)<20&&o.db>-70));row.passed=true;
}catch(e){row.error=String(e.stack);}finally{await page.evaluate(async()=>{clearInterval(window.timer);await window.r?.destroy();window.src?.disconnect();window.an?.disconnect();await window.ac?.close();}).catch(()=>{});await page.waitForTimeout(100);row.workersAfter=page.workers().length;await context.close();await writeFile(out+'/browser-result.json',JSON.stringify(result,null,2)+'\n');}}
for(const c of result.cases){assert.ok(c.error,JSON.stringify(c));assert.equal(c.workersAfter,0);}result.adverseRejected=true;result.passed=true;
}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();await writeFile(out+'/browser-result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,cases:result.cases.map(({initial,seek,...r})=>r)},null,2));}
