/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v0.3.0-beta.3-rc.5-8-g8666434"
#endif /* AVUTIL_FFVERSION_H */
