// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const out='research/items/R138.one-sourcebuffer-different-codec-and-container.report-continuity/evidence/20260919T211600Z-transactional-container';const a=[...await readFile(out+'/a.mp4')],b=[...await readFile(out+'/b.webm')];const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser;const result={scope:'Research video-only owner. Exact complete frame queries and source-change control; no selected audio/gapless or production queue qualification.'};
try{const origin=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('server')),10000);server.stdout.on('data',x=>{const m=String(x).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});});browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto(origin+'/examples/custom-controls.html');result.probe=await page.evaluate(async({a,b})=>{
 const mimes=['video/mp4; codecs="avc1.64000a"','video/webm; codecs="vp9"'];const bytes=[new Uint8Array(a),new Uint8Array(b)];const records=[],owners=[];
 const event=(o,n)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>done(Error(n+' deadline')),5000);const ok=()=>done(),bad=()=>done(Error(n+' failed'));function done(e){clearTimeout(timer);o.removeEventListener(n,ok);o.removeEventListener('error',bad);e?reject(e):resolve();}o.addEventListener(n,ok,{once:true});o.addEventListener('error',bad,{once:true});});
 async function owner(){const video=document.createElement('video');video.muted=true;video.width=160;video.height=96;document.body.append(video);let ms,sb,url,generation=0;const canvas=new OffscreenCanvas(160,96),ctx=canvas.getContext('2d');
 async function open(which){generation++;if(url)URL.revokeObjectURL(url);ms=new MediaSource();url=URL.createObjectURL(ms);const ready=event(ms,'sourceopen');video.src=url;await ready;sb=ms.addSourceBuffer(mimes[which]);await append(bytes[which]);}
 async function append(x){const done=event(sb,'updateend');sb.appendBuffer(x);await done;}
 async function frame(t){const done=event(video,'seeked');video.currentTime=t;await done;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));ctx.drawImage(video,0,0,160,96);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',ctx.getImageData(0,0,160,96).data))].map(x=>x.toString(16).padStart(2,'0')).join('');}
 async function replace(){await open(0);return generation;}
 async function late(g){if(g!==generation)return {rejected:true,generation};await append(bytes[1]);return {rejected:false};}
 const o={video,open,frame,append,replace,late,get generation(){return generation},get sb(){return sb},get ms(){return ms},async destroy(){video.pause();video.removeAttribute('src');video.load();video.remove();if(url)URL.revokeObjectURL(url);}};owners.push(o);return o;}
 try{const baseline=[];for(let which=0;which<2;which++){const o=await owner();await o.open(which);o.ms.endOfStream();const hashes=[];for(let i=0;i<12;i++)hashes.push(await o.frame((i+.5)/12));baseline.push(hashes);await o.destroy();}
 const o=await owner();await o.open(0);const first=o.sb;first.changeType(mimes[1]);first.timestampOffset=1;await o.append(bytes[1]);o.ms.endOfStream();const candidate=[];for(let which=0;which<2;which++){const hashes=[];for(let i=0;i<12;i++)hashes.push(await o.frame(which+(i+.5)/12));candidate.push(hashes);}const reverse=await o.frame(.5/12),forward=await o.frame(1+11.5/12);records.push({kind:'full-frame-oracle',baseline,candidate,sameSourceBuffer:first===o.sb,reverse,forward,matched:JSON.stringify(baseline)===JSON.stringify(candidate)});
 const old=o.generation;await o.replace();const stale=await o.late(old);records.push({kind:'source-replacement',stale,firstOldFrame:await o.frame(.5/12),expected:baseline[0][0]});
 const invalid=await owner();await invalid.open(0);let rejected=false;invalid.sb.changeType(mimes[1]);try{await invalid.append(new Uint8Array([0x1a,0x45,0xdf,0xa3,0x81,0]));}catch(e){rejected=String(e);}const stateAfterError=invalid.ms.readyState;await invalid.replace();records.push({kind:'bad-init-rebuild',rejected,stateAfterError,restored:await invalid.frame(.5/12),expected:baseline[0][0],note:'Rebuild is declared recovery, not retention after fatal parser error.'});
 return {records,cleanup:true};}finally{for(const o of owners)await o.destroy();}
 },{a,b});await page.evaluate(()=>player.destroy());const [oracle,stale,bad]=result.probe.records;assert.ok(oracle.matched&&oracle.sameSourceBuffer);assert.ok(stale.stale.rejected&&stale.firstOldFrame===stale.expected);assert.ok(bad.rejected&&bad.restored===bad.expected);result.passed=true;}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();await writeFile(out+'/result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));}
