# SPDX-License-Identifier: Apache-2.0
"""Register immutable recovered-video observations and explicit scoped contracts."""
import pathlib,json,hashlib,sys,importlib.util,statistics,subprocess,datetime
ROOT=pathlib.Path.cwd();T=ROOT/'research/shared/tooling/recovered-video';spec=importlib.util.spec_from_file_location('record',ROOT/'research/shared/tooling/record-research-stage.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
def write(p,x):p.write_text(json.dumps(x,indent=2)+'\n')
def rel(p):return str(p.relative_to(ROOT))
def artifact(p):return {'path':rel(p),'license':'Apache-2.0' if p.suffix in ('.py','.mjs') or p.name.endswith(('.py.txt','.mjs.txt')) else 'CC-BY-4.0','role':'original independent harness/source snapshot' if p.suffix in ('.py','.mjs','.txt') else 'synthetic fixture, captured measurement or research report','provenance':'Original Demuxe research; lavfi testsrc2 or authored Hap BC1 fixture. Tool/runtime names do not imply redistributed runtime licensing.'}
variants=[('040100','recovered-video-codec','codec-probes.py','Original mixed-profile smart cut fails189229 channel bytes; R076360p first pass succeeded.'),('040200','recovered-texture-playback','texture-playback.mjs','Initial adapter reuse rejected after firstdevice; environment/lifecycle harness diagnostic, not candidate fidelity result.'),('040700','recovered-video-distinct-sps','codec-probes.py','Distinct SPS identifiers do not fix mixed lossless/lossy splice; hypothesis ruled out, rootcause not established.'),('040800','recovered-texture-device','texture-playback.mjs','Fresh adapter fixes device reuse; strict GPU-vs-CPU BC interpolation equality fails.'),('041200','recovered-video-lossless','codec-probes.py','Uniform lossless H264 profile passes smart edit pixels, timing, packet preservation and allseven paired cost comparisons. R076360p repeat timing gate fails under observed noise.'),('041300','recovered-texture-rounding','texture-playback.mjs','Strict oracle mismatch quantified: native171/84 versus CPU170/85, max1channel. Preserve strict byte-exact failed profile.'),('041600','recovered-texture-bounded-fidelity','texture-playback.mjs','Explicit revised <=1LSB RGB, exact alpha profile passes32frames and all9 complete-job comparisons. Prior zero-error failure retained, no exact claim.'),('041900','recovered-temporal-720p','framerate-probe.py','Larger fixture prepared correctly but linear select expression exceeds parser depth; setup diagnostic, not timing result.'),('042100','recovered-edit-lifecycle','edit-lifecycle.py','Termination/reopen and other-source dimensions then return-seek exact.'),('042300','recovered-temporal-balanced','framerate-probe.py','Balanced expression sameselectedwork oracle:107/240frames exact, sourcePTS preserved; seven pairs all faster.'),('042600','recovered-texture-canvas','texture-playback.mjs','Actual WebGPU visible canvas and independent screenshot oracle within1LSB; all9 completejob pairs faster.'),('043000','recovered-video-supplement','qualify-supplement.py','Temporal seek exact output order/count; visible canvas screenshot max1LSB alphaexact.')]
folders=[];bulk=[]
for stamp,name,tool,note in variants:
 f=ROOT/f'research/shared/runs/20260920T{stamp}Z-{name}';folders.append(f)
 if not (f/(tool+'.txt')).exists():(f/(tool+'.txt')).write_bytes((T/tool).read_bytes())
 artifacts=[artifact(p) for p in sorted(f.iterdir()) if p.is_file()]
 command=('node' if tool.endswith('.mjs') else 'python3')+' '+rel(T/tool)+' '+rel(f)
 if tool=='edit-lifecycle.py':command='python3 '+rel(T/tool)+' research/shared/runs/20260920T041200Z-recovered-video-lossless '+rel(f)
 if tool=='qualify-supplement.py':command='python3 '+rel(T/tool)+' research/shared/runs/20260920T042300Z-recovered-temporal-balanced research/shared/runs/20260920T042600Z-recovered-texture-canvas '+rel(f)
 if tool=='texture-playback.mjs':command='python3 research/shared/tooling/recovered-video/texture-fixture.py '+rel(f)+'\n'+command
 if not (f/'run.json').exists():m.record({'folder':rel(f),'stage':'actual-route qualification or preserved diagnostic','items':['R076.definition-not-recovered','R077.definition-not-recovered','R078.definition-not-recovered'],'commands':[command],'analysis':note+'\n\nRun directory timestamp prefixes were mistakenly allocated ahead of the actual wall clock. They are immutable allocation labels, not execution timestamps; recorded_at_utc is the actual registration time. Candidate measurements are process monotonic durations. Original commands and failed variants remain preserved.','artifacts':artifacts,'decisions':[]})
 for p in f.iterdir():
  if p.suffix in ('.mp4','.h264','.avi') or p.name=='input.json':bulk.append({'path':rel(p),'reason':'Generated synthetic media or fixture/oracle payload, recreated by retained original harness or exact variant snapshot. Measurements and screenshots retained.','recovery':[rel(f/(tool+'.txt')),rel(f/'commands.log')],'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
final=ROOT/'research/shared/runs'/('20260920T'+datetime.datetime.now(datetime.timezone.utc).strftime('%H%M%S')+'Z-recovered-video-qualification');final.mkdir()
a=json.load(open(folders[9]/'results.json'))['R076'];b=json.load(open(folders[4]/'results.json'))['R077'];c=json.load(open(folders[10]/'results.json'));ratios=[s['candidate']['ms']/s['baseline']['ms'] for s in c['probe']['samples']];assert a['performance_pass'] and b['performance_pass'] and c['passed'] and statistics.median(ratios)<=.95 and max(ratios)<1
runtime={'ffmpeg_version':subprocess.check_output(['ffmpeg','-version'],text=True),'node_version':subprocess.check_output(['node','--version'],text=True).strip(),'python':sys.version,'browser':c['browser'],'adapter':c['probe']['adapterInfo']};ff=pathlib.Path('/opt/homebrew/bin/ffmpeg').resolve();runtime['ffmpeg_executable']={'path':str(ff),'sha256':hashlib.sha256(ff.read_bytes()).hexdigest()};write(final/'runtime.json',runtime);write(final/'regenerable-artifacts.json',{'schema':1,'artifacts':bulk})
summary={'R076':a,'R077':b,'R078':{'performance_ratio_median':statistics.median(ratios),'paired_ratios':ratios,'performance_pass':True,'max_RGB_error':c['probe']['maxChannelError'],'alpha_exact':True,'strict_byte_exact_profile':'failed; preserved in earlier runs','frames':32,'upload_ratio':.125,'texture_storage_ratio':.125,'full_setup_measured':True,'physical_display_qualification':False},'all_scopes':'Host/software H264 and Chrome WebGPU research routes; no shipping integration, no arbitrarycodec/profile or hardwareenergy qualification. Performance is wallclock on this shared development machine; interleaved pairs reduce but do not eliminate load effects.','registration_runs':[rel(f/'run.json') for f in folders]};write(final/'results.json',summary)
contracts={
'R076':{'scope':'H264 closed-GOP no B-pyramid nonreference pictures dropped before reconstruction, retaining all reference pictures and original variable PTS. 1280x720 240frame profile qualified; 360p setup-dominated variant inconsistent across repeats. No target constantfps guarantee.','correctness':'107 retained frames exact against full decoder output indexed by matching source PTS; key-only wrongselection detected, no-Bfallback exact, five seek/reopen cases exact order/count, subprocess cancel and freshowner verified.','performance':f"Seven alternating complete fresh-process jobs, median ratio {a['median_ratio']:.6f}, every pair faster, >=5% median threshold met. Includes output serialization and teardown; no physical energy claim.",'reason':'Dependency-safe predecode thinning qualified on declared720p software H264 profile:107/240 pictures retained exact and19.25% median total walltime saving. Variable cadence and reference structure constrain applicability.','related':['R350.extract-a-declared-lower-frame-rate-av1-operating-point-before-decoding'],'reopen':'Integrate an explicit opt-in policy only for identified nonreference pictures; rerun native/WebCodecs/audio synchronization and other reference structures before broader use.'},
'R077':{'scope':'Lossless H264 video-only640x36030fps closed-GOP noB source. Frameaccurate cut[7,113): reencode46 boundary frames losslessly, copy60 interior VCL slices, remux rebased106frames. Mixed lossyinterior/losslessedge concatenation failed pixelcontract and remains excluded.','correctness':'All106 decoded YUV frames exact against independent source-full-decode trim, timestamps exactlyrebased, all60interiorVCL hashes preserved, wrongstart detected; seek/reopen/sourcechange/termination pass.','performance':f"Seven alternating complete edit jobs, median ratio {b['median_ratio']:.6f}, every pair faster; >=5% median threshold met. Includes demux, edge decode/encode, I/O/concat/mux, setup and teardown. Source fixture preparation excluded equally.",'reason':'Uniform lossless H264 smart cut qualified:46of106frames reencoded,60slice payloads preserved, exact output/timestamps and34.29% median walltime saving. Mixed-profile variant is a retained correctness failure, not qualified.','related':['R044.play-an-exact-requested-excerpt-without-re-encoding-its-edge-gop'],'reopen':'Implement eligibility validation for uniform lossless profile; investigate mixed-profile splice divergence before any claim for arbitrary lossy sources, Bframes, openGOP or audio.'},
'R078':{'scope':'32frame30fps128x128 opaque Hap1 BC1 AVI, bounded container parser, compressed GPU texture upload and visiblecanvas presentation without conventional decoder. Revised profile RGBerror<=1/255 and alphaexact versus FFmpeg; original strictbyteexact profile failed GPUinterpolation and is not qualified.','correctness':'All32candidateframes and all32baselineframes checked; candidate max1LSB RGB and exactalpha. Wrongframe/corruptselector/truncated/codec/EOF controls; seeks, epochcancel, freshdevices; wallclock sequence32frames, actualcanvas screenshot validates lastframe independently.','performance':f"Nine alternating fresh-device32frame jobs incl parsing,pipeline,uploads,render,fullreadback andteardown; median ratio {statistics.median(ratios):.6f}, allpairs faster, >=5% median threshold met.8x less upload/source texture storage, not8x totalGPU memory. Visiblecanvas timeline separately verified; no physicalscanout claim.",'reason':'Texture-native browser playback qualified for declared Hap1 BC1 bounded-fidelity profile; visiblecanvas max1LSB RGB, exactalpha, lifecycle/timingcontrols,16.09% median job saving and8x less textureupload/storage. Strict byte-exact CPU/GPU profile remains failed.','related':['R172.keep-hap-bc1-compressed-to-presentation'],'reopen':'Add container/format eligibility and fidelitypolicy before integration; qualify Snappy, other BC modes, dimensions, audio sync and realworldlong streams separately. Never advertise strict CPUdecode bitexactness.'}}
decisions=[]
for short,contract in contracts.items():
 key=short+'.definition-not-recovered';home=ROOT/'research/items'/key;item=json.load(open(home/'item.json'));d=item['definition'];d.update({'definition_status':'RECOVERED_TITLE_WITH_EXPLICIT_DERIVED_TEST_CONTRACT','scope_contract':contract['scope'],'primary_metric':contract['performance'],'negative_control':contract['correctness'],'related_keys':contract['related'],'minimum_probe':'Completed actual candidate qualification recorded in current evidence.','initial_screen':'Explicit contract derived from recovered title; original detailed report remains unavailable.','reopen_condition':contract['reopen'],'default_next_action':contract['reopen'],'evidence_level':'actual_route_qualification','target_relevance':'scoped_research_profile','impact_basis':'Measured scoped outcomes; no fabricated original priority score.','recovery_note':'Original title source retained. Contract independently authored from recovered title under user authorization; not presented as original recovered report.'});item['qualification']={'status':'qualified_scoped_research_profile','scope':contract['scope'],'not_shipping_or_release_qualification':True};write(home/'item.json',item)
 readme=(home/'README.md').read_text();at=readme.index('## Stages');readme=readme[:at]+'## Definition and contract\n\n'+contract['scope']+'\n\nDerived openly from the recovered title; the original detailed report is unavailable.\n\n'+contract['correctness']+'\n\n'+contract['performance']+'\n\n'+readme[at:];(home/'README.md').write_text(readme)
 stages={'define':{'status':'passed','basis':contract['scope']},'prepare':{'status':'passed','basis':'Synthetic generation, independent oracle, exactcommands/runtimehashes and wrongoutput controls recorded; preserveddiagnostics included.'},'screen':{'status':'passed','basis':'Actual candidate executed, no conventionaldecode fallback hidden; scoped admissibility and failures recorded.'},'correctness':{'status':'passed','basis':contract['correctness']},'performance':{'status':'passed','basis':contract['performance']}}
 decisions.append({'key':key,'disposition':'pursue','category':'qualified_scoped_research_profile','evidence_level':'actual_route_qualification','candidate_executed':True,'new_execution':True,'reason':contract['reason'],'profile':contract['scope'],'next_action':contract['reopen'],'stages':stages})
arts=[artifact(p) for f in folders for p in sorted(f.iterdir()) if p.is_file()]+[artifact(p) for p in T.iterdir() if p.is_file()]+[artifact(p) for p in final.iterdir() if p.is_file()]
m.record({'folder':rel(final),'stage':'qualification and decision','items':[x['key'] for x in decisions],'commands':['python3 research/shared/tooling/recovered-video/register.py'],'analysis':'All three recovered-title hypotheses have explicit bounded research qualifications. Original reports were not fabricated. Preserve failed mixed-profile splice and strictBC1bitexact variants alongside qualified scopes. See results.json and each canonical contract; qualification is research-only, not production admission. Runfolder clocklabel error is explicitly documented in each exploratory record.','artifacts':arts,'decisions':decisions});print(rel(final))
