// SPDX-License-Identifier: Apache-2.0
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialPlayerControl} from '../../web/generated/internal/machine/state.js';
import {transitionPlayer} from '../../web/generated/internal/machine/transition.js';
import {candidateAttachments} from '../../web/generated/internal/machine/attachments.js';
import {unitPlayer} from '../helpers/unit-player.mjs';
import {acceptSourceIdentity} from '../helpers/player-control.mjs';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const MiB=1024*1024;
function accept(owner,preserve=true,settings=owner.state.settings){const attempt=owner.send({type:'source.begin',operationEpoch:owner.state.operations.epoch,mode:owner.state.source.mode,preserve,planId:'fixture'}).id;for(const type of ['source.created','source.configured','source.opened','source.applied','source.positioned'])owner.send({type,attempt});assert.equal(owner.send({type:'source.accept',attempt,operationEpoch:owner.state.operations.epoch,settings,planMatches:true}).accepted,true);owner.send({type:'source.finished',attempt});}
function core(open=true){let state=initialPlayerControl();const send=input=>{const before=state,text=JSON.stringify(before),out=transitionPlayer(state,input);assert.equal(JSON.stringify(before),text,'previous state was mutated');state=out.state;return out;};const owner={send,get state(){return state;}};if(open)accept(owner,false);const operation=send({type:'operation.admit',kind:'switching'}).id;send({type:'operation.start',id:operation});return owner;}
function facts(owner,changes={}){return {sourceId:owner.state.source.acceptedSession===null?null:owner.state.source.serial,session:owner.state.source.acceptedSession,hasSource:owner.state.source.acceptedSession!==null,hasBackend:owner.state.source.acceptedSession!==null,nativeASS:false,plan:'direct',surfaceLocked:false,...changes};}
function add(owner,kind='subtitle',bytes=10,changes={}){const id=owner.send({type:'attachment.allocate',kind,file:{valid:true,format:kind==='font'?'ttf':'vtt',size:bytes}}).id;return owner.send({type:'attachment.begin',command:{kind:'add',entry:{id:`${kind}-${id}`,kind,bytes,sourceId:kind==='font'?null:facts(owner).sourceId},select:true,...changes.command},facts:facts(owner,changes.facts)});}
function finish(owner,request,bytes=10){if(request.effects?.[0]?.kind==='attachment.read')assert.equal(owner.send({type:'attachment.ready',id:request.id,bytes}).accepted,true);assert.equal(owner.send({type:'attachment.complete',id:request.id}).accepted,true);return owner.state.attachments.entries.at(-1);}
test('attachment allocation preserves serial consumption on rejected input without retaining file payload',()=>{const r=core(false);for(const kind of ['subtitle','font']){const out=r.send({type:'attachment.allocate',kind,file:{valid:false,format:'',size:0}});assert.equal(out.accepted,false);assert.equal(out.reason,'invalid');}assert.equal(r.state.attachments.serial,2);assert.deepEqual(r.state.attachments.entries,[]);assert.equal(add(r,'font').id,1);assert.equal(r.state.attachments.serial,3);});
test('subtitle membership and stable selection remain private until atomic source acceptance',()=>{const r=core();r.send({type:'preferences.change',value:{publicSelections:{sub:'sub:stream:3'}}});const request=add(r);assert.equal(r.state.attachments.entries.length,0);assert.equal(candidateAttachments(r.state).length,0);r.send({type:'attachment.ready',id:request.id,bytes:8});assert.equal(candidateAttachments(r.state).length,1);assert.equal(r.state.preferences.publicSelections.sub,'sub:stream:3');accept(r,true,{...r.state.settings,sid:'7'});assert.equal(r.state.attachments.entries[0].bytes,8);assert.equal(r.state.preferences.publicSelections.sub,undefined);r.send({type:'attachment.complete',id:request.id});assert.equal(r.state.settings.sid,'7','final completion cannot overwrite remapped backend ID');});
for(const phase of ['reading','applying','accepted'])test(`failure in attachment ${phase} preserves only accepted membership`,()=>{const r=core();const request=add(r);if(phase!=='reading')r.send({type:'attachment.ready',id:request.id,bytes:4});if(phase==='accepted')accept(r);r.send({type:'attachment.failed',id:request.id});assert.equal(r.state.attachments.entries.length,phase==='accepted'?1:0);assert.equal(r.state.attachments.pending,null);});
for(const terminal of [false,true])for(const phase of ['reading','applying','accepted'])test(`${terminal?'destroy':'close'} retires attachment ${phase} and rejects late completions`,()=>{const r=core(),font=add(r,'font');finish(r,font);const request=add(r);if(phase!=='reading')r.send({type:'attachment.ready',id:request.id,bytes:5});if(phase==='accepted')accept(r);r.send({type:'operation.retire',terminal});assert.equal(r.send({type:'attachment.complete',id:request.id}).accepted,false);r.send({type:'source.clear'});assert.deepEqual(r.state.attachments.entries.map(item=>item.kind),terminal?[]:['font']);assert.equal(r.send({type:'attachment.ready',id:request.id,bytes:5}).accepted,false);});
test('new source expires subtitles and text while retaining fonts and attachment serial',()=>{const r=core();for(const kind of ['font','subtitle','text'])finish(r,add(r,kind));const serial=r.state.attachments.serial;accept(r,false);assert.deepEqual(r.state.attachments.entries.map(item=>item.kind),['font']);assert.equal(r.state.attachments.serial,serial);});
for(const [kind,max] of [['subtitle',16],['font',32]])test(`${kind} byte budget accepts exact boundary and rejects before read`,()=>{const r=core();for(let n=0;n<max/8;n++)finish(r,add(r,kind,8*MiB),8*MiB);const rejected=add(r,kind,1);assert.equal(rejected.accepted,false);assert.match(rejected.message,/budget exceeded/);assert.deepEqual(rejected.effects,[]);});
for(const kind of ['subtitle','font','text'])test(`${kind} count budget is independent of byte budget`,()=>{const r=core();for(let n=0;n<16;n++)finish(r,add(r,kind,0),0);const out=add(r,kind,0);assert.equal(out.accepted,false);assert.equal(r.state.attachments.entries.length,16);});
test('actual read byte budget is checked before candidate membership becomes visible',()=>{const r=core();finish(r,add(r,'subtitle',8*MiB),8*MiB);finish(r,add(r,'subtitle',8*MiB-1),8*MiB-1);const request=add(r,'subtitle',1),rejected=r.send({type:'attachment.ready',id:request.id,bytes:2});assert.equal(rejected.accepted,false);assert.match(rejected.message,/budget/);assert.equal(candidateAttachments(r.state).length,2);});
test('host subtitle policy, browser surface locks and stale source facts reject before effects',()=>{for(const change of [{policy:{locked:true}},{policy:{allowed:[{language:'japanese'}]},track:{id:'external',language:'english',title:'x',codec:'vtt',streamIndex:null,default:false,selected:false}},{session:99}]){const r=core(),out=add(r,'subtitle',10,{facts:change});assert.equal(out.accepted,false);assert.deepEqual(out.effects,[]);}const r=core();assert.equal(add(r,'text',0,{facts:{surfaceLocked:true}}).accepted,false);});
test('font route decision uses accepted mode, overlay and source facts',()=>{for(const [mode,changes,route] of [['native',{},undefined],['native',{plan:'remux-mpv'},'attachment.replace'],['hybrid',{},'attachment.replace'],['software',{},'attachment.replace']]){const r=core();r.send({type:'source.configure',mode});const request=add(r,'font',10,{facts:changes}),out=r.send({type:'attachment.ready',id:request.id,bytes:10});assert.equal(out.effects[0]?.kind,route);}const r=core(false);assert.equal(r.send({type:'attachment.ready',id:add(r,'font').id,bytes:10}).effects.length,0);});
function remove(r,entry,changes={},factChanges={}){return r.send({type:'attachment.begin',command:{kind:'remove',id:entry.id,handleKind:entry.kind==='font'?'font':'subtitle',sourceId:entry.sourceId,authentic:true,selected:false,...changes},facts:facts(r,factChanges)});}
test('removing the selected subtitle stages off policy and clears identity only at acceptance',()=>{const r=core(),entry=finish(r,add(r));r.send({type:'preferences.change',value:{publicSelections:{audio:'audio:stream:0',sub:`sub:attachment:${entry.id}`}}});const request=remove(r,entry,{selected:true});assert.equal(request.effects[0].settings.sid,'no');assert.equal(request.effects[0].settings.subtitles,false);assert.equal(r.state.attachments.entries.length,1);accept(r,true,request.effects[0].settings);assert.equal(r.state.attachments.entries.length,0);assert.deepEqual(r.state.preferences.publicSelections,{audio:'audio:stream:0'});r.send({type:'attachment.failed',id:request.id});assert.equal(r.state.attachments.entries.length,0);});
test('foreign, mismatched, expired and repeated handles cannot remove owned attachments',()=>{const r=core(),entry=finish(r,add(r));for(const change of [{authentic:false},{sourceId:2},{handleKind:'font'},{id:'missing'}])assert.equal(remove(r,entry,change).accepted,false);assert.equal(remove(r,entry,{selected:true},{policy:{allowOff:false}}).accepted,false);const request=remove(r,entry);finish(r,request);assert.equal(remove(r,entry).accepted,false);});
function adapter(t){const p=unitPlayer(),backend=new EventTarget();Object.assign(backend,{properties:new Map([['pause',true],['time-pos',0],['duration',20],['track-list',[]]]),diagnostics:{plan:'direct'},destroy:async()=>{},pause:async()=>{},play:async()=>{},addTextTrack:async()=>{}});Object.assign(p,{source:{kind:'local',file:new Blob()},current:{backend,surface:{remove(){}}}});acceptSourceIdentity(p,1);p.stateSnapshot={sourceId:1,mediaInfo:{subtitle:null}};p.select=async(_source,settings)=>accept({get state(){return p.control;},send:input=>p.dispatchControl(input)},true,settings);p.replace=p.select;t.after(()=>p.destroy());return {p,backend};}
const subtitle=()=>new File(['WEBVTT\n\n00:00.000 --> 00:02.000\nHello\n'],'caption.vtt');
test('actual attach holds accepted membership private while read and route work are deferred',async t=>{const {p}=adapter(t),read=deferred(),route=deferred(),started=deferred(),file=subtitle();file.arrayBuffer=()=>read.promise;p.select=async(_source,settings)=>{started.resolve();await route.promise;accept({get state(){return p.control;},send:input=>p.dispatchControl(input)},true,settings);};const task=p.attachSubtitle(file);await new Promise(setImmediate);assert.equal(p.control.attachments.entries.length,0);read.resolve(await subtitle().arrayBuffer());await started.promise;assert.equal(p.control.attachments.entries.length,0);assert.equal(p.subtitleAssets.length,1);route.resolve();const handle=await task;assert.equal(p.control.attachments.entries[0].id,handle.id);assert.equal(p.attachmentResources.size,1);});
for(const method of ['close','destroy'])for(const kind of ['font','subtitle'])test(`${method} during ${kind} file read cannot install late bytes`,async t=>{const {p}=adapter(t),read=deferred(),entered=deferred(),file=kind==='font'?new File(['font'],'font.ttf'):subtitle();file.arrayBuffer=()=>{entered.resolve();return read.promise;};const task=p[kind==='font'?'attachFont':'attachSubtitle'](file),rejection=assert.rejects(task,{code:'ABORTED'});await entered.promise;await p[method]();await rejection;read.resolve(new ArrayBuffer(8));await new Promise(setImmediate);assert.equal(p.attachmentResources.size,0);assert.deepEqual(p.control.attachments.entries,[]);});
test('late browser text completion after close cannot become membership of a reopened source',async t=>{const {p,backend}=adapter(t),pending=deferred(),entered=deferred();backend.addTextTrack=()=>{entered.resolve();return pending.promise;};const task=p.attachTextTrack({src:'blob:caller-owned',label:'Caption'}),rejection=assert.rejects(task,{code:'ABORTED'});await entered.promise;await p.close();await rejection;p.source={kind:'local',file:new Blob()};p.current={backend,surface:{remove(){}}};acceptSourceIdentity(p,2);pending.resolve();await new Promise(setImmediate);assert.equal(p.nativeTracks.length,0);assert.equal(p.attachmentResources.size,0);assert.equal(p.control.source.serial,2);});
test('actual failure after source acceptance retains the new subtitle resource and remapped ID',async t=>{const {p}=adapter(t);p.select=async(_source,settings)=>{accept({get state(){return p.control;},send:input=>p.dispatchControl(input)},true,{...settings,sid:'12'});throw Error('post-accept cleanup failure');};await assert.rejects(p.attachSubtitle(subtitle()),/post-accept/);assert.equal(p.control.attachments.entries.length,1);assert.equal(p.attachmentResources.size,1);assert.equal(p.settings.sid,'12');});
test('actual failed removal restores ownership before acceptance and retains removal after acceptance',async t=>{const {p}=adapter(t),handle=await p.attachSubtitle(subtitle());p.select=async()=>{throw Error('candidate failed');};await assert.rejects(p.removeAttachment(handle),/candidate failed/);assert.equal(p.attachmentResources.size,1);p.select=async(_source,settings)=>{accept({get state(){return p.control;},send:input=>p.dispatchControl(input)},true,settings);throw Error('cleanup failed');};await assert.rejects(p.removeAttachment(handle),/cleanup failed/);assert.equal(p.attachmentResources.size,0);await assert.rejects(p.removeAttachment(handle),{code:'INVALID_ARGUMENT'});});
test('actual fonts survive close and replacement source; branded handles reject foreign copies',async t=>{const {p,backend}=adapter(t),handle=await p.attachFont(new File(['font'],'font.ttf'));await p.close();assert.equal(p.fonts.length,1);p.source={kind:'local',file:new Blob()};p.current={backend,surface:{remove(){}}};acceptSourceIdentity(p,2);assert.equal(p.fonts.length,1);await assert.rejects(p.removeAttachment({...handle}),{code:'INVALID_ARGUMENT'});await p.removeAttachment(handle);assert.equal(p.fonts.length,0);await assert.rejects(p.removeAttachment(handle),{code:'INVALID_ARGUMENT'});});
test('actual invalid font extension consumes an ID but does not enter the queue',async t=>{const {p}=adapter(t);await assert.rejects(p.attachFont(new File(['font'],'ttf')),{code:'INVALID_ARGUMENT'});assert.equal(p.control.attachments.serial,1);assert.equal(p.queued,0);const handle=await p.attachFont(new File(['font'],'font.ttf'));assert.equal(handle.id,'font-2');});
test('synchronous file-read retirement observes its rejected physical promise without installing bytes',async t=>{const {p}=adapter(t),file=subtitle();let closing;file.arrayBuffer=()=>{closing=p.close();return Promise.reject(Error('late physical read failure'));};await assert.rejects(p.attachSubtitle(file),{code:'ABORTED'});await closing;await new Promise(setImmediate);assert.equal(p.attachmentResources.size,0);assert.equal(p.control.attachments.pending,null);});
for(let seed=1;seed<=12;seed++)test(`attachment model seed ${seed}: mixed add/remove/failure/close/reopen histories`,()=>{
  let random=seed*7919,sourceId=1,sourceSerial=1,serial=0;const next=()=>{random^=random<<13;random^=random>>>17;random^=random<<5;return random>>>0;};
  const r=core(),expected=new Map(),trace=[];
  const nextOperation=()=>{for(const entry of r.state.operations.entries){r.send({type:'operation.finish',id:entry.id});r.send({type:'operation.release',id:entry.id});}const id=r.send({type:'operation.admit',kind:'switching'}).id;r.send({type:'operation.start',id});};
  try{for(let index=0;index<100;index++){
    const action=next()%8;trace.push({index,action,sourceId});
    if(action<4){
      const kind=['subtitle','font','text'][next()%3],bytes=next()%1024,id=`${kind}-${++serial}`,failure=action===3;
      const request=add(r,kind,bytes),allowed=(kind==='font'||sourceId!==null)&&[...expected.values()].filter(entry=>entry.kind===kind).length<16;
      assert.equal(request.accepted,allowed);
      if(allowed){if(kind!=='text')r.send({type:'attachment.ready',id:request.id,bytes});if(failure)r.send({type:'attachment.failed',id:request.id});else {r.send({type:'attachment.complete',id:request.id});expected.set(id,{id,kind,bytes,sourceId:kind==='font'?null:sourceId});}}
    }else if(action===4||action===5){
      const entries=[...expected.values()],entry=entries[next()%Math.max(1,entries.length)]??{id:'foreign',kind:'subtitle',sourceId};
      const request=remove(r,entry);assert.equal(request.accepted,expected.has(entry.id));
      if(request.accepted){if(action===4){r.send({type:'attachment.complete',id:request.id});expected.delete(entry.id);}else r.send({type:'attachment.failed',id:request.id});}
    }else if(action===6){
      r.send({type:'operation.retire',terminal:false});r.send({type:'source.clear'});sourceId=null;for(const [id,entry]of expected)if(entry.kind!=='font')expected.delete(id);
    }else{
      accept(r,false);sourceId=++sourceSerial;assert.equal(r.state.source.serial,sourceSerial);for(const [id,entry]of expected)if(entry.kind!=='font')expected.delete(id);
    }
    assert.deepEqual(r.state.attachments.entries,[...expected.values()]);assert.equal(r.state.attachments.pending,null);assert.equal(r.state.attachments.serial,serial);nextOperation();
  }}catch(error){error.message+=`\nseed=${seed} trace=${JSON.stringify(trace)}`;throw error;}
});
