// SPDX-License-Identifier: Apache-2.0
// Human-reviewed behavior families. References establish test implementation,
// not exhaustive coverage or a current passing browser result.
const player=members=>members.split(' ').map(member=>`.#Player.${member}`);
const symbol=(entry,name,members)=>members.split(' ').map(member=>`${entry}#${name}${member==='@'?'':'.'+member}`);
const group=(id,apis,behavior,states,failures,backends,unit,browser,gaps)=>({id,apis,behavior,states,failures,backends,unit,browser,gaps,status:'partial'});
export const behaviorGroups=[
 group('construction',[
  '.#Player.constructor','.#PlayerError.constructor','.#PreviewController.constructor','.#AuthoredPreviewProvider.constructor','.#LocalVideoPreviewProvider.constructor','.#SoftwarePreviewProvider.constructor','.#PlayerPresentation.constructor','./player#DemuxePlayerElement.constructor','./integration#PlaybackBinding.constructor','./media-element#DemuxeMediaElement.constructor','./components#ProviderAcquisition.constructor'
 ],'Construct owners, apply options and roll back partial acquisition','constructing, active, retired during construction','invalid host/options, resource acquisition failure, reentry','DOM owners, providers and backend-independent facades',
 ['tests/api-stability/player-acquisition.mjs','tests/api-stability/consumer-preview-acquisition.mjs','tests/api-stability/provider-acquisition-state.mjs','tests/integration.mjs'],['tests/player-component.mjs','tests/integration-browser.mjs'],['Full constructor-option cross-product is not audited','Provider and error constructors need dedicated individual assertion review']),
 group('source-lifecycle',player('open openRemote close destroy ready isDestroyed'),'Admit a source, retire old work, join cleanup, permit close/reopen','idle, opening, ready, closing, destroyed','abort, replacement, stale completion, cleanup failure','Native, Hybrid, Software; streaming path separately',
 ['tests/api-stability/source-acceptance-state.mjs','tests/api-stability/player-teardown.mjs','tests/api-stability/wasm-player-lifecycle.mjs'],['tests/api-stability/browser.mjs','tests/api-stability/live-boundary-scenarios.mjs','tests/api-stability/live-network-scenarios.mjs'],['Network failures across Hybrid/Software remote opens, adaptive streams and custom sources beyond the bounded Native file cases','Close/reopen combined with authentication failure and cleanup errors']),
 group('transport',player('play pause seek rate volume setVolume setMuted setPlaybackRate'),'Preserve accepted intent and latest seek; validate and apply settings','idle, paused, playing, seeking, buffering, retired','invalid arguments, supersession, reentry, operation failure','Native, Hybrid, Software',
 ['tests/api-stability/player-transport-state.mjs','tests/api-stability/settings-adversarial-sequences.mjs','tests/play-pause-cancellation.mjs'],['tests/api-stability/browser.mjs','tests/api-stability/sequence-model.mjs'],['Every command pair under delayed network/output and replacement','Browser activation, backgrounding and device changes across all routes']),
 group('observation',player('state subscribe addEventListener removeEventListener properties diagnostics capabilities mediaInfo surface host getStats getPlaybackExplanation audioDiagnostics'),'Publish immutable current-source observations and retire subscriptions','idle, active, replaced, destroyed','observer throws, reentry, stale backend events','All routed backends; raw diagnostics differ',
 ['tests/api-stability/player-publication-state.mjs','tests/api-stability/player-projection.mjs','tests/roadmap-contracts.mjs'],['tests/public-api.mjs','tests/api-stability/browser.mjs'],['Event ordering and every state projection under live faults','Raw properties/audio diagnostics are not individually audited here']),
 group('routing',player('mode automaticSelection setMode setAutomaticSelection trackPolicy setVideoFilters setAudioFilters setAudioGain setToneMapping setWatchdogs watchdogs'),'Admit compatible routes and preserve intent/settings across transitions','unloaded, active, selecting, recovering, retired','unsupported capability, asset failure, source replacement','Route-dependent Native, Hybrid, Software',
 ['tests/api-stability/player-route-adversarial.mjs','tests/api-stability/settings-routing-core.mjs','tests/api-stability/startup-adversarial-sequences.mjs'],['tests/automatic-selection.mjs','tests/api-stability/sequence-model.mjs'],['Live recovery for every filter/codec/provider combination','Concurrent route change with attachment, preview and network failures']),
 group('preparation',player('prepare preparationReady preparationProgress'),'Share/cancel preparation and report progress without reviving retired owners','unprepared, preparing, ready, failed, destroyed','fetch failure, cancellation, concurrent consumers','Asset/provider dependent',
 ['tests/api-stability/engine-preparation-state.mjs','tests/engine-preparation.mjs'],['tests/asset-deployment-browser.mjs'],['Cross-browser cancellation during compile/instantiate','Cache corruption and deployment revision changes']),
 group('tracks-attachments',player('selectTrack selectAudioTrack selectSubtitleTrack subtitleVisible addSubtitle attachSubtitle addFont attachFont addTextTrack attachTextTrack removeAttachment'),'Keep track intent and attachment identity scoped to the accepted source','opening, ready, replacing, destroyed','forged/stale handle, partial attachment, superseded selection','Native text/ASS, Hybrid, Software, Shaka have different support',
 ['tests/api-stability/attachment-state.mjs','tests/api-stability/track-selection-state.mjs','tests/track-policy.mjs'],['tests/roadmap-browser.mjs','tests/api-stability/browser.mjs','tests/native-subtitle-selection-timing.mjs'],['Live attach/remove/select races across every supported backend','Missing fonts, failed subtitle transfers and source replacement combinations']),
 group('timing-style',player('getTimingSettings setSubtitleDelay setAudioDelay setSubtitleStyle'),'Validate timing/style settings and apply effective values on supported routes','idle, ready, switching, destroyed','invalid values, backend rejection, retired setting','Capability dependent; plain-text style scope',
 ['tests/api-stability/settings-transactions.mjs','tests/api-stability/advanced-controls-state.mjs'],['tests/api-stability/advanced-settings.mjs','tests/roadmap-browser.mjs'],['Actual subtitle/audio synchronization after overlapping timing changes','Explicit unsupported-route and style coverage per browser']),
 group('buffering',player('getBuffering setBuffering'),'Resolve requested buffering policy into route-specific effective state','paused, playing, buffering, replacing','invalid policy, configure rejection, source retirement','Native hints versus mpv/Shaka controls',
 ['tests/buffering-policy.mjs','tests/shaka-backend.mjs'],['tests/buffering/runtime-policy-browser.mjs'],['Live transfer interruption during policy changes','Authentication refresh and memory pressure across streaming routes']),
 group('streaming-quality',[...player('getStreamingState setQuality seekToLive'),'.#defaultQualitySelection'],'Constrain quality by source/audio intent and restore failed configurations','loaded, selecting, buffering, live, retired','configure/select/verify failure, rollback failure, supersession','Shaka; other routes capability-gated',
 ['tests/quality-switching.mjs','tests/shaka-backend.mjs','tests/api-stability/shaka-selection.mjs','tests/api-stability/remaining-policy-sequences.mjs'],['tests/shaka-lifecycle.mjs'],['Cross-browser quality/audio races under segment failures','Live-edge movement and authorization refresh during rollback']),
 group('ranges-output',player('seekChapter getPlaybackRange setPlaybackRange getLoop setLoop stepFrame snapshot resize'),'Keep range/loop/chapter actions source-scoped and expose actual image output','paused, playing, boundary, replaced, destroyed','invalid range, stale chapter, unsupported frame step, snapshot retirement','Feature-dependent Native, Hybrid, Software',
 ['tests/roadmap-contracts.mjs','tests/api-stability/playback-boundary.mjs','tests/api-stability/player-actions.mjs'],['tests/roadmap-browser.mjs','tests/api-stability/browser.mjs'],['Boundary combinations with reverse step, EOF, source replacement and resize','Live snapshot cancellation and pixel correctness on every supported route']),
 group('audio-device',player('getAudioOutputDevice setAudioOutputDevice'),'Select an output device with capability and permission checks','active, changing device, retired','unsupported sink, permission rejection, device failure','Browser/device capability dependent',
 ['tests/api-stability/player-actions.mjs'],['tests/roadmap-browser.mjs'],['Real device removal, permission revocation and repeated changes','Per-browser physical routing and audible output remain unverified']),
 group('preview-facade',player('preview'),'Expose source-scoped image requests and cache controls','idle, paused, playing, seeking, replacing, destroyed','abort, stale completion, cache pressure, provider failure','Browser/remux/software/authored/Shaka providers',
 ['tests/preview-facade.mjs','tests/api-stability/preview-route-isolation.mjs'],['tests/preview-browser.mjs','tests/preview-software.mjs','tests/preview-shaka-browser.mjs'],['Provider fallback during live network/decoder failures','All exact-time and cache-boundary combinations across browsers']),
 group('preview-controller',symbol('.','PreviewController','addProvider cacheLimits clear destroy diagnostics drain enabled getFrame prefetch request setCacheLimits setDuration setPlaybackActive setPlaybackPosition setProviders setSourceIdentity setStrategy setSuspended strategy unload'),'Arbitrate callers, providers, generation and bounded cache ownership','queued, active, suspended, retired','late provider, aborted caller, invalid output, resource acquisition failure','Provider independent',
 ['tests/api-stability/preview-core.mjs','tests/api-stability/consumer-preview-acquisition.mjs','tests/api-stability/remaining-policy-sequences.mjs'],['tests/preview-options-browser.mjs','tests/preview-ui.mjs'],['Every public mutator during an in-flight live request','Repeated provider replacement and failed cancellation']),
 group('preview-providers',[...symbol('.','LocalVideoPreviewProvider','allowDuringPlayback canHandle getFrame id priority requiresDecoder'),...symbol('.','AuthoredPreviewProvider','canHandle getFrame id priority'),...symbol('.','SoftwarePreviewProvider','canHandle getFrame id priority requiresDecoder')],'Produce validated preview images and release temporary resources','loading, seeking, decoding, cancelled, complete','bad media, cancellation, cleanup failures','Authored, local browser, software',
 ['tests/preview.mjs','tests/api-stability/remaining-policy-sequences.mjs'],['tests/api-stability/live-boundary-scenarios.mjs','tests/preview-software.mjs'],['Software cancellation at actual decoder output and worker failure','Authored callback reentry and mutable metadata in live hosts']),
 group('presentation',[...player('presentation'),...symbol('.','PlayerPresentation','destroy exitFullscreen exitPictureInPicture locksSurface requestFullscreen requestPictureInPicture setFullscreenTarget setMediaSessionEnabled state')],'Own fullscreen/PiP/media-session transitions without destroying borrowed playback','idle, entering, active, exiting, destroyed','permission rejection, unsupported API, late browser completion','Browser/API dependent',
 ['tests/roadmap-contracts.mjs','tests/api-stability/presentation-state.mjs'],['tests/integration-presentation.mjs','tests/player-presentation.mjs'],['Shipping Safari and OS media-session/device interactions','Fullscreen/PiP races with destruction and tab backgrounding']),
 group('inspection',symbol('.','inspectMedia','@'),'Inspect bounded custom/local sources without taking borrowed ownership','reading, cancelled, complete','short read, identity change, read failure, budget exceeded','Source inspection, before route selection',
 ['tests/roadmap-contracts.mjs','tests/api-stability/byte-reader.mjs','tests/api-stability/live-fault-server-contracts.mjs'],['tests/roadmap-browser.mjs','tests/api-stability/live-network-scenarios.mjs'],['Custom-source inspection races, cross-origin credentials and repeated authorization failures beyond the local HTTP cases']),
 group('bindings',[...symbol('./integration','subscribeSelector','@'),...symbol('./integration','bindPlayer','@'),...symbol('./integration','createPlayerBinding','@'),...symbol('./integration','PlaybackBinding','diagnostics dispose disposed pause play run seek setMuted setPlaybackRate setVolume sourceAuthority state subscribe')],'Forward commands and preserve owned/borrowed lifetimes','bound, active, disposed','observer throws, late failure, reentrant disposal','Backend independent',
 ['tests/integration.mjs','tests/api-stability/binding-state.mjs'],['tests/integration-browser.mjs','tests/api-stability/browser.mjs'],['Host-framework remount and event races across all browsers']),
 group('media-element',[...symbol('./media-element','registerMediaElement','@'),...symbol('./media-element','DemuxeMediaElement','bind buffered currentSrc currentTime disconnectedCallback dispose duration ended error muted pause paused play playbackRate seekable seeking src state volume')],'Project media semantics and detach borrowed bindings','unbound, bound, disconnected, disposed','invalid ranges, stale event, ownership mismatch','Backend independent DOM facade',
 ['tests/integration.mjs','tests/api-stability/element-lifecycle-state.mjs'],['tests/integration-browser.mjs','tests/api-stability/browser.mjs'],['Attribute/property/event ordering during live rebind and DOM adoption']),
 group('player-element',[...symbol('./player','definePlayerElement','@'),...symbol('./player','defaultLabels','@'),...symbol('./player','DemuxePlayerElement','addSubtitle allowFileDrop assetBase attributeChangedCallback audioPlayback autoplay close connectedCallback controls controlsMode controlsAutoHideDelay destroy disconnectedCallback labels layout muted open pause play player poster previewOptions previewThumbnails ready seek seekStep selectAudioTrack selectSubtitleTrack setMuted setPlaybackRate setVolume showDiagnostics showSourceControls src theme titleMode trackPolicy watchdogs'), './player#DemuxePlayerElement.static observedAttributes'],'Keep custom-element options, controls and player ownership coherent','disconnected, connecting, active, remounted, destroyed','invalid attribute, late construction, acquisition failure','DOM UI over routed backends',
 ['tests/api-stability/element-configuration-state.mjs','tests/api-stability/element-controls-state.mjs','tests/api-stability/consumer-review.mjs'],['tests/player-component.mjs','tests/player-presentation.mjs','tests/player-mobile.mjs'],['Per-member UI assertions are not individually mapped yet','Keyboard, accessibility, focus and touch combinations across browsers']),
 group('videojs',symbol('./adapters/videojs','registerVideojsTech','@'),'Adapt borrowed/owned player lifetime to Video.js','registered, bound, disposed','cross-document owner, registration/reentry failure','External Video.js host',
 ['tests/integration.mjs','tests/api-stability/videojs-state.mjs'],['tests/integration-browser.mjs'],['Version-specific Video.js live remount and source-error recovery']),
 group('components',[...['audioRepairRecipe','g726RawRepairRecipe','packetCopyRecipe','webmPacketCopyRecipe','parseProviderDeployment','executeComponentBinding','selectComponentBinding'].flatMap(name=>symbol('./components',name,'@')),...symbol('./components','ProviderAcquisition','acquire catalog dispose readAsset resolve')],'Select admitted provider recipes and bound asset acquisition','unresolved, acquiring, executing, disposed','missing asset, unsupported codec, stale owner, corrupt response','Qualified component/codec/deployment combinations only',
 ['tests/component-selection.mjs','tests/provider-acquisition.mjs','tests/provider-owner-failures.mjs'],['tests/bundle-playback.mjs','tests/provider-conformance-installed.mjs'],['Complete recipe/codec/browser/deployment cross-product is not qualified','Cancellation and corrupt assets during execution in installed consumers']),
 group('public-constants-errors',[...['PLAYBACK_MODES','PLAYER_EVENTS','CUSTOM_SOURCE_PLAYBACK_LIMIT'].flatMap(name=>symbol('.',name,'@')),...symbol('.','PlayerError','toJSON')],'Expose stable constants and serializable public error data','import, error construction, serialization','invalid/hostile error payload','Backend independent',
 ['tests/api-stability/contracts.mjs','tests/api-stability/error-classification.mjs'],[],['Constant values and every error-code payload need a dedicated member-level assertion audit'])
];
export const recentLiveEvidence={
 receipts:['results/api-stability/live-boundaries/chromium-1791247593436/result.json','results/api-stability/live-boundaries/firefox-1791247637804/result.json','results/api-stability/live-boundaries/webkit-1791247455926/result.json'],
 // Only explicitly asserted members receive evidence; incidental calls are not coverage.
 members:{'.#inspectMedia':['network-inspection-cancel','network-auth-cancel','network-auth-success','network-auth-rejected'],'.#Player.openRemote':['network-player-open-cancel','network-player-auth-destroy'],'.#Player.open':['network-player-open-cancel'],'.#LocalVideoPreviewProvider.getFrame':['preview-success','preview-abort-load','preview-abort-seek','preview-invalid-media'],'.#Player.destroy':['network-player-auth-destroy','destroy-during-open','destroy-command-burst','hybrid-destroy-during-open','hybrid-destroy-command-burst','software-destroy-during-open','software-destroy-command-burst'],'.#Player.isDestroyed':['destroy-command-burst','hybrid-destroy-command-burst','software-destroy-command-burst'],'.#Player.subscribe':['destroy-command-burst','hybrid-destroy-command-burst','software-destroy-command-burst']}
};
