// SPDX-License-Identifier: Apache-2.0
// Independent host libavformat experiment, not a Demuxe native/Wasm change.
#include <libavformat/avformat.h>
#include <libavutil/sha.h>
#include <libavutil/time.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef struct{uint8_t *data;int64_t size,pos,read_bytes;int reads,seeks;} Reader;
static int read_bytes(void *opaque,uint8_t *out,int n){Reader*r=opaque;if(r->pos>=r->size)return AVERROR_EOF;if(n>r->size-r->pos)n=r->size-r->pos;memcpy(out,r->data+r->pos,n);r->pos+=n;r->read_bytes+=n;r->reads++;return n;}
static int64_t seek_bytes(void*opaque,int64_t off,int whence){Reader*r=opaque;if(whence==AVSEEK_SIZE)return r->size;int w=whence&~AVSEEK_FORCE;int64_t p=w==SEEK_SET?off:w==SEEK_CUR?r->pos+off:w==SEEK_END?r->size+off:-1;if(p<0||p>r->size)return -1;r->pos=p;r->seeks++;return p;}
int main(int argc,char**argv){if(argc!=3)return 2;av_log_set_level(AV_LOG_ERROR);int64_t begin=av_gettime_relative();FILE*f=fopen(argv[1],"rb");if(!f)return 3;fseek(f,0,SEEK_END);Reader r={.size=ftell(f)};fseek(f,0,SEEK_SET);r.data=av_malloc(r.size);if(fread(r.data,1,r.size,f)!=r.size)return 4;fclose(f);AVIOContext*io=avio_alloc_context(av_malloc(32768),32768,0,&r,read_bytes,NULL,seek_bytes);AVFormatContext*in=avformat_alloc_context();in->pb=io;in->flags|=AVFMT_FLAG_CUSTOM_IO;int status=avformat_open_input(&in,NULL,NULL,NULL);if(status<0)return 5;if(avformat_find_stream_info(in,NULL)<0)return 6;int v=av_find_best_stream(in,AVMEDIA_TYPE_VIDEO,-1,-1,NULL,0);if(v<0)return 7;double target=atof(argv[2]);int64_t ts=(int64_t)(target/av_q2d(in->streams[v]->time_base));if(av_seek_frame(in,v,ts,AVSEEK_FLAG_BACKWARD)<0)return 8;AVPacket*p=av_packet_alloc();struct AVSHA*sha=av_sha_alloc();av_sha_init(sha,256);int packets=0;int64_t first_pts=0,first_dts=0;while(packets<24&&(status=av_read_frame(in,p))>=0){if(p->stream_index==v){if(!packets){first_pts=p->pts;first_dts=p->dts;}av_sha_update(sha,p->data,p->size);av_sha_update(sha,(uint8_t*)&p->pts,sizeof(p->pts));av_sha_update(sha,(uint8_t*)&p->dts,sizeof(p->dts));av_sha_update(sha,(uint8_t*)&p->duration,sizeof(p->duration));packets++;}av_packet_unref(p);}uint8_t hash[32];av_sha_final(sha,hash);av_free(sha);av_packet_free(&p);avformat_close_input(&in);av_freep(&io->buffer);avio_context_free(&io);av_free(r.data);int64_t elapsed=av_gettime_relative()-begin;printf("{\"packets\":%d,\"firstPTS\":%lld,\"firstDTS\":%lld,\"sourceBytes\":%lld,\"avioReadBytes\":%lld,\"readCalls\":%d,\"seekCalls\":%d,\"microseconds\":%lld,\"sha256\":\"",packets,(long long)first_pts,(long long)first_dts,(long long)r.size,(long long)r.read_bytes,r.reads,r.seeks,(long long)elapsed);for(int i=0;i<32;i++)printf("%02x",hash[i]);printf("\",\"libavformatVersion\":%u}\n",avformat_version());return packets==24?0:9;}
