// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';
import {readFile,writeFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {execFileSync,spawn} from 'node:child_process';
const out=process.argv[2],mode=process.argv[3]||'timer';
const server=createServer(async(q,r)=>{if(q.url==='/source.ivf'){r.end(await readFile(out+'/source.ivf'));}else{r.setHeader('Content-Type','text/html');r.end('<body style="margin:0;background:black"><video id="v" muted autoplay playsinline style="width:640px;height:360px"></video></body>')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser,cdp,capture,captureDone,result={mode};
try{
 browser=await chromium.launch({channel:'chrome',headless:false,args:['--autoplay-policy=no-user-gesture-required']});const page=await browser.newPage({viewport:{width:700,height:420}});await page.goto('http://127.0.0.1:'+server.address().port);cdp=await browser.newBrowserCDPSession();result.version=await cdp.send('Browser.getVersion');const processes=(await cdp.send('SystemInfo.getProcessInfo')).processInfo;result.foreground=JSON.parse(execFileSync('/tmp/demuxe-display-foreground',[String(processes.find(p=>p.type==='browser').id)],{encoding:'utf8'}));
 result.setup=await page.evaluate(async()=>{
  const bytes=new Uint8Array(await(await fetch('/source.ivf')).arrayBuffer()),view=new DataView(bytes.buffer);let errors=[];window.frames=[];
  const decoder=new VideoDecoder({output:f=>frames.push(f),error:e=>errors.push(String(e))});decoder.configure({codec:'vp8',codedWidth:view.getUint16(12,true),codedHeight:view.getUint16(14,true)});
  for(let o=32;o<bytes.length;){const n=view.getUint32(o,true),ts=Number(view.getBigUint64(o+4,true));const d=bytes.slice(o+12,o+12+n);decoder.decode(new EncodedVideoChunk({type:(d[0]&1)?'delta':'key',timestamp:Math.round(ts*1e6/24),data:d}));o+=12+n;}await decoder.flush();decoder.close();
  window.generator=new MediaStreamTrackGenerator({kind:'video'});window.writer=generator.writable.getWriter();v.srcObject=new MediaStream([generator]);v.play().catch(e=>errors.push(String(e)));const oracle=[];const c=new OffscreenCanvas(640,360),ctx=c.getContext('2d',{willReadFrequently:true});for(const f of frames){ctx.drawImage(f,0,0,640,360);const b=ctx.getImageData(0,0,640,360).data,g=[];for(let y=0;y<18;y++)for(let x=0;x<32;x++){const o=((y*20+10)*640+(x*20+10))*4;g.push(Math.floor((b[o]+b[o+1]+b[o+2])/3));}oracle.push({pts:f.timestamp,grid:g});}return{frames:frames.length,errors,first:frames[0].timestamp,last:frames.at(-1).timestamp,oracle};
 });
 if(process.env.CAPTURE==='1'){capture=spawn('/tmp/demuxe-display-capture',[String(processes.find(p=>p.type==='browser').id),out+'/captured.jsonl','6']);let log='';captureDone=new Promise(resolve=>capture.on('close',code=>{result.captureExit=code;resolve();}));await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('capture readiness timeout')),12000);capture.stdout.on('data',b=>{log+=b;if(log.includes('CAPTURE_READY')){clearTimeout(timeout);resolve();}});capture.stderr.on('data',b=>log+=b);capture.on('close',code=>{clearTimeout(timeout);if(code)reject(Error(log));});});result.captureStarted=true;captureDone.then(()=>writeFile(out+'/capture.log',log));}
 await cdp.send('Tracing.start',{categories:'media,benchmark,graphics.pipeline,blink.user_timing,viz,cc,gpu,disabled-by-default-display.framedisplayed,disabled-by-default-devtools.timeline.frame',options:'record-continuously',transferMode:'ReturnAsStream'});
 result.execution=await page.evaluate(async mode=>{
  const events=[],callbacks=[];let closed=0,issued=0;const start=performance.now()+200;let stop=false;
  const callback=(now,m)=>{callbacks.push({now,mediaTime:m.mediaTime,presentedFrames:m.presentedFrames,expectedDisplayTime:m.expectedDisplayTime});if(!stop)v.requestVideoFrameCallback(callback)};v.requestVideoFrameCallback(callback);
  const issue=async i=>{const selected=mode==='wrong-order'?(i===24?25:i===25?24:i):i;const f=frames[selected].clone();events.push({index:i,pts:f.timestamp,now:performance.now(),target:start+i*1000/24});performance.mark('SOURCE-'+i+'-'+f.timestamp);await writer.write(f);f.close();closed++;issued++;};
  if(mode!=='raf'){for(let i=0;i<frames.length;i++){if(mode==='cancel'&&i===12)break;await new Promise(r=>setTimeout(r,Math.max(0,start+i*1000/24*(mode==='wrong-speed'?0.8:1)-performance.now())));await issue(i);}}
  else{await new Promise((resolve,reject)=>{let i=0;const tick=async now=>{try{while(i<frames.length && start+i*1000/24<=now+8.333){await issue(i++);}if(i<frames.length)requestAnimationFrame(tick);else resolve();}catch(e){reject(e)}};requestAnimationFrame(tick)});}
  await new Promise(r=>setTimeout(r,500));stop=true;await writer.close();generator.stop();for(const f of frames)f.close();v.srcObject=null;return{events,callbacks,issued,closed,sourceFramesClosed:frames.length,trackEnded:generator.readyState==='ended',duration:performance.now()-start};
 },mode);
 const completed=new Promise(r=>cdp.once('Tracing.tracingComplete',r));await cdp.send('Tracing.end');const{stream}=await completed;let trace='';while(true){const p=await cdp.send('IO.read',{handle:stream});trace+=p.base64Encoded?Buffer.from(p.data,'base64').toString():p.data;if(p.eof)break;}await cdp.send('IO.close',{handle:stream});await writeFile(out+'/trace.json',trace);result.passed=true;
}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{if(captureDone)await captureDone;await browser?.close();await new Promise(r=>server.close(r));await writeFile(out+'/results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({mode,passed:result.passed,error:result.error,frames:result.execution?.issued,callbacks:result.execution?.callbacks.length}));}
