// SPDX-License-Identifier: Apache-2.0
#include <vector>
#include <array>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <cstdint>
#include <algorithm>
struct Tile{uint32_t offset;uint16_t base;uint8_t wide;uint8_t pad;};
struct Owner{std::vector<Tile>tiles;std::vector<uint8_t>packed;std::vector<uint16_t>raw;uint64_t generation=0;size_t wideCount=0;void close(){std::vector<Tile>().swap(tiles);std::vector<uint8_t>().swap(packed);std::vector<uint16_t>().swap(raw);generation++;}void build(const uint16_t*p){generation++;wideCount=0;tiles.resize(64);size_t bytes=0;for(int ty=0;ty<8;ty++)for(int tx=0;tx<8;tx++){uint16_t lo=1023,hi=0;for(int y=0;y<16;y++)for(int x=0;x<16;x++){auto v=p[(ty*16+y)*128+tx*16+x];if(v>1023)throw std::runtime_error("depth");lo=std::min(lo,v);hi=std::max(hi,v);}auto&t=tiles[ty*8+tx];t={uint32_t(bytes),lo,uint8_t(hi-lo>255),0};wideCount+=t.wide;bytes+=t.wide?512:256;}if(bytes+tiles.capacity()*sizeof(Tile)>=32768){raw.assign(p,p+16384);std::vector<Tile>().swap(tiles);std::vector<uint8_t>().swap(packed);return;}std::vector<uint16_t>().swap(raw);packed.resize(bytes);for(int ty=0;ty<8;ty++)for(int tx=0;tx<8;tx++){auto&t=tiles[ty*8+tx];for(int y=0;y<16;y++)for(int x=0;x<16;x++){auto v=p[(ty*16+y)*128+tx*16+x];size_t i=t.offset+(y*16+x)*(t.wide?2:1);if(t.wide){packed[i]=v&255;packed[i+1]=v>>8;}else packed[i]=v-t.base;}}}uint16_t at(size_t i)const{if(i>=16384)throw std::runtime_error("index");if(!raw.empty())return raw[i];if(tiles.empty())throw std::runtime_error("retired");size_t x=i%128,y=i/128;auto&t=tiles[(y/16)*8+x/16];size_t j=(y%16)*16+x%16;return t.wide?uint16_t(packed[t.offset+j*2]|(packed[t.offset+j*2+1]<<8)):uint16_t(t.base+packed[t.offset+j]);}uint16_t read(size_t i,uint64_t expected)const{if(expected!=generation)throw std::runtime_error("stale owner");return at(i);}size_t allocated()const{return sizeof(*this)+tiles.capacity()*sizeof(Tile)+packed.capacity()+raw.capacity()*2;}};
std::vector<uint16_t>load(const char*path){std::ifstream f(path,std::ios::binary|std::ios::ate);size_t n=f.tellg();f.seekg(0);std::vector<uint16_t>b(n/2);f.read((char*)b.data(),n);if(!f)throw std::runtime_error("input");return b;}
template<class F>uint64_t filter(F value,const uint16_t*reference){uint64_t digest=0;size_t k=0;for(int y=1;y<127;y++)for(int x=1;x<127;x++){unsigned sum=0;for(int dy=-1;dy<=1;dy++)for(int dx=-1;dx<=1;dx++)sum+=value((y+dy)*128+x+dx);uint16_t v=sum/9;if(v!=reference[k++])throw std::runtime_error("filter mismatch");digest=digest*131+v;}return digest;}
int main(int argc,char**argv){if(argc!=4)return 2;try{auto data=load(argv[1]),oracle=load(argv[2]);if(data.size()!=31*24576||oracle.size()!=31*15876)return 3;std::string mode=argv[3];size_t peak=0,wide=0;uint64_t digest=0;bool checker=false,stale=false,index=false,depth=false;std::array<Owner,3>owners;std::array<std::vector<uint16_t>,3>dense;int count=mode=="check"?31:30;for(int n=0;n<count;n++){const uint16_t*p=data.data()+n*24576,*ref=oracle.data()+n*15876;if(mode=="baseline"){auto&b=dense[n%3];b.assign(p,p+16384);digest^=filter([&](size_t i){return b[i];},ref);size_t bytes=sizeof(dense);for(auto&x:dense)bytes+=x.capacity()*2;peak=std::max(peak,bytes);}else{auto&o=owners[n%3];o.build(p);wide+=o.wideCount;if(mode=="check"){for(size_t i=0;i<16384;i++)if(o.at(i)!=p[i])throw std::runtime_error("plane mismatch");if(n==30)checker=o.wideCount==64&&!o.raw.empty()&&o.packed.capacity()==0&&o.tiles.capacity()==0;}digest^=filter([&](size_t i){return o.at(i);},ref);size_t bytes=0;for(auto&x:owners)bytes+=x.allocated();peak=std::max(peak,bytes);}}if(mode=="check"){auto&o=owners[0];auto token=o.generation;o.build(data.data());try{o.read(0,token);}catch(...){stale=true;}try{o.at(16384);}catch(...){index=true;}auto bad=std::vector<uint16_t>(data.begin(),data.begin()+16384);bad[0]=1024;try{o.build(bad.data());}catch(...){depth=true;}}for(auto&o:owners)o.close();for(auto&b:dense)std::vector<uint16_t>().swap(b);for(auto&o:owners)if(o.packed.capacity()||o.raw.capacity()||o.tiles.capacity())return 4;std::cout<<"{\"mode\":\""<<mode<<"\",\"frames\":"<<count<<",\"owned_peak_bytes\":"<<peak<<",\"wide_tiles\":"<<wide<<",\"digest\":\""<<digest<<"\",\"checkerboard_raw_fallback\":"<<(checker?"true":"false")<<",\"stale_rejected\":"<<(stale?"true":"false")<<",\"index_rejected\":"<<(index?"true":"false")<<",\"depth_rejected\":"<<(depth?"true":"false")<<",\"owners_released\":true}\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 5;}}
