// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import http from 'node:http';import fs from 'node:fs/promises';
const dir=process.argv[2],input=JSON.parse(await fs.readFile('results/top100/alpha/input.json'));let browser;const result={};const server=http.createServer((q,r)=>r.end('<html></html>'));await new Promise(r=>server.listen(0,'127.0.0.1',r));
try{browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);result.probe=await page.evaluate(async input=>{
let generation=0,frames=[[],[]],decoders=[],closedFrames=0,outputFrames=0;const errors=[];const config={codec:'vp8',codedWidth:32,codedHeight:32,colorSpace:{primaries:'smpte170m',transfer:'bt709',matrix:'smpte170m',fullRange:false}};
function close(f){f.close();closedFrames++;}
function reset(){generation++;for(const a of frames)for(const f of a)close(f);frames=[[],[]];for(const d of decoders)if(d.state!=='closed')d.close();const epoch=generation;decoders=[0,1].map(k=>{const d=new VideoDecoder({output:f=>{outputFrames++;if(epoch!==generation)close(f);else frames[k].push(f)},error:e=>errors.push(String(e))});d.configure(config);return d});}
function enqueue(n,maskN=n){for(let k=0;k<2;k++){const pair=input.pairs[k?maskN:n];decoders[k].decode(new EncodedVideoChunk({type:'key',timestamp:pair.timestamp*1000,data:new Uint8Array(pair[k?'alpha':'color'])}));}}
async function present(n){await Promise.all(decoders.map(d=>d.flush()));const a=frames[0].shift(),b=frames[1].shift();try{if(!a||!b||a.timestamp!==b.timestamp||a.displayWidth!==b.displayWidth||a.displayHeight!==b.displayHeight)throw Error('unpaired output');const canvas=new OffscreenCanvas(32,32),ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(a,0,0);const rgba=ctx.getImageData(0,0,32,32),raw=new Uint8Array(b.allocationSize()),layout=await b.copyTo(raw);for(let y=0;y<32;y++)for(let x=0;x<32;x++)rgba.data[(y*32+x)*4+3]=raw[layout[0].offset+y*layout[0].stride+x];ctx.putImageData(rgba,0,0);const shown=ctx.getImageData(0,0,32,32).data;let alphaMax=0,premultMax=0;for(let i=0;i<shown.length;i+=4){alphaMax=Math.max(alphaMax,Math.abs(shown[i+3]-input.rgba[n][i+3]));for(let c=0;c<3;c++)premultMax=Math.max(premultMax,Math.abs(shown[i+c]*shown[i+3]/255-input.rgba[n][i+c]*input.rgba[n][i+3]/255));}canvas.width=canvas.height=0;if(alphaMax>2||premultMax>3)throw Error('presented alpha fidelity');return {frame:n,timestamp:a.timestamp,alphaMax,premultMax};}finally{if(a)close(a);if(b)close(b);}}
reset();for(let i=0;i<3;i++)enqueue(i);const canceled=Promise.all(decoders.map(d=>d.flush())).then(()=>false,()=>true);reset();const canceledFlushRejected=await canceled;const afterReset=[];for(const n of [2,0,1,0]){enqueue(n);afterReset.push(await present(n));}
reset();enqueue(0,1);let unpairedRejected=false;try{await present(0)}catch(e){unpairedRejected=/unpaired/.test(String(e))}reset();enqueue(2);const afterBadSource=await present(2);for(const d of decoders)d.close();generation++;for(const a of frames)for(const f of a)close(f);if(!canceledFlushRejected||!unpairedRejected||errors.length||closedFrames!==outputFrames)throw Error('lifecycle controls');return {canceledFlushRejected,afterReset,unpairedRejected,afterBadSource,outputFrames,closedFrames,decoderStates:decoders.map(d=>d.state),errors,scope:'Actualpaired WebCodecs decoded alpha presented through canvas, backward keyframe seeks, source generation cancellation/reset and recovery; no arbitrary interframe mask dependency claim.'};},input);result.passed=true;}catch(e){result.error=String(e.stack);process.exitCode=1}finally{await browser?.close();server.close();await fs.writeFile(dir+'/results.json',JSON.stringify(result,null,2)+'\n');}console.log(JSON.stringify(result));
