// SPDX-License-Identifier: Apache-2.0
// Dedicated maintained codec checks, additional owner lifecycle checks; no host sniffing.
import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import path from 'node:path';import {webcrypto} from 'node:crypto';import {fileURLToPath} from 'node:url';import {sha} from './package.mjs';import {packetTrimMetadata} from './audio-decoder.mjs';import {decodeProbeHex} from './audio-fixtures.mjs';
export async function runRetainedPacketChecks({adapter,offer,fixture:f}){
 if(offer.profile==='lower-rate-pcm')assert.equal(f.seekContract,'restart-from-start-and-discard','Low-rate legacy requires original predictor restart/discard');
 const speex=offer.capability==='audio.decode.speex'&&offer.profile==='ogg-mono-cbr';
 const pts=packet=>{const original=Math.round(Number(packet.pts_time)*f.sampleRate);if(!speex)return f.codec==='shorten'?0:original;assert.equal(packet.pts,original,'Original Speex packet clock differs');assert.equal(f.packetClockPolicy,'original-ogg-signed-pts');assert.equal(f.codedClockOffset,undefined,'Hidden Speex clock transform forbidden');assert.ok(Number.isSafeInteger(original)&&original>-f.frameSamples,'Original signed Speex clock bounds');return original;};
 const fixtureInputs={},files={},root=f.fixtureRoot??path.dirname(f.input);
 const read=async(filename,digest)=>{assert.ok(path.isAbsolute(filename),'Retained path must be absolute');const b=await readFile(filename);if(digest)assert.equal(sha(b),digest,'Retained bytes changed');fixtureInputs[filename]=sha(b);return b;};await read(f.input,f.inputSHA256);
 for(const [extension,key,digest]of [['json','packetFile','packetSHA256'],['f32','reference','referenceF32SHA256'],['s32','integerReference','referenceSHA256'],['f64','doubleReference','doubleReferenceSHA256']]){const filename=f[key]??root+'/'+f.id+'.'+extension;if(extension==='json'||!f.expectedRejection&&!f.expectedDecodeRejection&&(extension==='f32'||extension==='s32'&&['ape','wavpack','tta','wmalossless','tak','shorten','truehd','mlp','dts-hd','adpcm-ms','adpcm-ima-wav','pcm-alaw','pcm-mulaw','gsm','gsm-ms'].includes(f.codec)||extension==='f64'&&f.codec==='pcm-f64le'))files[extension]=await read(filename,f[digest]);}
 if(files.f32&&f.referenceSamples!==undefined)assert.equal(files.f32.length/(4*f.channels),f.referenceSamples,'Retained declared PCM extent differs');
 if(speex){for(const[key,hash]of [['timingFile','timingSHA256'],['originalTimingFile','originalTimingSHA256'],['referenceBuildFile','referenceBuildSHA256'],['referenceBinary','referenceBinarySHA256']]){assert.ok(f[key]&&/^[a-f0-9]{64}$/.test(f[hash]??''),'Missing independently pinned Speex '+key);await read(f[key],f[hash]);}}
 const pageFile=fileURLToPath(new URL('../codec-expansion-page.mjs',import.meta.url)),page=await readFile(pageFile,'utf8'),context=vm.createContext({document:{querySelector:()=>({})},crypto:webcrypto,Uint8Array,Float32Array,Float64Array,Int32Array,DataView,AbortController,setTimeout,fetch:async url=>{const extension=path.extname(url).slice(1),b=files[extension];assert.ok(b,'Missing retained packet reference');return{json:async()=>JSON.parse(b),arrayBuffer:async()=>Uint8Array.from(b).buffer};}});vm.runInContext(page+'\nglobalThis.runPacket=packet;',context);
 const state={},saved=[],owned=()=>{for(const {view,copy}of saved)assert.deepEqual(view,copy,'Retained packet PCM ownership changed');};
 const api={loadTestModule:async()=>null,PacketAudioDecoder:class{constructor(_module,codec,signal,config){const decoder=adapter.createDecoder({...f,...config,codec},signal);let current=[],original,drains=0;const record=batch=>{for(const frame of batch)current.push({pts:frame.pts,samples:frame.samples,duration:frame.duration,layout:frame.layout,views:[...(frame.planes??[]),...(frame.planes64??[]),...(frame.pcm?[frame.pcm]:[])].map(v=>Array.from(v))});return batch;};return {decode(...args){if(saved.length){assert.deepEqual(saved[0].view,saved[0].copy);assert.deepEqual(saved.at(-1).view,saved.at(-1).copy);}const batch=decoder.decode(...args);for(const frame of batch)for(const view of [...(frame.planes??[]),...(frame.planes64??[]),...(frame.pcm?[frame.pcm]:[])])saved.push({view,copy:view.slice()});return record(batch);},flush(){const batch=record(decoder.flush());owned();if(++drains===2)assert.deepEqual(current,original,'Retained full reset PCM/clock changed');else if(drains===1){original=current;state.first=current;}return batch;},reset(){decoder.reset();owned();current=[];},dispose(){decoder.dispose();owned();}};}}};const result=await context.runPacket(api,'/',f);
 if(!f.expectedRejection&&!f.expectedDecodeRejection){const stream=JSON.parse(files.json).streams.find(s=>s.codec_type==='audio')??JSON.parse(files.json).streams[0],first=JSON.parse(files.json).packets.find(p=>stream.index===undefined||p.stream_index===stream.index),data=decodeProbeHex(first.data),configuration={...f,extradata:decodeProbeHex(stream.extradata),...f.framing};
  const pre=new AbortController();pre.abort();assert.throws(()=>adapter.createDecoder(configuration,pre.signal),'Pre-aborted retained decoder accepted');
  const cancel=new AbortController(),owner=adapter.createDecoder(configuration,cancel.signal);try{owner.decode(data,pts(first));cancel.abort();for(const method of ['decode','flush','reset'])assert.throws(()=>method==='decode'?owner.decode(data,0):owner[method](),'Canceled retained decoder accepted '+method);}finally{owner.dispose();owner.dispose();}for(const method of ['decode','flush','reset'])assert.throws(()=>method==='decode'?owner.decode(data,0):owner[method](),'Disposed retained decoder accepted '+method);
  if(speex){
   const packetData=JSON.parse(files.json),original=JSON.parse(await read(f.originalTimingFile,f.originalTimingSHA256)).frames,timing=JSON.parse(await read(f.timingFile,f.timingSHA256));assert.equal(sha(configuration.extradata),f.extraDataSHA256,'Pinned original Speex header differs');assert.equal(configuration.extradata.length,80);assert.equal(f.nativeFrameDuration,0);assert.equal(timing.toleranceSamples,0);assert.equal(timing.originalFirstPTS,f.originalFirstPTS);assert.equal(timing.codedClockOffset,undefined,'Hidden Speex timing transform forbidden');assert.equal(timing.nativeFrameDuration,0);assert.equal(timing.packetClockPolicy,f.packetClockPolicy);assert.equal(original.length,packetData.packets.length);assert.equal(state.first.length,original.length);assert.equal(timing.segments.length,original.length);
   for(const[i,frame]of state.first.entries()){const coded=pts(packetData.packets[i]);assert.equal(original[i].pts,packetData.packets[i].pts);assert.equal(original[i].nb_samples,f.frameSamples);assert.deepEqual(timing.segments[i],{pts:coded,samples:f.frameSamples});assert.equal(frame.pts,coded);assert.equal(frame.samples,f.frameSamples);assert.equal(frame.duration,0);}
   const reference=new Float32Array(Uint8Array.from(files.f32).buffer);for(const target of [1,Math.floor(f.referenceSamples/2),Math.floor(f.referenceSamples*3/4)]){const replay=adapter.createDecoder(configuration,new AbortController().signal),values=[];try{const collect=frames=>{for(const frame of frames)values.push(...frame.planes[0]);};for(const packet of packetData.packets)collect(replay.decode(decodeProbeHex(packet.data),pts(packet)));collect(replay.flush());assert.equal(values.length,reference.length,'Speex complete coded extent');let maximum=0,error=0,energy=0;for(let i=target;i<reference.length;i++){const d=values[i]-reference[i];maximum=Math.max(maximum,Math.abs(d));error+=d*d;energy+=reference[i]*reference[i];}assert.ok(maximum<7e-5&&energy>0&&10*Math.log10(energy/Math.max(error,1e-30))>80,'Speex original restart/discard reference mismatch');}finally{replay.dispose();}}result.originalClock=true;result.restartDiscardWindows=3;result.clockPolicy=f.packetClockPolicy;
  }
  if(offer.profile==='lower-rate-pcm'){
   assert.ok(f.timingFile&&/^[a-f0-9]{64}$/.test(f.timingSHA256??''),'Low-rate legacy needs independently pinned native timing');const timing=JSON.parse(await read(f.timingFile,f.timingSHA256));if(f.codec==='mp2'||timing.sourceTimeBase!==undefined)assert.equal(timing.sourceTimeBase,stream.time_base,'Independent timing time base differs from original packet stream');const [numerator,denominator]=String(stream.time_base).split('/').map(Number);assert.ok([numerator,denominator].every(n=>Number.isSafeInteger(n)&&n>0),'Missing original native clock quantum');assert.equal(timing.toleranceSamples,f.codec==='mp2'?Math.ceil(f.sampleRate*numerator/denominator/2):0,'Caller-chosen clock tolerance forbidden');assert.ok(Array.isArray(timing.segments)&&timing.segments.length&&Number.isSafeInteger(timing.toleranceSamples)&&timing.toleranceSamples>=0&&timing.toleranceSamples<=Math.ceil(f.sampleRate/1000),'Invalid retained low-rate native timing');
   const metadata=packetTrimMetadata(f.codec,configuration.extradata,JSON.parse(files.json).packets),raw=state.first,rawEnd=raw.reduce((n,x)=>n+x.samples,0)-metadata.discardSamples;let position=0;const actual=raw.flatMap(x=>{const start=Math.max(position,metadata.skipSamples),end=Math.min(position+x.samples,rawEnd),p=position;position+=x.samples;return end>start?[{pts:x.pts+start-p,samples:end-start}]:[];});let a=0,b=0,ao=0,bo=0;assert.ok(actual?.length,'Missing first original decode');for(const s of timing.segments)assert.ok(Number.isSafeInteger(s.pts)&&Number.isSafeInteger(s.samples)&&s.samples>0,'Invalid independent sample clock');
   while(a<actual.length&&b<timing.segments.length){const x=actual[a],y=timing.segments[b];assert.ok(Math.abs(x.pts+ao-y.pts-bo)<=timing.toleranceSamples,'Low-rate original native clock mismatch');const n=Math.min(x.samples-ao,y.samples-bo);ao+=n;bo+=n;if(ao===x.samples){a++;ao=0;}if(bo===y.samples){b++;bo=0;}}assert.equal(a,actual.length);assert.equal(b,timing.segments.length);
   const reference=new Float32Array(Uint8Array.from(files.f32).buffer),packets=JSON.parse(files.json).packets;
   for(const target of [1,Math.floor(reference.length/f.channels/2),reference.length/f.channels-1]){const replay=adapter.createDecoder(configuration,new AbortController().signal),values=[];try{const collect=frames=>{for(const frame of frames)for(let i=0;i<frame.samples*f.channels;i++)values.push(frame.pcm?frame.pcm[i]/2147483648:frame.planes[i%f.channels][Math.floor(i/f.channels)]);};for(const p of packets)collect(replay.decode(decodeProbeHex(p.data),Math.round(Number(p.pts_time)*f.sampleRate)));collect(replay.flush());const presented=values.slice(metadata.skipSamples*f.channels,values.length-metadata.discardSamples*f.channels);assert.equal(presented.length,reference.length,'Restart/discard original sample extent');let maximum=0;for(let i=target*f.channels;i<reference.length;i++)maximum=Math.max(maximum,Math.abs(presented[i]-reference[i]));assert.ok(maximum<2e-5,'Restart/discard reference mismatch');}finally{replay.dispose();}}
   result.originalClock=true;result.restartDiscardWindows=3;
  }
  const invalid=adapter.createDecoder(configuration,new AbortController().signal);try{assert.throws(()=>invalid.decode(new Uint8Array(),0),'Empty retained packet accepted');}finally{invalid.dispose();}
 }
 return {id:f.id,offer,...result,resetExact:!f.expectedRejection&&!f.expectedDecodeRejection,ownership:true,lifecycle:true,cancellation:true,fixtureInputs,harnessInputs:{[pageFile]:sha(Buffer.from(page))},scope:'Exact retained source codec packets using maintained dedicated framing/precision/reset/float controls; no presentation conversion or browser claim'};
}
