// SPDX-License-Identifier: Apache-2.0
#include <openjpeg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef struct{FILE*f,*trace;unsigned char*seen;size_t size,total,reads,seeks;} Source;
static OPJ_SIZE_T readfn(void*out,OPJ_SIZE_T n,void*user){Source*s=user;long pos=ftell(s->f);size_t got=fread(out,1,n,s->f);fprintf(s->trace,"read,%ld,%zu\n",pos,got);s->total+=got;s->reads++;if(got&&pos>=0&&(size_t)pos+got<=s->size)memset(s->seen+pos,1,got);return got?got:(OPJ_SIZE_T)-1;}
static OPJ_OFF_T skipfn(OPJ_OFF_T n,void*user){Source*s=user;long p=ftell(s->f);fprintf(s->trace,"skip,%ld,%lld\n",p,(long long)n);s->seeks++;return fseek(s->f,(long)n,SEEK_CUR)?-1:n;}
static OPJ_BOOL seekfn(OPJ_OFF_T n,void*user){Source*s=user;fprintf(s->trace,"seek,%lld,0\n",(long long)n);s->seeks++;return fseek(s->f,(long)n,SEEK_SET)==0;}
static void errorfn(const char*msg,void*p){(void)p;fputs(msg,stderr);}
int main(int argc,char**argv){if(argc!=10)return 2;Source s={0};s.f=fopen(argv[1],"rb");s.trace=fopen(argv[3],"w");if(!s.f||!s.trace)return 3;fseek(s.f,0,SEEK_END);s.size=ftell(s.f);rewind(s.f);s.seen=calloc(s.size,1);opj_dparameters_t p;opj_set_default_decoder_parameters(&p);p.cp_reduce=atoi(argv[8]);p.cp_layer=atoi(argv[9]);opj_codec_t*c=opj_create_decompress(OPJ_CODEC_J2K);opj_set_info_handler(c,NULL,NULL);opj_set_warning_handler(c,errorfn,NULL);opj_set_error_handler(c,errorfn,NULL);opj_stream_t*stream=opj_stream_create(1024,OPJ_TRUE);opj_stream_set_user_data(stream,&s,NULL);opj_stream_set_user_data_length(stream,s.size);opj_stream_set_read_function(stream,readfn);opj_stream_set_skip_function(stream,skipfn);opj_stream_set_seek_function(stream,seekfn);opj_image_t*image=NULL;int rc=0;unsigned w=0,h=0;int x0=atoi(argv[4]),y0=atoi(argv[5]),x1=atoi(argv[6]),y1=atoi(argv[7]);if(!opj_setup_decoder(c,&p)||!opj_read_header(stream,c,&image)){rc=4;goto done;}if((x1&&(x1>(int)image->x1||x1<=x0))||(y1&&(y1>(int)image->y1||y1<=y0))||x0<0||y0<0){rc=5;goto done;}if(!opj_set_decode_area(c,image,x0,y0,x1,y1)||!opj_decode(c,stream,image)||!opj_end_decompress(c,stream)){rc=6;goto done;}if(image->numcomps!=1||image->comps[0].prec!=8||image->comps[0].sgnd){rc=7;goto done;}w=image->comps[0].w;h=image->comps[0].h;FILE*out=fopen(argv[2],"wb");if(!out){rc=8;goto done;}fprintf(out,"P5\n%u %u\n255\n",w,h);for(size_t i=0;i<(size_t)w*h;i++){int v=image->comps[0].data[i];if(v<0||v>255){rc=9;break;}fputc(v,out);}fclose(out);done:if(image)opj_image_destroy(image);opj_stream_destroy(stream);opj_destroy_codec(c);fclose(s.f);fclose(s.trace);size_t unique=0;for(size_t i=0;i<s.size;i++)unique+=s.seen[i]!=0;free(s.seen);printf("{\"width\":%u,\"height\":%u,\"source_bytes\":%zu,\"unique_read_bytes\":%zu,\"total_read_bytes\":%zu,\"read_calls\":%zu,\"seek_skip_calls\":%zu,\"owners_closed\":true,\"exit\":%d}\n",w,h,s.size,unique,s.total,s.reads,s.seeks,rc);return rc;}
