# SPDX-License-Identifier: Apache-2.0
import pathlib,sys,json,subprocess,os,shutil
out=pathlib.Path(sys.argv[1]).resolve();out.mkdir(parents=True,exist_ok=True);src=pathlib.Path('/Volumes/seed2/Projects/webmpv/build/sources/ffmpeg');obj=pathlib.Path('/Volumes/seed2/Projects/webmpv/build/obj-software-full-ffmpeg');tool=pathlib.Path('/Volumes/seed2/Projects/webmpv/build/emsdk-4.0.14/upstream/emscripten');env=dict(os.environ,EM_CONFIG=str(pathlib.Path('research/shared/runs/20260919T230620Z-software-prefix-libraries/emscripten.config').resolve()),EM_CACHE=str(pathlib.Path('build/research-prefix-emcache').resolve()))
original=(src/'libavcodec/h264_cabac.c').read_text();start=original.index('static av_always_inline void\ndecode_cabac_residual_internal');end=original.index('static av_noinline void decode_cabac_residual_dc_internal',start);body=original[start:end];body=body.replace('get_cabac_bypass_sign(', 'research_sign(').replace('get_cabac_bypass(', 'research_bypass(').replace('get_cabac(', 'research_bin(')
helpers=r'''
/* Research-only explicit logical residual-block sidecar, not an opaque heap snapshot. */
#include <libavutil/sha.h>
#include <libavutil/mem.h>
#include <stddef.h>
#define CP_LIMIT 8
#define CP_TRACE 8192
typedef struct CPRecord {uint32_t magic,version,size,offset;int low,range,cat,n,max_coeff,pixel_shift,field;uint8_t states[1024],nnz[120],scan[64];uint32_t qmul[64];int16_t initial[16];uint8_t source_sha[32],checksum[32];} CPRecord;
typedef struct CPResult {int low,range,offset,trace_count;uint8_t states[1024],nnz[120];int16_t block[16];int trace[CP_TRACE];} CPResult;
static CPRecord records[CP_LIMIT];static CPResult expected[CP_LIMIT],result;static uint8_t*sources[CP_LIMIT];static int stored,enabled=1,seen;static CPResult*active;static uint8_t*state_base;
static void hash_bytes(const void*p,size_t n,uint8_t out[32]){struct AVSHA*s=av_sha_alloc();av_sha_init(s,256);av_sha_update(s,p,n);av_sha_final(s,out);av_free(s);}
static void trace_bin(int kind,int index,int value){if(active){int n=active->trace_count;if(n+3>CP_TRACE){active->trace_count=CP_TRACE+1;return;}active->trace[n]=kind;active->trace[n+1]=index;active->trace[n+2]=value;active->trace_count+=3;}}
static int research_bin(CABACContext*c,uint8_t*s){int v=get_cabac(c,s);trace_bin(0,(int)(s-state_base),v);return v;}
static int research_bypass(CABACContext*c){int v=get_cabac_bypass(c);trace_bin(1,-1,v);return v;}
static int research_sign(CABACContext*c,int v){int r=get_cabac_bypass_sign(c,v);trace_bin(2,v,r);return r;}
static void result_fill(CPResult*r,H264SliceContext*sl,const int16_t*block){r->low=sl->cabac.low;r->range=sl->cabac.range;r->offset=(int)(sl->cabac.bytestream-sl->cabac.bytestream_start);memcpy(r->states,sl->cabac_state,1024);memcpy(r->nnz,sl->non_zero_count_cache,120);memcpy(r->block,block,32);}
static int validate_record(const CPRecord*r,const uint8_t*source,int size){uint8_t digest[32];if(r->magic!=0x43504231||r->version!=1||r->size!=size||size<1||size>1048576||r->offset>=r->size||r->cat!=2||r->n<0||r->n>=16||r->max_coeff!=16||r->pixel_shift||r->field)return -1;hash_bytes(r,offsetof(CPRecord,checksum),digest);if(memcmp(digest,r->checksum,32))return -2;hash_bytes(source,size,digest);if(memcmp(digest,r->source_sha,32))return -3;return 0;}
int cp_count(void){return stored;}int cp_record_size(void){return sizeof(CPRecord);}int cp_result_size(void){return sizeof(CPResult);}void*cp_record(int i){return i>=0&&i<stored?records+i:NULL;}void*cp_oracle(int i){return i>=0&&i<stored?expected+i:NULL;}void*cp_result(void){return &result;}void*cp_source(int i){return i>=0&&i<stored?sources[i]:NULL;}int cp_source_size(int i){return i>=0&&i<stored?records[i].size:0;}int cp_capture(int value){enabled=value;return 0;}int cp_reset(void){for(int i=0;i<stored;i++)av_freep(sources+i);stored=seen=0;active=NULL;return 0;}
int cp_import(const void*record,int size,const uint8_t*source,int n){if(size!=sizeof(CPRecord)||stored==CP_LIMIT)return -4;CPRecord r;memcpy(&r,record,sizeof(r));int check=validate_record(&r,source,n);if(check)return check;uint8_t*copy=av_mallocz(n+AV_INPUT_BUFFER_PADDING_SIZE);if(!copy)return -5;memcpy(copy,source,n);records[stored]=r;sources[stored]=copy;stored++;return 0;}
'''
replay=r'''
int cp_replay(int i,int corrupt){if(i<0||i>=stored)return -6;CPRecord r=records[i];if(corrupt==1)r.states[100]^=2;if(corrupt==2)r.nnz[0]^=1;if(corrupt==3){memset(r.nnz,0,120);hash_bytes(&r,offsetof(CPRecord,checksum),r.checksum);}int valid=validate_record(&r,sources[i],r.size);if(valid)return valid;H264Context*h=av_mallocz(sizeof(*h));H264SliceContext*sl=av_mallocz(sizeof(*sl));if(!h||!sl){av_free(h);av_free(sl);return -5;}int16_t block[16];memcpy(block,r.initial,32);h->pixel_shift=r.pixel_shift;sl->mb_field_decoding_flag=r.field;sl->cabac.low=r.low;sl->cabac.range=r.range;sl->cabac.bytestream_start=sources[i];sl->cabac.bytestream=sources[i]+r.offset;sl->cabac.bytestream_end=sources[i]+r.size;memcpy(sl->cabac_state,r.states,1024);memcpy(sl->non_zero_count_cache,r.nnz,120);memset(&result,0,sizeof(result));active=&result;state_base=sl->cabac_state;decode_cabac_residual_internal(h,sl,block,r.cat,r.n,r.scan,r.qmul,r.max_coeff,0,0);active=NULL;result_fill(&result,sl,block);av_free(sl);av_free(h);return result.trace_count>CP_TRACE?-7:0;}
'''
old='''    decode_cabac_residual_internal(h, sl, block, cat, n, scantable, qmul, max_coeff, 0, 0);'''
new=r'''
    if(!enabled||stored==CP_LIMIT||cat!=2||n<0||n>=16||max_coeff!=16||h->pixel_shift||MB_FIELD(sl)||(seen++%17)!=0){decode_cabac_residual_internal(h,sl,block,cat,n,scantable,qmul,max_coeff,0,0);return;}
    CPRecord*r=&records[stored];memset(r,0,sizeof(*r));r->magic=0x43504231;r->version=1;r->size=sl->cabac.bytestream_end-sl->cabac.bytestream_start;r->offset=sl->cabac.bytestream-sl->cabac.bytestream_start;r->low=sl->cabac.low;r->range=sl->cabac.range;r->cat=cat;r->n=n;r->max_coeff=max_coeff;r->pixel_shift=h->pixel_shift;r->field=MB_FIELD(sl);memcpy(r->states,sl->cabac_state,1024);memcpy(r->nnz,sl->non_zero_count_cache,120);memcpy(r->scan,scantable,16);memcpy(r->qmul,qmul,16*sizeof(uint32_t));memcpy(r->initial,block,32);sources[stored]=av_mallocz(r->size+AV_INPUT_BUFFER_PADDING_SIZE);memcpy(sources[stored],sl->cabac.bytestream_start,r->size);hash_bytes(sources[stored],r->size,r->source_sha);hash_bytes(r,offsetof(CPRecord,checksum),r->checksum);memset(expected+stored,0,sizeof(CPResult));active=expected+stored;state_base=sl->cabac_state;decode_cabac_residual_internal(h,sl,block,cat,n,scantable,qmul,max_coeff,0,0);active=NULL;result_fill(expected+stored,sl,block);stored++;
'''
modified=original[:start]+helpers+body+replay+original[end:];assert modified.count(old)==1;modified=modified.replace(old,new);(out/'snapshots').mkdir(exist_ok=True);path=out/'snapshots/h264_cabac.c';path.write_text(modified);(out/'snapshots/COPYING.LGPLv2.1').write_bytes((src/'COPYING.LGPLv2.1').read_bytes());commands=[]
def run(args):
 r=subprocess.run(args,capture_output=True,text=True,env=env);commands.append({'args':args,'exit':r.returncode,'stderr':r.stderr});(out/'build-results.json').write_text(json.dumps(commands,indent=2));assert r.returncode==0,r.stderr
objout=out/'h264_cabac.o';run([str(tool/'emcc'),'-O3','-pthread','-msimd128','-std=c17','-DHAVE_AV_CONFIG_H','-D_ISOC11_SOURCE','-D_FILE_OFFSET_BITS=64','-D_LARGEFILE_SOURCE','-D_POSIX_C_SOURCE=200112','-D_XOPEN_SOURCE=600','-DZLIB_CONST','-I'+str(obj),'-I'+str(src),'-I'+str(src/'libavcodec'),'-I'+str(src/'compat/stdbit'),'-fno-math-errno','-fno-signed-zeros','-c',str(path),'-o',str(objout)])
archive=out/'libavcodec.a';shutil.copyfile(obj/'libavcodec/libavcodec.a',archive);run([str(tool/'emar'),'r',str(archive),str(objout)])
link=json.loads(pathlib.Path('research/shared/runs/20260919T230620Z-software-prefix-libraries/build-result.json').read_text())['command'];link=[str(archive)if x==str(obj/'libavcodec/libavcodec.a')else str(out/'decoder.mjs')if x.endswith('/decoder.mjs')else x for x in link];exports=['cp_count','cp_record_size','cp_result_size','cp_record','cp_oracle','cp_result','cp_source','cp_source_size','cp_capture','cp_reset','cp_import','cp_replay']
for i,x in enumerate(link):
 if x.startswith('-sEXPORTED_FUNCTIONS='):link[i]='-sEXPORTED_FUNCTIONS='+json.dumps(json.loads(x.split('=',1)[1])+['_'+v for v in exports])
run(link);print('built logical checkpoint decoder',out)
