// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import{readFile,writeFile}from'node:fs/promises';import{createServer}from'node:http';import assert from'node:assert/strict';
const out=process.argv[2],input=JSON.parse(await readFile(out+'/input.json'))['changed-tool'];
const contract={scope:'Actual 4x4 non-DC CABAC residual parsing after coded-block flag; NOT full mid-slice picture restart',workload:'Five alternating cold module pairs; ten requests of eight residual blocks. Candidate includes prefix decode, sidecar creation and source retention, serialization, fresh-module restoration, ten replay sets and cleanup; baseline repeats prefix decode to same eight blocks ten times. Both execute the same instrumentation and export result records. Browser startup excluded equally.',threshold:'median paired candidate/baseline complete component wall time <=0.9 after full independent picture and replay-state correctness'};
await writeFile(out+'/predeclared-contract.json',JSON.stringify(contract,null,2));
const server=createServer(async(q,r)=>{r.setHeader('Cross-Origin-Opener-Policy','same-origin');r.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(q.url==='/'){r.end('<body>');return;}if(!['/decoder.mjs','/decoder.wasm'].includes(q.url)){r.writeHead(404).end();return;}r.setHeader('Content-Type',q.url.endsWith('.wasm')?'application/wasm':'text/javascript');r.end(await readFile(out+q.url));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const result={contract,rows:[]};let browser;
try{browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);
result.correctness=await page.evaluate(async(input)=>{const{default:create}=await import('/decoder.mjs');const m=await create({printErr:()=>{}}),frames=[],jobs=[];m.onFrame=(y,u,v,sy,su,sv,w,h,pts)=>{const b=new Uint8Array(w*h*3/2);for(const [ptr,stride,ww,hh,offset]of[[y,sy,w,h,0],[u,su,w/2,h/2,w*h],[v,sv,w/2,h/2,w*h*5/4]])for(let n=0;n<hh;n++)b.set(m.HEAPU8.subarray(ptr+n*stride,ptr+n*stride+ww),offset+n*ww);jobs.push(crypto.subtle.digest('SHA-256',b).then(x=>frames.push({pts,hash:[...new Uint8Array(x)].map(v=>v.toString(16).padStart(2,'0')).join('')})));};m._vd_init();for(let i=0;i<input.packets.length;i++){let p=input.packets[i],ptr=m._malloc(p.length);m.HEAPU8.set(p,ptr);if(m._vd_packet(ptr,p.length,Math.round(i*1e6/24))<0)throw Error('packet');m._free(ptr);}m._vd_flush();await Promise.all(jobs);frames.sort((a,b)=>a.pts-b.pts);const fullExact=frames.length===30&&frames.every((f,i)=>f.hash===input.hashes[i]);const rs=m._cp_record_size(),os=m._cp_result_size(),records=[];for(let i=0;i<m._cp_count();i++)records.push({record:[...m.HEAPU8.slice(m._cp_record(i),m._cp_record(i)+rs)],oracle:[...m.HEAPU8.slice(m._cp_oracle(i),m._cp_oracle(i)+os)],source:[...m.HEAPU8.slice(m._cp_source(i),m._cp_source(i)+m._cp_source_size(i))]});m._vd_close();m._cp_reset();const n=await create({printErr:()=>{}});n._cp_capture(0);const eq=(a,b)=>a.length===b.length&&a.every((v,i)=>v===b[i]),checks=[];let wrongSource;
for(const row of records){const rp=n._malloc(rs),sp=n._malloc(row.source.length);n.HEAPU8.set(row.record,rp);n.HEAPU8.set(row.source,sp);if(checks.length===0){n.HEAPU8[sp]^=1;wrongSource=n._cp_import(rp,rs,sp,row.source.length);n.HEAPU8.set(row.source,sp);}const imported=n._cp_import(rp,rs,sp,row.source.length),i=checks.length,rc=n._cp_replay(i,0),actual=n.HEAPU8.slice(n._cp_result(),n._cp_result()+os),traceInts=new DataView(actual.buffer).getInt32(12,true);const corruptContext=n._cp_replay(i,1),corruptNeighbor=n._cp_replay(i,2),zeroNeighbor=n._cp_replay(i,3),zero=n.HEAPU8.slice(n._cp_result(),n._cp_result()+os);checks.push({imported,rc,exact:eq([...actual],row.oracle),traceEvents:traceInts/3,corruptContext,corruptNeighbor,zeroNeighbor,missingNeighborChangesState:!eq([...zero],row.oracle)});n._free(rp);n._free(sp);}n._cp_reset();return{fullExact,frames:frames.length,recordBytes:rs,resultBytes:os,wrongSource,checks,records};},input);
const c=result.correctness;assert.ok(c.fullExact&&c.checks.length===8&&c.wrongSource===-3&&c.checks.every(x=>x.imported===0&&x.rc===0&&x.exact&&x.traceEvents>0&&x.corruptContext===-2&&x.corruptNeighbor===-2)&&c.checks.some(x=>x.missingNeighborChangesState),JSON.stringify({...c,records:undefined}));await writeFile(out+'/serialized-sidecars.json',JSON.stringify(c.records));delete c.records;
for(let pair=0;pair<5;pair++)for(const mode of pair%2?['candidate','baseline']:['baseline','candidate']){const pg=await browser.newPage();await pg.goto('http://127.0.0.1:'+server.address().port);const row=await pg.evaluate(async({input,mode})=>{const begin=performance.now(),{default:create}=await import('/decoder.mjs'),m=await create({printErr:()=>{}});m.onFrame=()=>{};let packets=0,exports=0;const prefix=()=>{m._cp_reset();m._cp_capture(1);m._vd_init();for(let i=0;i<input.packets.length&&m._cp_count()<8;i++){const p=input.packets[i],ptr=m._malloc(p.length);m.HEAPU8.set(p,ptr);if(m._vd_packet(ptr,p.length,Math.round(i*1e6/24))<0)throw Error('packet');m._free(ptr);packets++;}if(m._cp_count()!==8)throw Error('checkpoint count');m._vd_close();};const exportOracles=()=>{for(let i=0;i<8;i++){const b=m.HEAPU8.slice(m._cp_oracle(i),m._cp_oracle(i)+m._cp_result_size());exports+=b.length;}};
if(mode==='baseline'){for(let j=0;j<10;j++){prefix();exportOracles();}m._cp_reset();}else{prefix();const records=[];for(let i=0;i<8;i++)records.push({record:m.HEAPU8.slice(m._cp_record(i),m._cp_record(i)+m._cp_record_size()),source:m.HEAPU8.slice(m._cp_source(i),m._cp_source(i)+m._cp_source_size(i))});m._cp_reset();const n=await create({printErr:()=>{}});n._cp_capture(0);for(const row of records){const rp=n._malloc(row.record.length),sp=n._malloc(row.source.length);n.HEAPU8.set(row.record,rp);n.HEAPU8.set(row.source,sp);if(n._cp_import(rp,row.record.length,sp,row.source.length)!==0)throw Error('import');n._free(rp);n._free(sp);}for(let j=0;j<10;j++)for(let i=0;i<8;i++){if(n._cp_replay(i,0)!==0)throw Error('replay');exports+=n.HEAPU8.slice(n._cp_result(),n._cp_result()+n._cp_result_size()).length;}n._cp_reset();}return{mode,ms:performance.now()-begin,packets,exportBytes:exports};},{input,mode});result.rows.push({...row,pair});await pg.close();}const ratios=Array.from({length:5},(_,i)=>result.rows.find(x=>x.pair===i&&x.mode==='candidate').ms/result.rows.find(x=>x.pair===i&&x.mode==='baseline').ms).sort((a,b)=>a-b);result.analysis={medianPairedRatio:ratios[2],range:[ratios[0],ratios[4]],costPassed:ratios[2]<=.9,fullMidSliceRestartImplemented:false};result.passed=true;
}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();await new Promise(r=>server.close(r));await writeFile(out+'/browser-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify({...result,correctness:result.correctness?{...result.correctness,records:undefined}:undefined}));}
