// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const dir=path.resolve(process.argv[2]),setup=JSON.parse(fs.readFileSync(dir+'/setup.json')),server=http.createServer((q,r)=>{const name=decodeURIComponent(q.url).slice(1);if(!name){r.setHeader('Content-Type','text/html');r.end('<!doctype html><title>Chunk decoder</title>');return;}if(name!=='source.flac'&&!setup.chunks.includes(name)){r.writeHead(404).end();return;}r.setHeader('Content-Type','audio/flac');r.end(fs.readFileSync(dir+'/'+name));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser,result={scope:'Prepared independent FLAC chunks, complete sample consumption; not general arbitrary codec segmentation',setup};
try{browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);result.probe=await page.evaluate(async chunks=>{
 const load=n=>fetch('/'+n).then(r=>r.arrayBuffer()),hash=async a=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',a))].map(x=>x.toString(16).padStart(2,'0')).join('');
 const ctx=new AudioContext({sampleRate:48000});let full=await ctx.decodeAudioData(await load('source.flac'));const checks=[];let at=0,wrongRejected=false;
 for(const name of chunks){let b=await ctx.decodeAudioData(await load(name));for(let c=0;c<b.numberOfChannels;c++){const expected=full.getChannelData(c).slice(at,at+b.length);if(await hash(expected.buffer)!==await hash(b.getChannelData(c).buffer))throw Error('chunk mismatch '+name);if(at>0&&await hash(full.getChannelData(c).slice(at-1,at-1+b.length).buffer)!==await hash(expected.buffer))wrongRejected=true;}checks.push({name,frames:b.length,channels:b.numberOfChannels});at+=b.length;b=null;}
 if(at!==full.length||!wrongRejected)throw Error('count/control');const wholeFrames=full.length;full=null;await ctx.close();
 function consume(b,acc){for(let c=0;c<b.numberOfChannels;c++){const a=b.getChannelData(c);for(let i=0;i<a.length;i++)acc[c]+=a[i];}}
 async function operation(mode){const start=performance.now(),ac=new AudioContext({sampleRate:48000}),acc=[0,0];let first=null,frames=0,peak=0;try{for(const n of mode==='baseline'?['source.flac']:chunks){let b=await ac.decodeAudioData(await load(n));if(first===null)first=performance.now()-start;frames+=b.length;peak=Math.max(peak,b.length*b.numberOfChannels*4);consume(b,acc);b=null;}return {mode,wallMs:performance.now()-start,firstOutputMs:first,frames,peakRetainedPCMBytes:peak,checksum:acc};}finally{const before=performance.now();await ac.close();lastClose=performance.now()-before;}}
 let lastClose=0;const rows=[];for(let pair=-1;pair<5;pair++)for(const mode of pair%2===0?['baseline','candidate']:['candidate','baseline']){const row=await operation(mode);row.wallMs+=lastClose;row.closeMs=lastClose;row.pair=pair;if(pair>=0)rows.push(row);}
 const base=rows.find(r=>r.mode==='baseline');for(const r of rows)if(r.frames!==base.frames||JSON.stringify(r.checksum)!==JSON.stringify(base.checksum))throw Error('timed output mismatch');return {correctnessPassed:true,wholeFrames,chunkChecks:checks,wrongSampleControlRejected:wrongRejected,rows,cleanup:true};
 },setup.chunks);const rows=result.probe.rows,median=a=>a.sort((x,y)=>x-y)[Math.floor(a.length/2)],bm=median(rows.filter(r=>r.mode==='baseline').map(r=>r.wallMs)),cm=median(rows.filter(r=>r.mode==='candidate').map(r=>r.wallMs)),bpeak=rows.find(r=>r.mode==='baseline').peakRetainedPCMBytes,cpeak=rows.find(r=>r.mode==='candidate').peakRetainedPCMBytes;result.metrics={baselineMedianMs:bm,candidateMedianMs:cm,wallRatio:cm/bm,baselineRetainedPCMBytes:bpeak,candidateRetainedPCMBytes:cpeak,retainedRatio:cpeak/bpeak,coldCandidateMs:cm+setup.preparation_seconds*1000,preparedThresholdPassed:cm<=1.25*bm&&cpeak<=bpeak/8,coldThresholdPassed:cm+setup.preparation_seconds*1000<=1.25*bm};result.completed=true;}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.close();fs.writeFileSync(dir+'/results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,probe:result.probe?{...result.probe,rows:result.probe.rows.length}:undefined}));}
