# SPDX-License-Identifier: Apache-2.0
# The coefficient artifact is derived from separately licensed original FFmpeg LGPL source.
import pathlib,sys,struct,subprocess,json,re,random,math,array,time,statistics,hashlib
p=pathlib.Path(sys.argv[1]);p.mkdir(parents=True,exist_ok=True);upstream=pathlib.Path('build/local-screening/adaptation-reference/source/FFmpeg-n7.1.1/libavcodec/dsd.c');text=upstream.read_text();body=re.search(r'htaps\[HTAPS\]\s*=\s*\{([^}]+)',text)[1];half=[float(x)for x in re.findall(r'[-+]?\d+(?:\.\d*)?(?:e[-+]?\d+)?',body)];assert len(half)==48;h=list(reversed(half))+half;g=[]
for i in range(17):
 n=i-8;v=.1 if n==0 else math.sin(2*math.pi*.05*n)/(math.pi*n);g.append(v*(.54-.46*math.cos(2*math.pi*i/16)))
g=[x/sum(g)for x in g];coeff=p/'coefficients.bin';coeff.write_bytes(struct.pack('<II',len(h),len(g))+array.array('d',h+g).tobytes());(p/'coefficient-notice.txt').write_text(text[:text.index('#include')]+'\n96tap first filter coefficients derived from FFmpeg dsd.c;17tap second filter original research policy, no general audio-quality certification.\n');rng=random.Random(348);raw=bytes([0x96])*128+rng.randbytes(12582912)+bytes([0x96])*128;source=p/'source.dsd';source.write_bytes(raw);dsf=b'DSD '+struct.pack('<QQQ',28,92+len(raw),0)+b'fmt '+struct.pack('<QIIIIIIQII',52,1,0,1,1,2822400,1,len(raw)*8,4096,0)+b'data'+struct.pack('<Q',12+len(raw))+raw;(p/'source.dsf').write_bytes(dsf)
(p/'protocol.json').write_text(json.dumps({'scope':'Specific FFmpeg96tap DSD lowpass at2.8224MHz→352.8k PCM, followed by explicit17tap PCM FIR decimation8 to44.1k. Candidate composes K[l]=sum_j g[j]h[l-8j] and uses packed-byte lookup tables directly. Baseline also packed-byte tables, not naive bit expansion.','correctness':'Compare baseline and fused full requested44100rate output against actual FFmpeg DSD decode then independent Python second FIR. Explicit1e-6abs tolerance accommodates eliminated intermediatefloat rounding.128packed-byte prefix establishes declared history,128byte tail covers compositeFIR; same sample phase/delay. Wrong bitorder/filter controls, malformed metadata/rate/identity not part bare component; source and coefficient hashes pinned.','performance':'Followup16x longer12.58MB packed input, five alternating compiled complete packed read, cold table construction, actual filtering, retained intermediate where applicable, output write/read; Median paired cost ratio<=0.9 and at least4of5 pairs faster; compile excluded. Baseline retains efficient packed lookup behavior. No broad DSD decoder or spectral-quality claim.'},indent=2));exe=p/'filter';build=['c++','-std=c++17','-O2','research/shared/tooling/audio-stage-probes/dsd_fused_filter.cpp','-o',str(exe)];subprocess.run(build,check=True)
def job(mode):
 dest=p/(mode+'.f32');subprocess.run([str(exe),mode,str(coeff),str(source),str(dest)],check=True);a=array.array('f');a.frombytes(dest.read_bytes());return a
first=array.array('f');cmd=['ffmpeg','-v','error','-i',str(p/'source.dsf'),'-f','f32le','-'];first.frombytes(subprocess.check_output(cmd));assert len(first)==len(raw),(len(first),len(raw));reference=array.array('f',(sum(g[j]*first[q-j]for j in range(len(g)))for q in range(128,len(raw),8)));baseline=job('baseline');fused=job('fused');errors={'baselineOracle':max(abs(a-b)for a,b in zip(baseline,reference)),'fusedOracle':max(abs(a-b)for a,b in zip(fused,reference))};passed=len(reference)==len(fused)==len(baseline)and max(errors.values())<=1e-6;(p/'results.json').write_text(json.dumps({'samples':len(reference),'errors':errors,'correctnessPassed':passed,'intermediateBaselineFloatBytes':len(raw)*4,'fusedCoefficientCount':len(h)+8*(len(g)-1),'sourceSHA256':hashlib.sha256(raw).hexdigest()},indent=2));print(errors,passed,flush=True)
if passed:
 times={'fused':[],'baseline':[]}
 for trial in range(6):
  for mode in (['fused','baseline']if trial%2==0 else ['baseline','fused']):
   start=time.perf_counter_ns();out=job(mode);ms=(time.perf_counter_ns()-start)/1e6;assert max(abs(a-b)for a,b in zip(out,reference))<=1e-6
   if trial:times[mode].append(ms)
 med={k:statistics.median(v)for k,v in times.items()};ratio=med['fused']/med['baseline'];paired=[a/b for a,b in zip(times['fused'],times['baseline'])];pairedMedian=statistics.median(paired);cost={'timesMS':times,'medianMS':med,'ratio':ratio,'pairedRatios':paired,'medianPairedRatio':pairedMedian,'passed':pairedMedian<=.9 and sum(x<1 for x in paired)>=4};(p/'cost-results.json').write_text(json.dumps(cost,indent=2));print(cost)
(p/'commands.log').write_text(json.dumps(build)+'\n'+json.dumps(cmd)+'\npython3 research/shared/tooling/audio-stage-probes/dsd_fused_filter.py '+str(p)+'\n')
