# SPDX-License-Identifier: Apache-2.0
import pathlib,subprocess,json,sys,hashlib,array
p=pathlib.Path(sys.argv[1]);p.mkdir(parents=True,exist_ok=True);source=pathlib.Path('/tmp/demuxe-research-dts/bond_sample_dtshdma.m2ts');commands=[]
def call(a):commands.append(a);return subprocess.check_output(a,stderr=subprocess.DEVNULL)
b=['ffmpeg','-v','error','-y'];call(b+['-i',str(source),'-map','0:1','-t','3.5','-c:a','copy','-f','dts',str(p/'original-hd.dts')]);call(b+['-i',str(p/'original-hd.dts'),'-c:a','copy','-bsf:a','dca_core','-f','dts',str(p/'core.dts')]);call(b+['-i',str(p/'core.dts'),'-c:a','copy','-movflags','frag_keyframe+empty_moov+default_base_moof',str(p/'core.mp4')]);call(b+['-i',str(p/'core.dts'),'-c:a','flac','-sample_fmt','s32','-bits_per_raw_sample','24',str(p/'core-control.flac')])
def probe(f):return json.loads(call(['ffprobe','-v','error','-show_streams','-show_packets','-of','json',str(f)]))
a=probe(p/'original-hd.dts');c=probe(p/'core.dts');(p/'original-probe.json').write_text(json.dumps(a,indent=2));(p/'core-probe.json').write_text(json.dumps(c,indent=2));ab=(p/'original-hd.dts').read_bytes();cb=(p/'core.dts').read_bytes();assert len(a['packets'])==len(c['packets']);assert all(ab[int(x['pos']):int(x['pos'])+int(y['size'])]==cb[int(y['pos']):int(y['pos'])+int(y['size'])]for x,y in zip(a['packets'],c['packets']))
def pcm(f):return call(['ffmpeg','-v','error','-i',str(f),'-f','f32le','-'])
x=array.array('f');x.frombytes(pcm(p/'original-hd.dts'));y=array.array('f');y.frombytes(pcm(p/'core.dts'));r={'originalProfile':a['streams'][0]['profile'],'coreProfile':c['streams'][0]['profile'],'packets':len(c['packets']),'corePrefixesExact':True,'originalBytes':len(ab),'coreBytes':len(cb),'discardedBytes':len(ab)-len(cb),'sourcePCMFrames':len(x)//6,'corePCMFrames':len(y)//6,'fullFidelityPCMEqual':x==y,'maxError':max(abs(a-b)for a,b in zip(x,y))};assert r['originalProfile']=='DTS-HD MA' and r['coreProfile']=='DTS';(p/'host-results.json').write_text(json.dumps(r,indent=2));(p/'provenance.json').write_text(json.dumps({'url':'https://samples.ffmpeg.org/A-codecs/DTS/bond_sample_dtshdma.m2ts','local':str(source),'sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'license':'NOASSERTION','restriction':'External FFmpeg sample archive fixture and derivedmedia; no redistribution grant established. Local research only, retain upstream attribution; do not label original CC-BY.'},indent=2));(p/'protocol.json').write_text(json.dumps({'item':'R029.offer-explicit-compatible-core-extraction-before-audio-re-encoding','scope':'Actual DTS-HD MA5.1 core-plus-extension source; explicit research permission discards extensions, coreprefix packet copy verified, fullPCM different expected. Exact Chrome native DTS core raw andMP4 destinations tested before preservedvideo or costwork.','stop':'If extractedcore unsupported, stop destination profile; do not claim extraction admits playback. HostFLACdecodedpositivecontrol distinguishes corruptfixture fromnativecodecabsence.','performance':'Blocked if native coredestination correctness fails; no speculative speedbenchmark.'},indent=2));(p/'commands.log').write_text('\n'.join(map(json.dumps,commands))+'\n');print(r)
