# SPDX-License-Identifier: Apache-2.0
import pathlib,sys,json,subprocess,os,hashlib,shutil,time
root=pathlib.Path.cwd();out=pathlib.Path(sys.argv[1]).resolve();out.mkdir(parents=True,exist_ok=True);old=root/'build/local-screening/adaptation-reference';manifest=json.loads((old/'engine-1789826284257134000/manifest.json').read_text());sdk=pathlib.Path('/Volumes/seed2/Projects/webmpv/build/emsdk-4.0.14/upstream/emscripten');commands=[];files={}
for n in ['native/remux/remux.c','native/adaptation/flac.h']:
 f=root/n;dest=out/'sources'/n;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(f,dest);files[n]=hashlib.sha256(f.read_bytes()).hexdigest()
f=out/'sources/native/adaptation/flac.h';s=f.read_text();needle='r=avcodec_open2(adapt_encoder,enc,NULL);';assert s.count(needle)==1;s=s.replace(needle,'if(adapt_enabled==1)adapt_encoder->frame_size=4608; /* research: isolate effort at fixed duration */\n '+needle);f.write_text(s)
config=out/'emscripten.config';config.write_text((old/'emscripten.config').read_text());env={**os.environ,'EM_CONFIG':str(config),'PATH':str(sdk)+os.pathsep+os.environ['PATH'],'SOURCE_DATE_EPOCH':'1740000000'}
for level in [0,5]:
 engine=out/f'level{level}';engine.mkdir();args=[str(sdk/'emcc')]+manifest['linkCommand'][1:];args=[x.replace('-DDEMUXE_FLAC_LEVEL=5','-DDEMUXE_FLAC_LEVEL='+str(level)).replace(str(root/'native/remux/remux.c'),str(out/'sources/native/remux/remux.c'))for x in args];args[-1]=str(engine/'remux.mjs');t=time.perf_counter();r=subprocess.run(args,env=env,capture_output=True);commands.append({'args':args,'elapsedSeconds':time.perf_counter()-t,'exit':r.returncode,'stderr':r.stderr.decode(errors='replace')});assert r.returncode==0;subprocess.run(['node','--input-type=module','-e','import fs from "node:fs";if(!WebAssembly.validate(fs.readFileSync(process.argv[1])))throw Error("Invalid Wasm")',str(engine/'remux.wasm')],check=True)
(out/'build-results.json').write_text(json.dumps({'originalSources':files,'baselineManifest':str(old/'engine-1789826284257134000/manifest.json'),'variant':'copied maintainedadapter source, fixed4608frames bothlevels, onlyeffort macro differs','commands':commands},indent=2));(out/'commands.log').write_text('\n'.join(json.dumps(c['args'])for c in commands)+'\n');print('linked bothlevels')
