# SPDX-License-Identifier: Apache-2.0
import pathlib,sys,subprocess,json,hashlib,struct
p=pathlib.Path(sys.argv[1]);p.mkdir(parents=True,exist_ok=True);commands=[]
def run(a):
 r=subprocess.run(a,capture_output=True);commands.append({'args':a,'code':r.returncode,'stderr':r.stderr.decode(errors='replace')});return r
base=['ffmpeg','-v','error','-y'];protocol={'R223':'8s48kstereoFLAC4608blocks; suffix originalframes42..end; correctSTREAMINFO totals, zeroMD5 unknown. Preserve everycompletecodedframebyte.','R245':'6s48kstereoFLAC4096blocks; originalframes20..22; correcttotal12288, recomputeMD5 via boundedPCM verification (costmustchargeit). Preserveeverycompletecodedframebyte.','correctness':'Hostcontinuousreference exactsequentialPCM, correctreportedcount/duration, independentlibFLACseek skip0/1/interior/nearend exact512framewindows, corruptedCRC mustreject. If exactfull-frame copy breaks standalone seek/numbering, stopprofilebeforecost. Headerrewriting belongs separatelyqualified mechanism.','performance':'Only after correctness, full cold constructionincludingchecksums and destination versusdecode-crop-reencode; no benchmark if seekfails.'};(p/'protocol.json').write_text(json.dumps(protocol,indent=2));results={}
for key,duration,block,start,stop in [('R223',8,4608,42,None),('R245',6,4096,20,23)]:
 source=p/(key+'-source.flac');r=run(base+['-f','lavfi','-i',r'aevalsrc=0.2*sin(2*PI*(431*t+71*t*t))|0.1*sin(2*PI*(719*t+53*t*t)):s=48000:d='+str(duration),'-sample_fmt','s16','-c:a','flac','-frame_size',str(block),str(source)]);assert r.returncode==0
 data=source.read_bytes();packets=json.loads(run(['ffprobe','-v','error','-show_packets','-of','json',str(source)]).stdout)['packets'];chosen=packets[start:stop];frames=[data[int(x['pos']):int(x['pos'])+int(x['size'])]for x in chosen];n=sum(int(x['duration'])for x in chosen);offset=int(chosen[0]['pts']);ref=run(['ffmpeg','-v','error','-i',str(source),'-f','s16le','-']).stdout[offset*4:(offset+n)*4];si=bytearray(data[8:42]);packed=int.from_bytes(si[10:18],'big');si[10:18]=((packed&~((1<<36)-1))|n).to_bytes(8,'big');si[18:34]=hashlib.md5(ref).digest()if key=='R245'else b'\0'*16;micro=b'fLaC\x80\x00\x00\x22'+si+b''.join(frames);dest=p/(key+'-micro.flac');dest.write_bytes(micro);decoded=run(['ffmpeg','-v','error','-i',str(dest),'-f','s16le','-']);whole=decoded.returncode==0 and decoded.stdout==ref;test=run(['flac','-t','-s',str(dest)]);seeks=[]
 for at in [0,1,min(5000,n-512),n-512]:
  output=p/f'{key}-seek-{at}.s16';r=run(['flac','--silent','--force','--decode','--force-raw-format','--endian=little','--sign=signed',f'--skip={at}','--until=+512','-o',str(output),str(dest)]);actual=output.read_bytes()if output.exists()else b'';seeks.append({'at':at,'exit':r.returncode,'exact':actual==ref[at*4:(at+512)*4],'bytes':len(actual),'stderr':r.stderr.decode(errors='replace')})
 corrupt=bytearray(micro);corrupt[42+len(frames[0])-1]^=1;bad=p/(key+'-crc-corrupt.flac');bad.write_bytes(corrupt);badtest=run(['flac','-t','-s',str(bad)]);stream=json.loads(run(['ffprobe','-v','error','-show_streams','-of','json',str(dest)]).stdout)['streams'][0];results[key]={'sourceFrames':len(packets),'selectedFrames':len(frames),'startSample':offset,'samples':n,'wholePCMExact':whole,'duration':stream['duration'],'expectedDuration':n/48000,'framePayloadHashesUnchanged':True,'frameHashes':[hashlib.sha256(x).hexdigest()for x in frames],'md5Policy':'bounded reference checksum'if key=='R245'else'explicit unknown zeros','flacTestCode':test.returncode,'flacTestStderr':test.stderr.decode(errors='replace'),'seeks':seeks,'corruptedCRCRejected':badtest.returncode!=0,'correctnessPassed':whole and all(x['exact']for x in seeks)and badtest.returncode!=0}
(p/'results.json').write_text(json.dumps(results,indent=2));(p/'commands.log').write_text('\n'.join(map(json.dumps,commands))+'\n');print({k:{x:v for x,v in r.items()if x not in ['frameHashes','flacTestStderr','seeks']}for k,r in results.items()});print({k:r['seeks']for k,r in results.items()})
