// SPDX-License-Identifier: Apache-2.0
import http from 'node:http';
import {chromium} from 'playwright';import {spawn,spawnSync} from 'node:child_process';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {performance} from 'node:perf_hooks';
const out=process.argv[2];await mkdir(out,{recursive:true});const protocol={item:'R117.play-iamf-through-native-component-decoders',scope:'Strict actual host ffprobe IAMF flat stereo zero-gain one-element admission and copied FLAC extraction, browser native component decode and unity-gain single-clock render; not browser-only demux',correctness:'All96000 signed16stereo frames exact against originalsource; unsupportedgain and truncated component reject, whole-source offline playback, ended ownership cleanup',performance:'After fresh correctness,1warmup5alternating full host admission/extraction or reference PCM decode plus transfer and browser render pairs; candidate<=1.10baseline',threshold:1.1};await writeFile(out+'/protocol.json',JSON.stringify(protocol,null,2));const server=http.createServer(async(req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end('<html></html>');return;}try{const name=new URL(req.url,'http://local').pathname.split('/').pop();if(!['component.flac','reference.s16'].includes(name))throw Error('path');res.end(await readFile(out+'/'+name));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;const result={rows:[]};function prepare(mode){const t=performance.now();const r=spawnSync('python3',['research/shared/tooling/audio-stage-probes/iamf_host_bridge.py',out,mode]);if(r.status)throw Error(String(r.stderr));return performance.now()-t;}
try{const origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const p=await browser.newPage();await p.goto(origin+'/');prepare('baseline');
const rb=await readFile(out+'/reference.s16'),ref=[...new Int16Array(rb.buffer,rb.byteOffset,rb.length/2)];
await p.evaluate(ref=>{globalThis.iamfRef=ref;},ref);
async function run(mode,controls=false){const t=performance.now(),hostMs=prepare(mode),file=out+'/'+(mode==='candidate'?'component.flac':'reference.s16');const r=await p.evaluate(async({mode,file,controls})=>{const bytes=new Uint8Array(await (await fetch('/'+file+'?t='+Math.random())).arrayBuffer()),ref=globalThis.iamfRef;const ctx=new OfflineAudioContext(2,96000,48000);let buffer;if(mode==='candidate')buffer=await ctx.decodeAudioData(new Uint8Array(bytes).buffer);else{buffer=ctx.createBuffer(2,96000,48000);const pcm=new Int16Array(new Uint8Array(bytes).buffer);for(let ch=0;ch<2;ch++){const a=buffer.getChannelData(ch);for(let i=0;i<96000;i++)a[i]=pcm[i*2+ch]/(pcm[i*2+ch]<0?32768:32767);}}if(buffer.length!==96000||buffer.numberOfChannels!==2)throw Error('shape');let mismatch=0;for(let ch=0;ch<2;ch++)for(let i=0;i<96000;i++){const x=buffer.getChannelData(ch)[i],q=Math.round(x*(x<0?32768:32767));if(q!==ref[i*2+ch])mismatch++;}if(mismatch)throw Error('PCM mismatch '+mismatch);let trunc=false;if(controls){try{await ctx.decodeAudioData(new Uint8Array(bytes.slice(0,12)).buffer);}catch{trunc=true;}if(!trunc)throw Error('truncated');}const source=ctx.createBufferSource(),gain=ctx.createGain();gain.gain.value=1;source.buffer=buffer;source.connect(gain);gain.connect(ctx.destination);let ended=false;source.onended=()=>ended=true;source.start();const rendered=await ctx.startRendering();await new Promise(r=>setTimeout(r,0));let renderedMismatch=0;for(let ch=0;ch<2;ch++)for(let i=0;i<96000;i++)if(rendered.getChannelData(ch)[i]!==buffer.getChannelData(ch)[i])renderedMismatch++;source.disconnect();gain.disconnect();if(!ended||renderedMismatch||ctx.state!=='closed')throw Error('render lifecycle');return {frames:buffer.length,mismatch,renderedMismatch,ended,closed:ctx.state==='closed',truncatedRejected:trunc};},{mode,file,controls});return {mode,hostMs,totalMs:performance.now()-t,...r};}
result.correctness=await run('candidate',true);for(let i=0;i<6;i++)for(const mode of(i%2?['baseline','candidate']:['candidate','baseline'])){const r=await run(mode);if(i)result.rows.push({pair:i,...r});}const med=a=>a.sort((x,y)=>x-y)[a.length>>1];result.candidateMedianMs=med(result.rows.filter(r=>r.mode==='candidate').map(r=>r.totalMs));result.baselineMedianMs=med(result.rows.filter(r=>r.mode==='baseline').map(r=>r.totalMs));result.ratio=result.candidateMedianMs/result.baselineMedianMs;result.performancePassed=result.ratio<=1.1;}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.close();await writeFile(out+'/results.json',JSON.stringify(result,null,2)+'\n');}console.log(result);
