// SPDX-License-Identifier: Apache-2.0
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import fs from 'node:fs';import assert from 'node:assert/strict';
const dir=process.argv[2],files={};for(const n of ['audio-44100.mp4','audio-48000.mp4','pulse.mp4'])files[n]=[...fs.readFileSync(dir+'/'+n)];for(const n of ['small.mp4','large.mp4'])files[n]=[...fs.readFileSync('results/top100/lanes/'+n)];
const server=spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:'0'},stdio:['ignore','pipe','inherit']});let browser;const result={profile:'isolated browser split-MSE source-rate changes and explicit audio timestamp offsets',cases:[]};
try{const origin=await new Promise((res,rej)=>{const t=setTimeout(()=>rej(Error('server timeout')),10000);server.stdout.on('data',b=>{const m=String(b).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);res(m[0]);}});});browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();const page=await browser.newPage();await page.goto(origin+'/web/audio-worklet.js');
for(const mode of ['rate-44100-48000','rate-48000-44100','offset-positive','offset-negative']){
 const row=await page.evaluate(async({mode,files})=>{
  const v=document.createElement('video');document.body.append(v);const ac=new AudioContext();await ac.resume();const src=ac.createMediaElementSource(v),an=ac.createAnalyser();an.fftSize=4096;src.connect(an);an.connect(ac.destination);const m=new MediaSource(),url=URL.createObjectURL(m);const row={mode,observed:[]};
  const event=(o,type)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>{clean();reject(Error(type+' timeout'));},8000);const good=()=>{clean();resolve();},bad=()=>{clean();reject(Error(type+' error'));};function clean(){clearTimeout(timer);o.removeEventListener(type,good);o.removeEventListener('error',bad);}o.addEventListener(type,good);o.addEventListener('error',bad);});let timer,phase='forward';
  try{const opened=event(m,'sourceopen');v.src=url;await opened;const video=m.addSourceBuffer('video/mp4; codecs="avc3.42C00D"'),audio=m.addSourceBuffer('audio/mp4; codecs="mp4a.40.2"');const append=async(sb,bytes)=>{const done=event(sb,'updateend');sb.appendBuffer(new Uint8Array(bytes));await done;};await append(video,files['small.mp4']);video.timestampOffset=2;await append(video,files['large.mp4']);
   if(mode.startsWith('rate')){const rates=mode.split('-').slice(1);audio.appendWindowEnd=2;await append(audio,files[`audio-${rates[0]}.mp4`]);audio.appendWindowEnd=4;audio.timestampOffset=2;await append(audio,files[`audio-${rates[1]}.mp4`]);row.rates=rates.map(Number);}
   else{audio.timestampOffset=mode==='offset-positive'?.35:-.25;row.requestedOffset=audio.timestampOffset;await append(audio,files['pulse.mp4']);const ranges=()=>Array.from({length:audio.buffered.length},(_,i)=>[audio.buffered.start(i),audio.buffered.end(i)]);row.beforePropertyOnlyChange=ranges();audio.timestampOffset=1;row.afterPropertyOnlyChange=ranges();audio.timestampOffset=row.requestedOffset;}
   m.endOfStream();const ended=event(v,'ended');await v.play();timer=setInterval(()=>{const f=new Float32Array(an.frequencyBinCount),t=new Float32Array(an.fftSize);an.getFloatFrequencyData(f);an.getFloatTimeDomainData(t);let best=1;for(let i=2;i<f.length;i++)if(f[i]>f[best])best=i;row.observed.push({phase,time:v.currentTime,width:v.videoWidth,frames:v.getVideoPlaybackQuality().totalVideoFrames,hz:best*ac.sampleRate/an.fftSize,db:f[best],rms:Math.sqrt(t.reduce((n,x)=>n+x*x,0)/t.length)});},30);await ended;row.eof=true;
   // Backward restoration uses the same element and both source buffers.
   phase='backward';const seeked=event(v,'seeked');v.currentTime=.6;await seeked;await v.play();await new Promise(r=>setTimeout(r,350));v.pause();row.backwardTime=v.currentTime;row.sameVideoBuffer=m.sourceBuffers[0]===video;row.sameAudioBuffer=m.sourceBuffers[1]===audio;row.paused=v.paused;
   if(!mode.startsWith('rate')){phase='paused-update';const removed=event(audio,'updateend');audio.remove(0,5);await removed;row.updatedOffset=-row.requestedOffset;audio.timestampOffset=row.updatedOffset;await append(audio,files['pulse.mp4']);m.endOfStream();v.currentTime=.05;const updatedEnded=event(v,'ended');await v.play();await updatedEnded;row.pausedUpdateEof=true;}
  }catch(e){row.error=String(e);row.mediaError=v.error?.message;}finally{clearInterval(timer);v.pause();v.removeAttribute('src');v.load();v.remove();URL.revokeObjectURL(url);src.disconnect();an.disconnect();await ac.close();row.cleanup=true;}return row;
 },{mode,files});
 if(mode.startsWith('rate')){const expected=row.rates?.map(r=>r===44100?440:880)||[];row.firstInterval=row.observed.some(s=>s.time>.5&&s.time<1.5&&Math.abs(s.hz-expected[0])<25&&s.db>-70);row.secondInterval=row.observed.some(s=>s.time>2.5&&s.time<3.5&&Math.abs(s.hz-expected[1])<25&&s.db>-70);row.passed=!!(row.firstInterval&&row.secondInterval&&row.sameVideoBuffer&&row.sameAudioBuffer&&row.eof&&row.cleanup);}
 else{const start=.5+row.requestedOffset,end=1.3+row.requestedOffset;const tone=row.observed.filter(s=>s.phase==='forward'&&s.time>start+.2&&s.time<end-.1);const quiet=row.observed.filter(s=>s.phase==='forward'&&s.time>Math.max(0,start-.3)&&s.time<start-.1);row.toneSamples=tone.length;row.quietSamples=quiet.length;row.toneCorrect=tone.length>2&&tone.every(s=>Math.abs(s.hz-660)<25&&s.rms>.04);row.quietCorrect=quiet.length>1&&quiet.every(s=>s.rms<.01);row.propertyOnlyDoesNotRetime=JSON.stringify(row.beforePropertyOnlyChange)===JSON.stringify(row.afterPropertyOnlyChange);const changedTone=row.observed.filter(s=>s.phase==='paused-update'&&s.time>.5+row.updatedOffset+.2&&s.time<1.3+row.updatedOffset-.1);row.updatedToneCorrect=changedTone.length>2&&changedTone.every(s=>Math.abs(s.hz-660)<25&&s.rms>.04);row.passed=!!(row.updatedToneCorrect&&row.pausedUpdateEof&&row.toneCorrect&&row.quietCorrect&&row.propertyOnlyDoesNotRetime&&row.sameVideoBuffer&&row.cleanup);}
 result.cases.push(row);fs.writeFileSync(dir+'/browser-result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...row,observed:row.observed.length}));
}
result.passed=result.cases.every(x=>x.passed);assert.ok(result.passed);
}catch(e){result.error=String(e.stack);process.exitCode=1;}finally{await browser?.close();server.kill();fs.writeFileSync(dir+'/browser-result.json',JSON.stringify(result,null,2)+'\n');}
